// Code generated by Scalar SDK Generator. DO NOT EDIT.

package dedalus

import (
	"github.com/dedalus-labs/dedalus-go/option"
)

// MachineTerminalService contains methods and other services that help with interacting
// with the API. You should not instantiate this service directly, and instead use
// the [NewMachineTerminalService] method instead.
type MachineTerminalService struct {
	Options []option.RequestOption
}

// NewMachineTerminalService generates a new service that applies the given options to each request.
// These options are applied after the parent client's options (if there is one), and
// before any request-specific options.
func NewMachineTerminalService(opts ...option.RequestOption) (r *MachineTerminalService) {
	r = &MachineTerminalService{}
	r.Options = opts
	return
}

type MachineTerminalConnectParams struct {
	MachineID  string `path:"machine_id" api:"required" json:"-"`
	TerminalID string `path:"terminal_id" api:"required" json:"-"`
}
