// Code generated by Scalar SDK Generator. DO NOT EDIT.

package dedalus

import (
	"context"
	"errors"
	"fmt"
	"net/http"
	"net/url"
	"slices"
	"time"

	"github.com/dedalus-labs/dedalus-go/internal/apijson"
	"github.com/dedalus-labs/dedalus-go/internal/apiquery"
	"github.com/dedalus-labs/dedalus-go/internal/param"
	"github.com/dedalus-labs/dedalus-go/internal/requestconfig"
	"github.com/dedalus-labs/dedalus-go/option"
	"github.com/dedalus-labs/dedalus-go/packages/pagination"
	"github.com/dedalus-labs/dedalus-go/packages/ssestream"
)

// MachineService contains methods and other services that help with interacting
// with the API. You should not instantiate this service directly, and instead use
// the [NewMachineService] method instead.
type MachineService struct {
	Options    []option.RequestOption
	Network    *MachineNetworkService
	Artifacts  *MachineArtifactService
	Ports      *MachinePortService
	SSH        *MachineSSHService
	Executions *MachineExecutionService
	Terminals  *MachineTerminalService
}

// NewMachineService generates a new service that applies the given options to each request.
// These options are applied after the parent client's options (if there is one), and
// before any request-specific options.
func NewMachineService(opts ...option.RequestOption) (r *MachineService) {
	r = &MachineService{}
	r.Options = opts
	r.Network = NewMachineNetworkService(opts...)
	r.Artifacts = NewMachineArtifactService(opts...)
	r.Ports = NewMachinePortService(opts...)
	r.SSH = NewMachineSSHService(opts...)
	r.Executions = NewMachineExecutionService(opts...)
	r.Terminals = NewMachineTerminalService(opts...)
	return
}

// List machines
//
// Parameters:
//
//	ctx: Context for the request.
//	query: MachineListParams request parameters.
//	opts: Options to apply to this request.
//
// Returns:
//
//	*pagination.CursorPage[MachineListItem]: OK
//
// Example:
//
//	page, err := client.Machines.List(context.Background(), sdk.MachineListParams{})
//	if err != nil {
//		panic(err)
//	}
//
//	fmt.Println(page)
func (r *MachineService) List(ctx context.Context, query MachineListParams, opts ...option.RequestOption) (res *pagination.CursorPage[MachineListItem], err error) {
	var raw *http.Response
	if query.XDedalusOrgID.Present {
		opts = append(opts, option.WithHeader("X-Dedalus-Org-Id", fmt.Sprintf("%v", query.XDedalusOrgID.Value)))
	}
	opts = slices.Concat(r.Options, opts)
	opts = append([]option.RequestOption{option.WithResponseInto(&raw)}, opts...)
	path := "v1/machines"
	cfg, err := requestconfig.NewRequestConfig(ctx, http.MethodGet, path, query, &res, opts...)
	if err != nil {
		return nil, err
	}
	err = cfg.Execute()
	if err != nil {
		return nil, err
	}
	res.SetPageConfig(cfg, raw)
	return res, nil
}

// ListAutoPaging returns an auto-pager for List.
//
// Returns:
//
//	*pagination.CursorPageAutoPager[MachineListItem]
func (r *MachineService) ListAutoPaging(ctx context.Context, query MachineListParams, opts ...option.RequestOption) *pagination.CursorPageAutoPager[MachineListItem] {
	return pagination.NewCursorPageAutoPager(r.List(ctx, query, opts...))
}

// Create machine
//
// Parameters:
//
//	ctx: Context for the request.
//	body: MachineNewParams request parameters.
//	opts: Options to apply to this request.
//
// Returns:
//
//	*Machine: Create converged inline
//
// Example:
//
//	machine, err := client.Machines.New(context.Background(), sdk.MachineNewParams{
//		CreateParams: sdk.CreateParams{
//			Autosleep:  sdk.F[string]("300s"),
//			MemoryMib:  sdk.F[int64](4096),
//			StorageGib: sdk.F[int64](10),
//			Vcpu:       sdk.F[float64](1),
//		},
//	})
//	if err != nil {
//		panic(err)
//	}
//
//	fmt.Println(machine.MachineID)
func (r *MachineService) New(ctx context.Context, body MachineNewParams, opts ...option.RequestOption) (res *Machine, err error) {
	if body.XDedalusOrgID.Present {
		opts = append(opts, option.WithHeader("X-Dedalus-Org-Id", fmt.Sprintf("%v", body.XDedalusOrgID.Value)))
	}
	opts = slices.Concat(r.Options, opts)
	path := "v1/machines"
	err = requestconfig.ExecuteNewRequest(ctx, http.MethodPost, path, body, &res, opts...)
	return res, err
}

// Get machine
//
// Parameters:
//
//	ctx: Context for the request.
//	params: MachineGetParams request parameters.
//	opts: Options to apply to this request.
//
// Returns:
//
//	*MachineGetResponse: OK
//
// Example:
//
//	machine, err := client.Machines.Get(context.Background(), sdk.MachineGetParams{
//		MachineID: "machineID",
//	})
//	if err != nil {
//		panic(err)
//	}
//
//	fmt.Println(machine.MachineID)
func (r *MachineService) Get(ctx context.Context, params MachineGetParams, opts ...option.RequestOption) (res *MachineGetResponse, err error) {
	if params.XDedalusOrgID.Present {
		opts = append(opts, option.WithHeader("X-Dedalus-Org-Id", fmt.Sprintf("%v", params.XDedalusOrgID.Value)))
	}
	opts = slices.Concat(r.Options, opts)
	if params.MachineID == "" {
		err = errors.New("missing required machine_id parameter")
		return nil, err
	}
	path := fmt.Sprintf("v1/machines/%s", url.PathEscape(params.MachineID))
	err = requestconfig.ExecuteNewRequest(ctx, http.MethodGet, path, nil, &res, opts...)
	return res, err
}

// Update machine
//
// Parameters:
//
//	ctx: Context for the request.
//	body: MachineUpdateParams request parameters.
//	opts: Options to apply to this request.
//
// Returns:
//
//	*Machine: OK
//
// Example:
//
//	machine, err := client.Machines.Update(context.Background(), sdk.MachineUpdateParams{
//		MachineID:    "machineID",
//		UpdateParams: sdk.UpdateParams{},
//	})
//	if err != nil {
//		panic(err)
//	}
//
//	fmt.Println(machine.MachineID)
func (r *MachineService) Update(ctx context.Context, body MachineUpdateParams, opts ...option.RequestOption) (res *Machine, err error) {
	if body.XDedalusOrgID.Present {
		opts = append(opts, option.WithHeader("X-Dedalus-Org-Id", fmt.Sprintf("%v", body.XDedalusOrgID.Value)))
	}
	opts = slices.Concat(r.Options, opts)
	if body.MachineID == "" {
		err = errors.New("missing required machine_id parameter")
		return nil, err
	}
	path := fmt.Sprintf("v1/machines/%s", url.PathEscape(body.MachineID))
	err = requestconfig.ExecuteNewRequest(ctx, http.MethodPatch, path, body, &res, opts...)
	return res, err
}

// Destroy machine
//
// Parameters:
//
//	ctx: Context for the request.
//	params: MachineDeleteParams request parameters.
//	opts: Options to apply to this request.
//
// Returns:
//
//	*Machine: OK
//
// Example:
//
//	machine, err := client.Machines.Delete(context.Background(), sdk.MachineDeleteParams{
//		MachineID: "machineID",
//	})
//	if err != nil {
//		panic(err)
//	}
//
//	fmt.Println(machine.MachineID)
func (r *MachineService) Delete(ctx context.Context, params MachineDeleteParams, opts ...option.RequestOption) (res *Machine, err error) {
	if params.XDedalusOrgID.Present {
		opts = append(opts, option.WithHeader("X-Dedalus-Org-Id", fmt.Sprintf("%v", params.XDedalusOrgID.Value)))
	}
	opts = slices.Concat(r.Options, opts)
	if params.MachineID == "" {
		err = errors.New("missing required machine_id parameter")
		return nil, err
	}
	path := fmt.Sprintf("v1/machines/%s", url.PathEscape(params.MachineID))
	err = requestconfig.ExecuteNewRequest(ctx, http.MethodDelete, path, nil, &res, opts...)
	return res, err
}

// Streams machine lifecycle updates over Server-Sent Events. Each `status` event contains a full `LifecycleResponse` payload. The stream closes after the machine reaches its current desired state.
//
// Parameters:
//
//	ctx: Context for the request.
//	params: MachineWatchParams request parameters.
//	opts: Options to apply to this request.
//
// Returns:
//
//	*ssestream.Stream[Machine]: Server-Sent Event stream (`text/event-stream`) of machine lifecycle updates.
//
// Example:
//
//	stream := client.Machines.WatchStreaming(context.Background(), sdk.MachineWatchParams{
//		MachineID: "machineID",
//	})
//	defer stream.Close()
//
//	for stream.Next() {
//		event := stream.Current()
//		fmt.Println(event)
//	}
//	if err := stream.Err(); err != nil {
//		panic(err)
//	}
func (r *MachineService) WatchStreaming(ctx context.Context, params MachineWatchParams, opts ...option.RequestOption) (stream *ssestream.Stream[Machine]) {
	var (
		raw *http.Response
		err error
	)
	if params.LastEventID.Present {
		opts = append(opts, option.WithHeader("Last-Event-ID", fmt.Sprintf("%v", params.LastEventID.Value)))
	}
	if params.XDedalusOrgID.Present {
		opts = append(opts, option.WithHeader("X-Dedalus-Org-Id", fmt.Sprintf("%v", params.XDedalusOrgID.Value)))
	}
	opts = slices.Concat(r.Options, opts)
	opts = append([]option.RequestOption{option.WithHeader("Accept", "text/event-stream")}, opts...)
	if params.MachineID == "" {
		err = errors.New("missing required machine_id parameter")
		return ssestream.NewStream[Machine](nil, err)
	}
	path := fmt.Sprintf("v1/machines/%s/status/stream", url.PathEscape(params.MachineID))
	err = requestconfig.ExecuteNewRequest(ctx, http.MethodGet, path, nil, &raw, opts...)
	return ssestream.NewStream[Machine](ssestream.NewDecoder(raw), err)
}

// Sleep a running machine
//
// Parameters:
//
//	ctx: Context for the request.
//	params: MachineSleepParams request parameters.
//	opts: Options to apply to this request.
//
// Returns:
//
//	*Machine: OK
//
// Example:
//
//	machine, err := client.Machines.Sleep(context.Background(), sdk.MachineSleepParams{
//		MachineID: "machineID",
//	})
//	if err != nil {
//		panic(err)
//	}
//
//	fmt.Println(machine.MachineID)
func (r *MachineService) Sleep(ctx context.Context, params MachineSleepParams, opts ...option.RequestOption) (res *Machine, err error) {
	if params.XDedalusOrgID.Present {
		opts = append(opts, option.WithHeader("X-Dedalus-Org-Id", fmt.Sprintf("%v", params.XDedalusOrgID.Value)))
	}
	opts = slices.Concat(r.Options, opts)
	if params.MachineID == "" {
		err = errors.New("missing required machine_id parameter")
		return nil, err
	}
	path := fmt.Sprintf("v1/machines/%s/sleep", url.PathEscape(params.MachineID))
	err = requestconfig.ExecuteNewRequest(ctx, http.MethodPost, path, nil, &res, opts...)
	return res, err
}

// Wake a sleeping machine
//
// Parameters:
//
//	ctx: Context for the request.
//	params: MachineWakeParams request parameters.
//	opts: Options to apply to this request.
//
// Returns:
//
//	*Machine: OK
//
// Example:
//
//	machine, err := client.Machines.Wake(context.Background(), sdk.MachineWakeParams{
//		MachineID: "machineID",
//	})
//	if err != nil {
//		panic(err)
//	}
//
//	fmt.Println(machine.MachineID)
func (r *MachineService) Wake(ctx context.Context, params MachineWakeParams, opts ...option.RequestOption) (res *Machine, err error) {
	if params.XDedalusOrgID.Present {
		opts = append(opts, option.WithHeader("X-Dedalus-Org-Id", fmt.Sprintf("%v", params.XDedalusOrgID.Value)))
	}
	opts = slices.Concat(r.Options, opts)
	if params.MachineID == "" {
		err = errors.New("missing required machine_id parameter")
		return nil, err
	}
	path := fmt.Sprintf("v1/machines/%s/wake", url.PathEscape(params.MachineID))
	err = requestconfig.ExecuteNewRequest(ctx, http.MethodPost, path, nil, &res, opts...)
	return res, err
}

type Machine struct {
	// Seconds of inactivity before autosleep. 0 disables autosleep.
	AutosleepSeconds int64               `json:"autosleep_seconds" api:"required"`
	DesiredState     MachineDesiredState `json:"desired_state" api:"required"`
	MachineID        string              `json:"machine_id" api:"required"`
	// Memory in MiB.
	MemoryMib  int64        `json:"memory_mib" api:"required"`
	Phase      MachinePhase `json:"phase" api:"required"`
	StorageGib int64        `json:"storage_gib" api:"required"`
	// CPU in vCPUs.
	Vcpu float64     `json:"vcpu" api:"required"`
	JSON machineJSON `json:"-"`
}

// machineJSON contains the JSON metadata for the struct [Machine]
type machineJSON struct {
	AutosleepSeconds apijson.Field
	DesiredState     apijson.Field
	MachineID        apijson.Field
	MemoryMib        apijson.Field
	Phase            apijson.Field
	StorageGib       apijson.Field
	Vcpu             apijson.Field
	raw              string
	ExtraFields      map[string]apijson.Field
}

func (r *Machine) UnmarshalJSON(data []byte) (err error) {
	return apijson.UnmarshalRoot(data, r)
}

func (r machineJSON) RawJSON() string {
	return r.raw
}

type MachineDesiredState string

const (
	MachineDesiredStateRunning   MachineDesiredState = "running"
	MachineDesiredStateSleeping  MachineDesiredState = "sleeping"
	MachineDesiredStateDestroyed MachineDesiredState = "destroyed"
)

func (r MachineDesiredState) IsKnown() bool {
	switch r {
	case MachineDesiredStateRunning, MachineDesiredStateSleeping, MachineDesiredStateDestroyed:
		return true
	}
	return false
}

type MachinePhase string

const (
	MachinePhaseAccepted         MachinePhase = "accepted"
	MachinePhasePlacementPending MachinePhase = "placement_pending"
	MachinePhaseStarting         MachinePhase = "starting"
	MachinePhaseRunning          MachinePhase = "running"
	MachinePhaseStopping         MachinePhase = "stopping"
	MachinePhaseSleeping         MachinePhase = "sleeping"
	MachinePhaseDestroying       MachinePhase = "destroying"
	MachinePhaseDestroyed        MachinePhase = "destroyed"
	MachinePhaseFailed           MachinePhase = "failed"
)

func (r MachinePhase) IsKnown() bool {
	switch r {
	case MachinePhaseAccepted, MachinePhasePlacementPending, MachinePhaseStarting, MachinePhaseRunning, MachinePhaseStopping, MachinePhaseSleeping, MachinePhaseDestroying, MachinePhaseDestroyed, MachinePhaseFailed:
		return true
	}
	return false
}

type MachineList struct {
	Items      []MachineListItem `json:"items" api:"required,nullable"`
	NextCursor string            `json:"next_cursor"`
	JSON       machineListJSON   `json:"-"`
}

// machineListJSON contains the JSON metadata for the struct [MachineList]
type machineListJSON struct {
	Items       apijson.Field
	NextCursor  apijson.Field
	raw         string
	ExtraFields map[string]apijson.Field
}

func (r *MachineList) UnmarshalJSON(data []byte) (err error) {
	return apijson.UnmarshalRoot(data, r)
}

func (r machineListJSON) RawJSON() string {
	return r.raw
}

type MachineListItem struct {
	// Seconds of inactivity before autosleep. 0 disables autosleep.
	AutosleepSeconds int64                       `json:"autosleep_seconds" api:"required"`
	CreatedAt        time.Time                   `json:"created_at" api:"required" format:"date-time"`
	DesiredState     MachineListItemDesiredState `json:"desired_state" api:"required"`
	MachineID        string                      `json:"machine_id" api:"required"`
	// Memory in MiB.
	MemoryMib  int64                `json:"memory_mib" api:"required"`
	Phase      MachineListItemPhase `json:"phase" api:"required"`
	StorageGib int64                `json:"storage_gib" api:"required"`
	// CPU in vCPUs.
	Vcpu float64             `json:"vcpu" api:"required"`
	JSON machineListItemJSON `json:"-"`
}

// machineListItemJSON contains the JSON metadata for the struct [MachineListItem]
type machineListItemJSON struct {
	AutosleepSeconds apijson.Field
	CreatedAt        apijson.Field
	DesiredState     apijson.Field
	MachineID        apijson.Field
	MemoryMib        apijson.Field
	Phase            apijson.Field
	StorageGib       apijson.Field
	Vcpu             apijson.Field
	raw              string
	ExtraFields      map[string]apijson.Field
}

func (r *MachineListItem) UnmarshalJSON(data []byte) (err error) {
	return apijson.UnmarshalRoot(data, r)
}

func (r machineListItemJSON) RawJSON() string {
	return r.raw
}

type MachineListItemDesiredState string

const (
	MachineListItemDesiredStateRunning   MachineListItemDesiredState = "running"
	MachineListItemDesiredStateSleeping  MachineListItemDesiredState = "sleeping"
	MachineListItemDesiredStateDestroyed MachineListItemDesiredState = "destroyed"
)

func (r MachineListItemDesiredState) IsKnown() bool {
	switch r {
	case MachineListItemDesiredStateRunning, MachineListItemDesiredStateSleeping, MachineListItemDesiredStateDestroyed:
		return true
	}
	return false
}

type MachineListItemPhase string

const (
	MachineListItemPhaseAccepted         MachineListItemPhase = "accepted"
	MachineListItemPhasePlacementPending MachineListItemPhase = "placement_pending"
	MachineListItemPhaseStarting         MachineListItemPhase = "starting"
	MachineListItemPhaseRunning          MachineListItemPhase = "running"
	MachineListItemPhaseStopping         MachineListItemPhase = "stopping"
	MachineListItemPhaseSleeping         MachineListItemPhase = "sleeping"
	MachineListItemPhaseDestroying       MachineListItemPhase = "destroying"
	MachineListItemPhaseDestroyed        MachineListItemPhase = "destroyed"
	MachineListItemPhaseFailed           MachineListItemPhase = "failed"
)

func (r MachineListItemPhase) IsKnown() bool {
	switch r {
	case MachineListItemPhaseAccepted, MachineListItemPhasePlacementPending, MachineListItemPhaseStarting, MachineListItemPhaseRunning, MachineListItemPhaseStopping, MachineListItemPhaseSleeping, MachineListItemPhaseDestroying, MachineListItemPhaseDestroyed, MachineListItemPhaseFailed:
		return true
	}
	return false
}

type CreateParams struct {
	// Idle window before autosleep. Accepts fixed duration units like 30s, 30m, 2h,
	// 7d3h4s, or 1w3d, raw seconds ("1800"), or never to disable.
	Autosleep param.Field[string] `json:"autosleep"`
	// Memory in MiB.
	MemoryMib param.Field[int64] `json:"memory_mib"`
	// Storage in GiB.
	StorageGib param.Field[int64] `json:"storage_gib"`
	// CPU in vCPUs.
	Vcpu param.Field[float64] `json:"vcpu"`
}

func (r CreateParams) MarshalJSON() (data []byte, err error) {
	return apijson.MarshalRoot(r)
}

type UpdateParams struct {
	// Idle window before autosleep. Accepts fixed duration units like 30s, 30m, 2h,
	// 7d3h4s, or 1w3d, raw seconds ("1800"), or never to disable.
	Autosleep param.Field[string] `json:"autosleep"`
	// Memory in MiB.
	MemoryMib param.Field[int64] `json:"memory_mib"`
	// Storage in GiB.
	StorageGib param.Field[int64] `json:"storage_gib"`
	// CPU in vCPUs.
	Vcpu param.Field[float64] `json:"vcpu"`
}

func (r UpdateParams) MarshalJSON() (data []byte, err error) {
	return apijson.MarshalRoot(r)
}

type LifecycleStatus struct {
	LastProgressAt   time.Time            `json:"last_progress_at" api:"required" format:"date-time"`
	LastTransitionAt time.Time            `json:"last_transition_at" api:"required" format:"date-time"`
	Phase            LifecycleStatusPhase `json:"phase" api:"required"`
	Reason           string               `json:"reason" api:"required"`
	Retryable        bool                 `json:"retryable" api:"required"`
	Revision         string               `json:"revision" api:"required"`
	LastError        string               `json:"last_error"`
	JSON             lifecycleStatusJSON  `json:"-"`
}

// lifecycleStatusJSON contains the JSON metadata for the struct [LifecycleStatus]
type lifecycleStatusJSON struct {
	LastProgressAt   apijson.Field
	LastTransitionAt apijson.Field
	Phase            apijson.Field
	Reason           apijson.Field
	Retryable        apijson.Field
	Revision         apijson.Field
	LastError        apijson.Field
	raw              string
	ExtraFields      map[string]apijson.Field
}

func (r *LifecycleStatus) UnmarshalJSON(data []byte) (err error) {
	return apijson.UnmarshalRoot(data, r)
}

func (r lifecycleStatusJSON) RawJSON() string {
	return r.raw
}

type LifecycleStatusPhase string

const (
	LifecycleStatusPhaseAccepted         LifecycleStatusPhase = "accepted"
	LifecycleStatusPhasePlacementPending LifecycleStatusPhase = "placement_pending"
	LifecycleStatusPhaseStarting         LifecycleStatusPhase = "starting"
	LifecycleStatusPhaseRunning          LifecycleStatusPhase = "running"
	LifecycleStatusPhaseStopping         LifecycleStatusPhase = "stopping"
	LifecycleStatusPhaseSleeping         LifecycleStatusPhase = "sleeping"
	LifecycleStatusPhaseDestroying       LifecycleStatusPhase = "destroying"
	LifecycleStatusPhaseDestroyed        LifecycleStatusPhase = "destroyed"
	LifecycleStatusPhaseFailed           LifecycleStatusPhase = "failed"
)

func (r LifecycleStatusPhase) IsKnown() bool {
	switch r {
	case LifecycleStatusPhaseAccepted, LifecycleStatusPhasePlacementPending, LifecycleStatusPhaseStarting, LifecycleStatusPhaseRunning, LifecycleStatusPhaseStopping, LifecycleStatusPhaseSleeping, LifecycleStatusPhaseDestroying, LifecycleStatusPhaseDestroyed, LifecycleStatusPhaseFailed:
		return true
	}
	return false
}

type CreateParamsParam struct {
	// Idle window before autosleep. Accepts fixed duration units like 30s, 30m, 2h,
	// 7d3h4s, or 1w3d, raw seconds ("1800"), or never to disable.
	Autosleep param.Field[string] `json:"autosleep"`
	// Memory in MiB.
	MemoryMib param.Field[int64] `json:"memory_mib"`
	// Storage in GiB.
	StorageGib param.Field[int64] `json:"storage_gib"`
	// CPU in vCPUs.
	Vcpu param.Field[float64] `json:"vcpu"`
}

func (r CreateParamsParam) MarshalJSON() (data []byte, err error) {
	return apijson.MarshalRoot(r)
}

type UpdateParamsParam struct {
	// Idle window before autosleep. Accepts fixed duration units like 30s, 30m, 2h,
	// 7d3h4s, or 1w3d, raw seconds ("1800"), or never to disable.
	Autosleep param.Field[string] `json:"autosleep"`
	// Memory in MiB.
	MemoryMib param.Field[int64] `json:"memory_mib"`
	// Storage in GiB.
	StorageGib param.Field[int64] `json:"storage_gib"`
	// CPU in vCPUs.
	Vcpu param.Field[float64] `json:"vcpu"`
}

func (r UpdateParamsParam) MarshalJSON() (data []byte, err error) {
	return apijson.MarshalRoot(r)
}

type MachineGetResponse struct {
	// Seconds of inactivity before autosleep. 0 disables autosleep.
	AutosleepSeconds int64                          `json:"autosleep_seconds" api:"required"`
	DesiredState     MachineGetResponseDesiredState `json:"desired_state" api:"required"`
	MachineID        string                         `json:"machine_id" api:"required"`
	// Memory in MiB.
	MemoryMib  int64           `json:"memory_mib" api:"required"`
	Status     LifecycleStatus `json:"status" api:"required"`
	StorageGib int64           `json:"storage_gib" api:"required"`
	// CPU in vCPUs.
	Vcpu float64                `json:"vcpu" api:"required"`
	JSON machineGetResponseJSON `json:"-"`
}

// machineGetResponseJSON contains the JSON metadata for the struct [MachineGetResponse]
type machineGetResponseJSON struct {
	AutosleepSeconds apijson.Field
	DesiredState     apijson.Field
	MachineID        apijson.Field
	MemoryMib        apijson.Field
	Status           apijson.Field
	StorageGib       apijson.Field
	Vcpu             apijson.Field
	raw              string
	ExtraFields      map[string]apijson.Field
}

func (r *MachineGetResponse) UnmarshalJSON(data []byte) (err error) {
	return apijson.UnmarshalRoot(data, r)
}

func (r machineGetResponseJSON) RawJSON() string {
	return r.raw
}

type MachineGetResponseDesiredState string

const (
	MachineGetResponseDesiredStateRunning   MachineGetResponseDesiredState = "running"
	MachineGetResponseDesiredStateSleeping  MachineGetResponseDesiredState = "sleeping"
	MachineGetResponseDesiredStateDestroyed MachineGetResponseDesiredState = "destroyed"
)

func (r MachineGetResponseDesiredState) IsKnown() bool {
	switch r {
	case MachineGetResponseDesiredStateRunning, MachineGetResponseDesiredStateSleeping, MachineGetResponseDesiredStateDestroyed:
		return true
	}
	return false
}

type MachineListParams struct {
	Cursor        param.Field[string] `query:"cursor"`
	Limit         param.Field[int64]  `query:"limit"`
	XDedalusOrgID param.Field[string] `header:"X-Dedalus-Org-Id"`
}

// URLQuery serializes [MachineListParams]'s query parameters as `url.Values`.
func (r MachineListParams) URLQuery() (v url.Values) {
	return apiquery.MarshalWithSettings(r, apiquery.QuerySettings{
		ArrayFormat:  apiquery.ArrayQueryFormatComma,
		NestedFormat: apiquery.NestedQueryFormatBrackets,
	})
}

type MachineNewParams struct {
	CreateParams  CreateParams        `json:"create_params" api:"required"`
	XDedalusOrgID param.Field[string] `header:"X-Dedalus-Org-Id"`
}

func (r MachineNewParams) MarshalJSON() (data []byte, err error) {
	return apijson.MarshalRoot(r.CreateParams)
}

type MachineGetParams struct {
	MachineID     string              `path:"machine_id" api:"required" json:"-"`
	XDedalusOrgID param.Field[string] `header:"X-Dedalus-Org-Id"`
}

type MachineUpdateParams struct {
	MachineID     string              `path:"machine_id" api:"required" json:"-"`
	UpdateParams  UpdateParams        `json:"update_params" api:"required"`
	XDedalusOrgID param.Field[string] `header:"X-Dedalus-Org-Id"`
}

func (r MachineUpdateParams) MarshalJSON() (data []byte, err error) {
	return apijson.MarshalRoot(r.UpdateParams)
}

type MachineDeleteParams struct {
	MachineID     string              `path:"machine_id" api:"required" json:"-"`
	XDedalusOrgID param.Field[string] `header:"X-Dedalus-Org-Id"`
}

type MachineWatchParams struct {
	// Machine identifier.
	MachineID string `path:"machine_id" api:"required" json:"-"`
	// Optional resourceVersion bookmark used to resume a previous stream.
	LastEventID param.Field[string] `header:"Last-Event-ID"`
	// Organization ID header applied to all DCS requests.
	XDedalusOrgID param.Field[string] `header:"X-Dedalus-Org-Id" format:"uuid"`
}

type MachineSleepParams struct {
	MachineID     string              `path:"machine_id" api:"required" json:"-"`
	XDedalusOrgID param.Field[string] `header:"X-Dedalus-Org-Id"`
}

type MachineWakeParams struct {
	MachineID     string              `path:"machine_id" api:"required" json:"-"`
	XDedalusOrgID param.Field[string] `header:"X-Dedalus-Org-Id"`
}
