// Code generated by Scalar SDK Generator. DO NOT EDIT.

package dedalus

import (
	"context"
	"errors"
	"fmt"
	"net/http"
	"net/url"
	"slices"
	"time"

	"github.com/dedalus-labs/dedalus-go/internal/apijson"
	"github.com/dedalus-labs/dedalus-go/internal/apiquery"
	"github.com/dedalus-labs/dedalus-go/internal/param"
	"github.com/dedalus-labs/dedalus-go/internal/requestconfig"
	"github.com/dedalus-labs/dedalus-go/option"
	"github.com/dedalus-labs/dedalus-go/packages/pagination"
)

// MachineService contains methods and other services that help with interacting
// with the API. You should not instantiate this service directly, and instead use
// the [NewMachineService] method instead.
type MachineService struct {
	Options      []option.RequestOption
	SSH          *MachineSSHService
	Executions   *MachineExecutionService
	Autoresizing *MachineAutoresizingService
}

// NewMachineService generates a new service that applies the given options to each request.
// These options are applied after the parent client's options (if there is one), and
// before any request-specific options.
func NewMachineService(opts ...option.RequestOption) (r *MachineService) {
	r = &MachineService{}
	r.Options = opts
	r.SSH = NewMachineSSHService(opts...)
	r.Executions = NewMachineExecutionService(opts...)
	r.Autoresizing = NewMachineAutoresizingService(opts...)
	return
}

// List machines
//
// Parameters:
//
//	ctx: Context for the request.
//	query: MachineListParams request parameters.
//	opts: Options to apply to this request.
//
// Returns:
//
//	*pagination.CursorPage[MachineListItem]: OK
//
// Example:
//
//	page, err := client.Machines.List(context.Background(), sdk.MachineListParams{})
//	if err != nil {
//		panic(err)
//	}
//
//	fmt.Println(page)
func (r *MachineService) List(ctx context.Context, query MachineListParams, opts ...option.RequestOption) (res *pagination.CursorPage[MachineListItem], err error) {
	var raw *http.Response
	opts = slices.Concat(r.Options, opts)
	opts = append([]option.RequestOption{option.WithResponseInto(&raw)}, opts...)
	path := "v1/machines"
	cfg, err := requestconfig.NewRequestConfig(ctx, http.MethodGet, path, query, &res, opts...)
	if err != nil {
		return nil, err
	}
	err = cfg.Execute()
	if err != nil {
		return nil, err
	}
	res.SetPageConfig(cfg, raw)
	return res, nil
}

// ListAutoPaging returns an auto-pager for List.
//
// Returns:
//
//	*pagination.CursorPageAutoPager[MachineListItem]
func (r *MachineService) ListAutoPaging(ctx context.Context, query MachineListParams, opts ...option.RequestOption) *pagination.CursorPageAutoPager[MachineListItem] {
	return pagination.NewCursorPageAutoPager(r.List(ctx, query, opts...))
}

// Create machine
//
// Parameters:
//
//	ctx: Context for the request.
//	body: MachineNewParams request parameters.
//	opts: Options to apply to this request.
//
// Returns:
//
//	*Machine: Create converged inline
//
// Example:
//
//	machine, err := client.Machines.New(context.Background(), sdk.MachineNewParams{
//		CreateParams: sdk.CreateParams{
//			Autosleep:  sdk.F[string]("300s"),
//			MemoryMib:  sdk.F[int64](4096),
//			StorageGib: sdk.F[int64](10),
//			Vcpu:       sdk.F[float64](1),
//		},
//	})
//	if err != nil {
//		panic(err)
//	}
//
//	fmt.Println(machine.MachineID)
func (r *MachineService) New(ctx context.Context, body MachineNewParams, opts ...option.RequestOption) (res *Machine, err error) {
	opts = slices.Concat(r.Options, opts)
	path := "v1/machines"
	err = requestconfig.ExecuteNewRequest(ctx, http.MethodPost, path, body, &res, opts...)
	return res, err
}

// Get machine
//
// Parameters:
//
//	ctx: Context for the request.
//	params: MachineGetParams request parameters.
//	opts: Options to apply to this request.
//
// Returns:
//
//	*MachineGetResponse: OK
//
// Example:
//
//	machine, err := client.Machines.Get(context.Background(), sdk.MachineGetParams{
//		MachineID: "017f22e2-79b0-7cc3-98c4-dc0c0c07398f",
//	})
//	if err != nil {
//		panic(err)
//	}
//
//	fmt.Println(machine.MachineID)
func (r *MachineService) Get(ctx context.Context, params MachineGetParams, opts ...option.RequestOption) (res *MachineGetResponse, err error) {
	opts = slices.Concat(r.Options, opts)
	if params.MachineID == "" {
		err = errors.New("missing required machine_id parameter")
		return nil, err
	}
	path := fmt.Sprintf("v1/machines/%s", url.PathEscape(params.MachineID))
	err = requestconfig.ExecuteNewRequest(ctx, http.MethodGet, path, nil, &res, opts...)
	return res, err
}

// Update machine
//
// Parameters:
//
//	ctx: Context for the request.
//	body: MachineUpdateParams request parameters.
//	opts: Options to apply to this request.
//
// Returns:
//
//	*Machine: OK
//
// Example:
//
//	machine, err := client.Machines.Update(context.Background(), sdk.MachineUpdateParams{
//		MachineID:    "017f22e2-79b0-7cc3-98c4-dc0c0c07398f",
//		UpdateParams: sdk.UpdateParams{},
//	})
//	if err != nil {
//		panic(err)
//	}
//
//	fmt.Println(machine.MachineID)
func (r *MachineService) Update(ctx context.Context, body MachineUpdateParams, opts ...option.RequestOption) (res *Machine, err error) {
	opts = slices.Concat(r.Options, opts)
	if body.MachineID == "" {
		err = errors.New("missing required machine_id parameter")
		return nil, err
	}
	path := fmt.Sprintf("v1/machines/%s", url.PathEscape(body.MachineID))
	err = requestconfig.ExecuteNewRequest(ctx, http.MethodPatch, path, body, &res, opts...)
	return res, err
}

// Destroy machine
//
// Parameters:
//
//	ctx: Context for the request.
//	params: MachineDeleteParams request parameters.
//	opts: Options to apply to this request.
//
// Returns:
//
//	*Machine: OK
//
// Example:
//
//	machine, err := client.Machines.Delete(context.Background(), sdk.MachineDeleteParams{
//		MachineID: "017f22e2-79b0-7cc3-98c4-dc0c0c07398f",
//	})
//	if err != nil {
//		panic(err)
//	}
//
//	fmt.Println(machine.MachineID)
func (r *MachineService) Delete(ctx context.Context, params MachineDeleteParams, opts ...option.RequestOption) (res *Machine, err error) {
	opts = slices.Concat(r.Options, opts)
	if params.MachineID == "" {
		err = errors.New("missing required machine_id parameter")
		return nil, err
	}
	path := fmt.Sprintf("v1/machines/%s", url.PathEscape(params.MachineID))
	err = requestconfig.ExecuteNewRequest(ctx, http.MethodDelete, path, nil, &res, opts...)
	return res, err
}

// Sleep a running machine
//
// Parameters:
//
//	ctx: Context for the request.
//	params: MachineSleepParams request parameters.
//	opts: Options to apply to this request.
//
// Returns:
//
//	*Machine: OK
//
// Example:
//
//	machine, err := client.Machines.Sleep(context.Background(), sdk.MachineSleepParams{
//		MachineID: "017f22e2-79b0-7cc3-98c4-dc0c0c07398f",
//	})
//	if err != nil {
//		panic(err)
//	}
//
//	fmt.Println(machine.MachineID)
func (r *MachineService) Sleep(ctx context.Context, params MachineSleepParams, opts ...option.RequestOption) (res *Machine, err error) {
	opts = slices.Concat(r.Options, opts)
	if params.MachineID == "" {
		err = errors.New("missing required machine_id parameter")
		return nil, err
	}
	path := fmt.Sprintf("v1/machines/%s/sleep", url.PathEscape(params.MachineID))
	err = requestconfig.ExecuteNewRequest(ctx, http.MethodPost, path, nil, &res, opts...)
	return res, err
}

// Wake a sleeping machine
//
// Parameters:
//
//	ctx: Context for the request.
//	params: MachineWakeParams request parameters.
//	opts: Options to apply to this request.
//
// Returns:
//
//	*Machine: OK
//
// Example:
//
//	machine, err := client.Machines.Wake(context.Background(), sdk.MachineWakeParams{
//		MachineID: "017f22e2-79b0-7cc3-98c4-dc0c0c07398f",
//	})
//	if err != nil {
//		panic(err)
//	}
//
//	fmt.Println(machine.MachineID)
func (r *MachineService) Wake(ctx context.Context, params MachineWakeParams, opts ...option.RequestOption) (res *Machine, err error) {
	opts = slices.Concat(r.Options, opts)
	if params.MachineID == "" {
		err = errors.New("missing required machine_id parameter")
		return nil, err
	}
	path := fmt.Sprintf("v1/machines/%s/wake", url.PathEscape(params.MachineID))
	err = requestconfig.ExecuteNewRequest(ctx, http.MethodPost, path, nil, &res, opts...)
	return res, err
}

// Checkpoints files and replaces the runtime. The machine ID and filesystem are preserved. RAM, processes, and temporary mounts are cleared. Poll the machine until its phase is running. Retry the same Idempotency-Key after a lost response.
//
// Parameters:
//
//	ctx: Context for the request.
//	body: MachineRebootParams request parameters.
//	opts: Options to apply to this request.
//
// Returns:
//
//	*Machine: OK
//
// Example:
//
//	machine, err := client.Machines.Reboot(context.Background(), sdk.MachineRebootParams{
//		MachineID: "017f22e2-79b0-7cc3-98c4-dc0c0c07398f",
//	})
//	if err != nil {
//		panic(err)
//	}
//
//	fmt.Println(machine)
func (r *MachineService) Reboot(ctx context.Context, body MachineRebootParams, opts ...option.RequestOption) (res *Machine, err error) {
	opts = slices.Concat(r.Options, opts)
	if body.MachineID == "" {
		err = errors.New("missing required machine_id parameter")
		return nil, err
	}
	path := fmt.Sprintf("v1/machines/%s/reboot", url.PathEscape(body.MachineID))
	err = requestconfig.ExecuteNewRequest(ctx, http.MethodPost, path, body, &res, opts...)
	return res, err
}

type Machine struct {
	// Seconds of inactivity before autosleep. 0 disables autosleep.
	AutosleepSeconds int64               `json:"autosleep_seconds" api:"required"`
	DesiredState     MachineDesiredState `json:"desired_state" api:"required"`
	MachineID        string              `json:"machine_id" api:"required" format:"uuid"`
	// Memory in MiB.
	MemoryMib  int64        `json:"memory_mib" api:"required"`
	Phase      MachinePhase `json:"phase" api:"required"`
	StorageGib int64        `json:"storage_gib" api:"required"`
	// CPU in vCPUs.
	Vcpu float64     `json:"vcpu" api:"required"`
	JSON machineJSON `json:"-"`
}

// machineJSON contains the JSON metadata for the struct [Machine]
type machineJSON struct {
	AutosleepSeconds apijson.Field
	DesiredState     apijson.Field
	MachineID        apijson.Field
	MemoryMib        apijson.Field
	Phase            apijson.Field
	StorageGib       apijson.Field
	Vcpu             apijson.Field
	raw              string
	ExtraFields      map[string]apijson.Field
}

func (r *Machine) UnmarshalJSON(data []byte) (err error) {
	return apijson.UnmarshalRoot(data, r)
}

func (r machineJSON) RawJSON() string {
	return r.raw
}

type MachineDesiredState string

const (
	MachineDesiredStateRunning   MachineDesiredState = "running"
	MachineDesiredStateSleeping  MachineDesiredState = "sleeping"
	MachineDesiredStateDestroyed MachineDesiredState = "destroyed"
)

func (r MachineDesiredState) IsKnown() bool {
	switch r {
	case MachineDesiredStateRunning, MachineDesiredStateSleeping, MachineDesiredStateDestroyed:
		return true
	}
	return false
}

type MachinePhase string

const (
	MachinePhaseAccepted         MachinePhase = "accepted"
	MachinePhasePlacementPending MachinePhase = "placement_pending"
	MachinePhaseStarting         MachinePhase = "starting"
	MachinePhaseRunning          MachinePhase = "running"
	MachinePhaseStopping         MachinePhase = "stopping"
	MachinePhaseSleeping         MachinePhase = "sleeping"
	MachinePhaseDestroying       MachinePhase = "destroying"
	MachinePhaseDestroyed        MachinePhase = "destroyed"
	MachinePhaseFailed           MachinePhase = "failed"
)

func (r MachinePhase) IsKnown() bool {
	switch r {
	case MachinePhaseAccepted, MachinePhasePlacementPending, MachinePhaseStarting, MachinePhaseRunning, MachinePhaseStopping, MachinePhaseSleeping, MachinePhaseDestroying, MachinePhaseDestroyed, MachinePhaseFailed:
		return true
	}
	return false
}

type MachineList struct {
	Items      []MachineListItem `json:"items" api:"required,nullable"`
	NextCursor string            `json:"next_cursor"`
	JSON       machineListJSON   `json:"-"`
}

// machineListJSON contains the JSON metadata for the struct [MachineList]
type machineListJSON struct {
	Items       apijson.Field
	NextCursor  apijson.Field
	raw         string
	ExtraFields map[string]apijson.Field
}

func (r *MachineList) UnmarshalJSON(data []byte) (err error) {
	return apijson.UnmarshalRoot(data, r)
}

func (r machineListJSON) RawJSON() string {
	return r.raw
}

type MachineListItem struct {
	// Seconds of inactivity before autosleep. 0 disables autosleep.
	AutosleepSeconds int64                       `json:"autosleep_seconds" api:"required"`
	CreatedAt        time.Time                   `json:"created_at" api:"required" format:"date-time"`
	DesiredState     MachineListItemDesiredState `json:"desired_state" api:"required"`
	MachineID        string                      `json:"machine_id" api:"required" format:"uuid"`
	// Memory in MiB.
	MemoryMib  int64                `json:"memory_mib" api:"required"`
	Phase      MachineListItemPhase `json:"phase" api:"required"`
	StorageGib int64                `json:"storage_gib" api:"required"`
	// CPU in vCPUs.
	Vcpu float64             `json:"vcpu" api:"required"`
	JSON machineListItemJSON `json:"-"`
}

// machineListItemJSON contains the JSON metadata for the struct [MachineListItem]
type machineListItemJSON struct {
	AutosleepSeconds apijson.Field
	CreatedAt        apijson.Field
	DesiredState     apijson.Field
	MachineID        apijson.Field
	MemoryMib        apijson.Field
	Phase            apijson.Field
	StorageGib       apijson.Field
	Vcpu             apijson.Field
	raw              string
	ExtraFields      map[string]apijson.Field
}

func (r *MachineListItem) UnmarshalJSON(data []byte) (err error) {
	return apijson.UnmarshalRoot(data, r)
}

func (r machineListItemJSON) RawJSON() string {
	return r.raw
}

type MachineListItemDesiredState string

const (
	MachineListItemDesiredStateRunning   MachineListItemDesiredState = "running"
	MachineListItemDesiredStateSleeping  MachineListItemDesiredState = "sleeping"
	MachineListItemDesiredStateDestroyed MachineListItemDesiredState = "destroyed"
)

func (r MachineListItemDesiredState) IsKnown() bool {
	switch r {
	case MachineListItemDesiredStateRunning, MachineListItemDesiredStateSleeping, MachineListItemDesiredStateDestroyed:
		return true
	}
	return false
}

type MachineListItemPhase string

const (
	MachineListItemPhaseAccepted         MachineListItemPhase = "accepted"
	MachineListItemPhasePlacementPending MachineListItemPhase = "placement_pending"
	MachineListItemPhaseStarting         MachineListItemPhase = "starting"
	MachineListItemPhaseRunning          MachineListItemPhase = "running"
	MachineListItemPhaseStopping         MachineListItemPhase = "stopping"
	MachineListItemPhaseSleeping         MachineListItemPhase = "sleeping"
	MachineListItemPhaseDestroying       MachineListItemPhase = "destroying"
	MachineListItemPhaseDestroyed        MachineListItemPhase = "destroyed"
	MachineListItemPhaseFailed           MachineListItemPhase = "failed"
)

func (r MachineListItemPhase) IsKnown() bool {
	switch r {
	case MachineListItemPhaseAccepted, MachineListItemPhasePlacementPending, MachineListItemPhaseStarting, MachineListItemPhaseRunning, MachineListItemPhaseStopping, MachineListItemPhaseSleeping, MachineListItemPhaseDestroying, MachineListItemPhaseDestroyed, MachineListItemPhaseFailed:
		return true
	}
	return false
}

type CreateParams struct {
	// Idle window before autosleep. Accepts fixed duration units like 30s, 30m, 2h,
	// 7d3h4s, or 1w3d, raw seconds ("1800"), or never to disable.
	Autosleep param.Field[string] `json:"autosleep"`
	// Memory in MiB.
	MemoryMib param.Field[int64] `json:"memory_mib"`
	// Storage in GiB.
	StorageGib param.Field[int64] `json:"storage_gib"`
	// CPU in vCPUs.
	Vcpu param.Field[float64] `json:"vcpu"`
}

func (r CreateParams) MarshalJSON() (data []byte, err error) {
	return apijson.MarshalRoot(r)
}

type UpdateParams struct {
	// Idle window before autosleep. Accepts fixed duration units like 30s, 30m, 2h,
	// 7d3h4s, or 1w3d, raw seconds ("1800"), or never to disable.
	Autosleep param.Field[string] `json:"autosleep"`
	// Memory in MiB.
	MemoryMib param.Field[int64] `json:"memory_mib"`
	// Storage in GiB.
	StorageGib param.Field[int64] `json:"storage_gib"`
	// CPU in vCPUs.
	Vcpu param.Field[float64] `json:"vcpu"`
}

func (r UpdateParams) MarshalJSON() (data []byte, err error) {
	return apijson.MarshalRoot(r)
}

type LifecycleStatus struct {
	LastProgressAt   time.Time `json:"last_progress_at" api:"required" format:"date-time"`
	LastTransitionAt time.Time `json:"last_transition_at" api:"required" format:"date-time"`
	// Accepted RAM maximum, including completed automatic increases.
	MemoryConfiguredMib int64                `json:"memory_configured_mib" api:"required"`
	Phase               LifecycleStatusPhase `json:"phase" api:"required"`
	Reason              string               `json:"reason" api:"required"`
	Retryable           bool                 `json:"retryable" api:"required"`
	Revision            string               `json:"revision" api:"required"`
	LastError           string               `json:"last_error"`
	// Last confirmed RAM allocation for the current running generation. Absent when
	// the allocation is unknown or no longer current.
	MemoryAssignedMib int64 `json:"memory_assigned_mib"`
	// Time of the latest confirmed automatic RAM increase. Does not include explicit
	// resizing or a complete change history.
	MemoryLastAutoresizedAt time.Time `json:"memory_last_autoresized_at" format:"date-time"`
	// Resize progress reported by the current runtime. A pending automatic target may
	// not yet be applied by that runtime.
	MemoryResizeState LifecycleStatusMemoryResizeState `json:"memory_resize_state"`
	// Pending automatic RAM target, or the current runtime target when no automatic
	// target is pending.
	MemoryTargetMib int64               `json:"memory_target_mib"`
	JSON            lifecycleStatusJSON `json:"-"`
}

// lifecycleStatusJSON contains the JSON metadata for the struct [LifecycleStatus]
type lifecycleStatusJSON struct {
	LastProgressAt          apijson.Field
	LastTransitionAt        apijson.Field
	MemoryConfiguredMib     apijson.Field
	Phase                   apijson.Field
	Reason                  apijson.Field
	Retryable               apijson.Field
	Revision                apijson.Field
	LastError               apijson.Field
	MemoryAssignedMib       apijson.Field
	MemoryLastAutoresizedAt apijson.Field
	MemoryResizeState       apijson.Field
	MemoryTargetMib         apijson.Field
	raw                     string
	ExtraFields             map[string]apijson.Field
}

func (r *LifecycleStatus) UnmarshalJSON(data []byte) (err error) {
	return apijson.UnmarshalRoot(data, r)
}

func (r lifecycleStatusJSON) RawJSON() string {
	return r.raw
}

type LifecycleStatusMemoryResizeState string

const (
	LifecycleStatusMemoryResizeStateStable          LifecycleStatusMemoryResizeState = "stable"
	LifecycleStatusMemoryResizeStateError           LifecycleStatusMemoryResizeState = "error"
	LifecycleStatusMemoryResizeStatePendingCapacity LifecycleStatusMemoryResizeState = "pending_capacity"
)

func (r LifecycleStatusMemoryResizeState) IsKnown() bool {
	switch r {
	case LifecycleStatusMemoryResizeStateStable, LifecycleStatusMemoryResizeStateError, LifecycleStatusMemoryResizeStatePendingCapacity:
		return true
	}
	return false
}

type LifecycleStatusPhase string

const (
	LifecycleStatusPhaseAccepted         LifecycleStatusPhase = "accepted"
	LifecycleStatusPhasePlacementPending LifecycleStatusPhase = "placement_pending"
	LifecycleStatusPhaseStarting         LifecycleStatusPhase = "starting"
	LifecycleStatusPhaseRunning          LifecycleStatusPhase = "running"
	LifecycleStatusPhaseStopping         LifecycleStatusPhase = "stopping"
	LifecycleStatusPhaseSleeping         LifecycleStatusPhase = "sleeping"
	LifecycleStatusPhaseDestroying       LifecycleStatusPhase = "destroying"
	LifecycleStatusPhaseDestroyed        LifecycleStatusPhase = "destroyed"
	LifecycleStatusPhaseFailed           LifecycleStatusPhase = "failed"
)

func (r LifecycleStatusPhase) IsKnown() bool {
	switch r {
	case LifecycleStatusPhaseAccepted, LifecycleStatusPhasePlacementPending, LifecycleStatusPhaseStarting, LifecycleStatusPhaseRunning, LifecycleStatusPhaseStopping, LifecycleStatusPhaseSleeping, LifecycleStatusPhaseDestroying, LifecycleStatusPhaseDestroyed, LifecycleStatusPhaseFailed:
		return true
	}
	return false
}

type CreateParamsParam struct {
	// Idle window before autosleep. Accepts fixed duration units like 30s, 30m, 2h,
	// 7d3h4s, or 1w3d, raw seconds ("1800"), or never to disable.
	Autosleep param.Field[string] `json:"autosleep"`
	// Memory in MiB.
	MemoryMib param.Field[int64] `json:"memory_mib"`
	// Storage in GiB.
	StorageGib param.Field[int64] `json:"storage_gib"`
	// CPU in vCPUs.
	Vcpu param.Field[float64] `json:"vcpu"`
}

func (r CreateParamsParam) MarshalJSON() (data []byte, err error) {
	return apijson.MarshalRoot(r)
}

type UpdateParamsParam struct {
	// Idle window before autosleep. Accepts fixed duration units like 30s, 30m, 2h,
	// 7d3h4s, or 1w3d, raw seconds ("1800"), or never to disable.
	Autosleep param.Field[string] `json:"autosleep"`
	// Memory in MiB.
	MemoryMib param.Field[int64] `json:"memory_mib"`
	// Storage in GiB.
	StorageGib param.Field[int64] `json:"storage_gib"`
	// CPU in vCPUs.
	Vcpu param.Field[float64] `json:"vcpu"`
}

func (r UpdateParamsParam) MarshalJSON() (data []byte, err error) {
	return apijson.MarshalRoot(r)
}

type MachineGetResponse struct {
	// Seconds of inactivity before autosleep. 0 disables autosleep.
	AutosleepSeconds int64                          `json:"autosleep_seconds" api:"required"`
	DesiredState     MachineGetResponseDesiredState `json:"desired_state" api:"required"`
	MachineID        string                         `json:"machine_id" api:"required" format:"uuid"`
	// Memory in MiB.
	MemoryMib  int64           `json:"memory_mib" api:"required"`
	Status     LifecycleStatus `json:"status" api:"required"`
	StorageGib int64           `json:"storage_gib" api:"required"`
	// CPU in vCPUs.
	Vcpu float64                `json:"vcpu" api:"required"`
	JSON machineGetResponseJSON `json:"-"`
}

// machineGetResponseJSON contains the JSON metadata for the struct [MachineGetResponse]
type machineGetResponseJSON struct {
	AutosleepSeconds apijson.Field
	DesiredState     apijson.Field
	MachineID        apijson.Field
	MemoryMib        apijson.Field
	Status           apijson.Field
	StorageGib       apijson.Field
	Vcpu             apijson.Field
	raw              string
	ExtraFields      map[string]apijson.Field
}

func (r *MachineGetResponse) UnmarshalJSON(data []byte) (err error) {
	return apijson.UnmarshalRoot(data, r)
}

func (r machineGetResponseJSON) RawJSON() string {
	return r.raw
}

type MachineGetResponseDesiredState string

const (
	MachineGetResponseDesiredStateRunning   MachineGetResponseDesiredState = "running"
	MachineGetResponseDesiredStateSleeping  MachineGetResponseDesiredState = "sleeping"
	MachineGetResponseDesiredStateDestroyed MachineGetResponseDesiredState = "destroyed"
)

func (r MachineGetResponseDesiredState) IsKnown() bool {
	switch r {
	case MachineGetResponseDesiredStateRunning, MachineGetResponseDesiredStateSleeping, MachineGetResponseDesiredStateDestroyed:
		return true
	}
	return false
}

type MachineListParams struct {
	Cursor param.Field[string] `query:"cursor"`
	Limit  param.Field[int64]  `query:"limit"`
}

// URLQuery serializes [MachineListParams]'s query parameters as `url.Values`.
func (r MachineListParams) URLQuery() (v url.Values) {
	return apiquery.MarshalWithSettings(r, apiquery.QuerySettings{
		ArrayFormat:  apiquery.ArrayQueryFormatComma,
		NestedFormat: apiquery.NestedQueryFormatBrackets,
	})
}

type MachineNewParams struct {
	CreateParams CreateParams `json:"create_params" api:"required"`
}

func (r MachineNewParams) MarshalJSON() (data []byte, err error) {
	return apijson.MarshalRoot(r.CreateParams)
}

type MachineGetParams struct {
	// Bare, lowercase, hyphenated Machine UUID. Pass the returned machine_id
	// unchanged.
	MachineID string `path:"machine_id" api:"required" json:"-"`
}

type MachineUpdateParams struct {
	// Bare, lowercase, hyphenated Machine UUID. Pass the returned machine_id
	// unchanged.
	MachineID    string       `path:"machine_id" api:"required" json:"-"`
	UpdateParams UpdateParams `json:"update_params" api:"required"`
}

func (r MachineUpdateParams) MarshalJSON() (data []byte, err error) {
	return apijson.MarshalRoot(r.UpdateParams)
}

type MachineDeleteParams struct {
	// Bare, lowercase, hyphenated Machine UUID. Pass the returned machine_id
	// unchanged.
	MachineID string `path:"machine_id" api:"required" json:"-"`
}

type MachineSleepParams struct {
	// Bare, lowercase, hyphenated Machine UUID. Pass the returned machine_id
	// unchanged.
	MachineID string `path:"machine_id" api:"required" json:"-"`
}

type MachineWakeParams struct {
	// Bare, lowercase, hyphenated Machine UUID. Pass the returned machine_id
	// unchanged.
	MachineID string `path:"machine_id" api:"required" json:"-"`
}

type MachineRebootParams struct {
	// Bare, lowercase, hyphenated Machine UUID. Pass the returned machine_id
	// unchanged.
	MachineID string `path:"machine_id" api:"required" json:"-"`
	// Recover from the last committed filesystem checkpoint without guest cooperation.
	// Unpublished file writes are lost. The default checkpoints files before
	// rebooting.
	Force param.Field[bool] `query:"force"`
}

// URLQuery serializes [MachineRebootParams]'s query parameters as `url.Values`.
func (r MachineRebootParams) URLQuery() (v url.Values) {
	return apiquery.MarshalWithSettings(r, apiquery.QuerySettings{
		ArrayFormat:  apiquery.ArrayQueryFormatComma,
		NestedFormat: apiquery.NestedQueryFormatBrackets,
	})
}
