// Code generated by Scalar SDK Generator. DO NOT EDIT.

package dedalus

import (
	"context"
	"errors"
	"fmt"
	"net/http"
	"net/url"
	"slices"

	"github.com/dedalus-labs/dedalus-go/internal/apijson"
	"github.com/dedalus-labs/dedalus-go/internal/param"
	"github.com/dedalus-labs/dedalus-go/internal/requestconfig"
	"github.com/dedalus-labs/dedalus-go/option"
)

// MachineAutoresizingService contains methods and other services that help with interacting
// with the API. You should not instantiate this service directly, and instead use
// the [NewMachineAutoresizingService] method instead.
type MachineAutoresizingService struct {
	Options []option.RequestOption
}

// NewMachineAutoresizingService generates a new service that applies the given options to each request.
// These options are applied after the parent client's options (if there is one), and
// before any request-specific options.
func NewMachineAutoresizingService(opts ...option.RequestOption) (r *MachineAutoresizingService) {
	r = &MachineAutoresizingService{}
	r.Options = opts
	return
}

// Read this machine's RAM autoresizing settings
//
// Parameters:
//
//	ctx: Context for the request.
//	params: MachineAutoresizingGetParams request parameters.
//	opts: Options to apply to this request.
//
// Returns:
//
//	*Settings: OK
//
// Example:
//
//	autoresizing, err := client.Machines.Autoresizing.Get(context.Background(), sdk.MachineAutoresizingGetParams{
//		MachineID: "017f22e2-79b0-7cc3-98c4-dc0c0c07398f",
//	})
//	if err != nil {
//		panic(err)
//	}
//
//	fmt.Println(autoresizing)
func (r *MachineAutoresizingService) Get(ctx context.Context, params MachineAutoresizingGetParams, opts ...option.RequestOption) (res *Settings, err error) {
	opts = slices.Concat(r.Options, opts)
	if params.MachineID == "" {
		err = errors.New("missing required machine_id parameter")
		return nil, err
	}
	path := fmt.Sprintf("v1/machines/%s/autoresizing", url.PathEscape(params.MachineID))
	err = requestconfig.ExecuteNewRequest(ctx, http.MethodGet, path, nil, &res, opts...)
	return res, err
}

// Set this machine's RAM autoresizing settings
//
// Parameters:
//
//	ctx: Context for the request.
//	body: MachineAutoresizingUpdateParams request parameters.
//	opts: Options to apply to this request.
//
// Returns:
//
//	*Settings: OK
//
// Example:
//
//	autoresizing, err := client.Machines.Autoresizing.Update(context.Background(), sdk.MachineAutoresizingUpdateParams{
//		MachineID: "017f22e2-79b0-7cc3-98c4-dc0c0c07398f",
//		Settings: sdk.SettingsParam{
//			Enabled: sdk.F[bool](false),
//		},
//	})
//	if err != nil {
//		panic(err)
//	}
//
//	fmt.Println(autoresizing)
func (r *MachineAutoresizingService) Update(ctx context.Context, body MachineAutoresizingUpdateParams, opts ...option.RequestOption) (res *Settings, err error) {
	opts = slices.Concat(r.Options, opts)
	if body.MachineID == "" {
		err = errors.New("missing required machine_id parameter")
		return nil, err
	}
	path := fmt.Sprintf("v1/machines/%s/autoresizing", url.PathEscape(body.MachineID))
	err = requestconfig.ExecuteNewRequest(ctx, http.MethodPut, path, body, &res, opts...)
	return res, err
}

type Settings struct {
	Enabled bool         `json:"enabled" api:"required"`
	JSON    settingsJSON `json:"-"`
}

// settingsJSON contains the JSON metadata for the struct [Settings]
type settingsJSON struct {
	Enabled     apijson.Field
	raw         string
	ExtraFields map[string]apijson.Field
}

func (r *Settings) UnmarshalJSON(data []byte) (err error) {
	return apijson.UnmarshalRoot(data, r)
}

func (r settingsJSON) RawJSON() string {
	return r.raw
}

type SettingsParam struct {
	Enabled param.Field[bool] `json:"enabled" api:"required"`
}

func (r SettingsParam) MarshalJSON() (data []byte, err error) {
	return apijson.MarshalRoot(r)
}

type MachineAutoresizingGetParams struct {
	// Bare, lowercase, hyphenated Machine UUID. Pass the returned machine_id
	// unchanged.
	MachineID string `path:"machine_id" api:"required" json:"-"`
}

type MachineAutoresizingUpdateParams struct {
	// Bare, lowercase, hyphenated Machine UUID. Pass the returned machine_id
	// unchanged.
	MachineID string        `path:"machine_id" api:"required" json:"-"`
	Settings  SettingsParam `json:"settings" api:"required"`
}

func (r MachineAutoresizingUpdateParams) MarshalJSON() (data []byte, err error) {
	return apijson.MarshalRoot(r.Settings)
}
