// Code generated by Scalar SDK Generator. DO NOT EDIT.

package dedalus

import (
	"context"
	"errors"
	"fmt"
	"net/http"
	"net/url"
	"slices"
	"time"

	"github.com/dedalus-labs/dedalus-go/internal/apijson"
	"github.com/dedalus-labs/dedalus-go/internal/apiquery"
	"github.com/dedalus-labs/dedalus-go/internal/param"
	"github.com/dedalus-labs/dedalus-go/internal/requestconfig"
	"github.com/dedalus-labs/dedalus-go/option"
	"github.com/dedalus-labs/dedalus-go/packages/pagination"
)

// MachineExecutionService contains methods and other services that help with interacting
// with the API. You should not instantiate this service directly, and instead use
// the [NewMachineExecutionService] method instead.
type MachineExecutionService struct {
	Options []option.RequestOption
	Logs    *MachineExecutionLogService
}

// NewMachineExecutionService generates a new service that applies the given options to each request.
// These options are applied after the parent client's options (if there is one), and
// before any request-specific options.
func NewMachineExecutionService(opts ...option.RequestOption) (r *MachineExecutionService) {
	r = &MachineExecutionService{}
	r.Options = opts
	r.Logs = NewMachineExecutionLogService(opts...)
	return
}

// List executions
//
// Parameters:
//
//	ctx: Context for the request.
//	query: MachineExecutionListParams request parameters.
//	opts: Options to apply to this request.
//
// Returns:
//
//	*pagination.CursorPage[Execution]: OK
//
// Example:
//
//	page, err := client.Machines.Executions.List(context.Background(), sdk.MachineExecutionListParams{
//		MachineID: "017f22e2-79b0-7cc3-98c4-dc0c0c07398f",
//	})
//	if err != nil {
//		panic(err)
//	}
//
//	fmt.Println(page)
func (r *MachineExecutionService) List(ctx context.Context, query MachineExecutionListParams, opts ...option.RequestOption) (res *pagination.CursorPage[Execution], err error) {
	var raw *http.Response
	opts = slices.Concat(r.Options, opts)
	opts = append([]option.RequestOption{option.WithResponseInto(&raw)}, opts...)
	if query.MachineID == "" {
		err = errors.New("missing required machine_id parameter")
		return nil, err
	}
	path := fmt.Sprintf("v1/machines/%s/executions", url.PathEscape(query.MachineID))
	cfg, err := requestconfig.NewRequestConfig(ctx, http.MethodGet, path, query, &res, opts...)
	if err != nil {
		return nil, err
	}
	err = cfg.Execute()
	if err != nil {
		return nil, err
	}
	res.SetPageConfig(cfg, raw)
	return res, nil
}

// ListAutoPaging returns an auto-pager for List.
//
// Returns:
//
//	*pagination.CursorPageAutoPager[Execution]
func (r *MachineExecutionService) ListAutoPaging(ctx context.Context, query MachineExecutionListParams, opts ...option.RequestOption) *pagination.CursorPageAutoPager[Execution] {
	return pagination.NewCursorPageAutoPager(r.List(ctx, query, opts...))
}

// Create execution
//
// Parameters:
//
//	ctx: Context for the request.
//	body: MachineExecutionNewParams request parameters.
//	opts: Options to apply to this request.
//
// Returns:
//
//	*Execution: OK
//
// Example:
//
//	execution, err := client.Machines.Executions.New(context.Background(), sdk.MachineExecutionNewParams{
//		MachineID: "017f22e2-79b0-7cc3-98c4-dc0c0c07398f",
//		ExecutionCreateParams: sdk.ExecutionCreateParams{
//			Command: sdk.F[[]string]([]string{""}),
//		},
//	})
//	if err != nil {
//		panic(err)
//	}
//
//	fmt.Println(execution.ExecutionID)
func (r *MachineExecutionService) New(ctx context.Context, body MachineExecutionNewParams, opts ...option.RequestOption) (res *Execution, err error) {
	opts = slices.Concat(r.Options, opts)
	if body.MachineID == "" {
		err = errors.New("missing required machine_id parameter")
		return nil, err
	}
	path := fmt.Sprintf("v1/machines/%s/executions", url.PathEscape(body.MachineID))
	err = requestconfig.ExecuteNewRequest(ctx, http.MethodPost, path, body, &res, opts...)
	return res, err
}

// Get execution
//
// Parameters:
//
//	ctx: Context for the request.
//	params: MachineExecutionGetParams request parameters.
//	opts: Options to apply to this request.
//
// Returns:
//
//	*Execution: OK
//
// Example:
//
//	execution, err := client.Machines.Executions.Get(context.Background(), sdk.MachineExecutionGetParams{
//		ExecutionID: "executionID",
//		MachineID:   "017f22e2-79b0-7cc3-98c4-dc0c0c07398f",
//	})
//	if err != nil {
//		panic(err)
//	}
//
//	fmt.Println(execution.ExecutionID)
func (r *MachineExecutionService) Get(ctx context.Context, params MachineExecutionGetParams, opts ...option.RequestOption) (res *Execution, err error) {
	opts = slices.Concat(r.Options, opts)
	if params.ExecutionID == "" {
		err = errors.New("missing required execution_id parameter")
		return nil, err
	}
	if params.MachineID == "" {
		err = errors.New("missing required machine_id parameter")
		return nil, err
	}
	path := fmt.Sprintf("v1/machines/%s/executions/%s", url.PathEscape(params.MachineID), url.PathEscape(params.ExecutionID))
	err = requestconfig.ExecuteNewRequest(ctx, http.MethodGet, path, nil, &res, opts...)
	return res, err
}

// Delete execution
//
// Parameters:
//
//	ctx: Context for the request.
//	params: MachineExecutionDeleteParams request parameters.
//	opts: Options to apply to this request.
//
// Returns:
//
//	*Execution: OK
//
// Example:
//
//	execution, err := client.Machines.Executions.Delete(context.Background(), sdk.MachineExecutionDeleteParams{
//		ExecutionID: "executionID",
//		MachineID:   "017f22e2-79b0-7cc3-98c4-dc0c0c07398f",
//	})
//	if err != nil {
//		panic(err)
//	}
//
//	fmt.Println(execution.ExecutionID)
func (r *MachineExecutionService) Delete(ctx context.Context, params MachineExecutionDeleteParams, opts ...option.RequestOption) (res *Execution, err error) {
	opts = slices.Concat(r.Options, opts)
	if params.ExecutionID == "" {
		err = errors.New("missing required execution_id parameter")
		return nil, err
	}
	if params.MachineID == "" {
		err = errors.New("missing required machine_id parameter")
		return nil, err
	}
	path := fmt.Sprintf("v1/machines/%s/executions/%s", url.PathEscape(params.MachineID), url.PathEscape(params.ExecutionID))
	err = requestconfig.ExecuteNewRequest(ctx, http.MethodDelete, path, nil, &res, opts...)
	return res, err
}

// Get execution output
//
// Parameters:
//
//	ctx: Context for the request.
//	params: MachineExecutionOutputParams request parameters.
//	opts: Options to apply to this request.
//
// Returns:
//
//	*ExecutionOutput: OK
//
// Example:
//
//	execution, err := client.Machines.Executions.Output(context.Background(), sdk.MachineExecutionOutputParams{
//		ExecutionID: "executionID",
//		MachineID:   "017f22e2-79b0-7cc3-98c4-dc0c0c07398f",
//	})
//	if err != nil {
//		panic(err)
//	}
//
//	fmt.Println(execution.ExecutionID)
func (r *MachineExecutionService) Output(ctx context.Context, params MachineExecutionOutputParams, opts ...option.RequestOption) (res *ExecutionOutput, err error) {
	opts = slices.Concat(r.Options, opts)
	if params.ExecutionID == "" {
		err = errors.New("missing required execution_id parameter")
		return nil, err
	}
	if params.MachineID == "" {
		err = errors.New("missing required machine_id parameter")
		return nil, err
	}
	path := fmt.Sprintf("v1/machines/%s/executions/%s/output", url.PathEscape(params.MachineID), url.PathEscape(params.ExecutionID))
	err = requestconfig.ExecuteNewRequest(ctx, http.MethodGet, path, nil, &res, opts...)
	return res, err
}

// List execution events
//
// Parameters:
//
//	ctx: Context for the request.
//	query: MachineExecutionEventsParams request parameters.
//	opts: Options to apply to this request.
//
// Returns:
//
//	*pagination.CursorPage[ExecutionEvent]: OK
//
// Example:
//
//	page, err := client.Machines.Executions.Events(context.Background(), sdk.MachineExecutionEventsParams{
//		ExecutionID: "executionID",
//		MachineID:   "017f22e2-79b0-7cc3-98c4-dc0c0c07398f",
//	})
//	if err != nil {
//		panic(err)
//	}
//
//	fmt.Println(page)
func (r *MachineExecutionService) Events(ctx context.Context, query MachineExecutionEventsParams, opts ...option.RequestOption) (res *pagination.CursorPage[ExecutionEvent], err error) {
	var raw *http.Response
	opts = slices.Concat(r.Options, opts)
	opts = append([]option.RequestOption{option.WithResponseInto(&raw)}, opts...)
	if query.ExecutionID == "" {
		err = errors.New("missing required execution_id parameter")
		return nil, err
	}
	if query.MachineID == "" {
		err = errors.New("missing required machine_id parameter")
		return nil, err
	}
	path := fmt.Sprintf("v1/machines/%s/executions/%s/events", url.PathEscape(query.MachineID), url.PathEscape(query.ExecutionID))
	cfg, err := requestconfig.NewRequestConfig(ctx, http.MethodGet, path, query, &res, opts...)
	if err != nil {
		return nil, err
	}
	err = cfg.Execute()
	if err != nil {
		return nil, err
	}
	res.SetPageConfig(cfg, raw)
	return res, nil
}

// EventsAutoPaging returns an auto-pager for Events.
//
// Returns:
//
//	*pagination.CursorPageAutoPager[ExecutionEvent]
func (r *MachineExecutionService) EventsAutoPaging(ctx context.Context, query MachineExecutionEventsParams, opts ...option.RequestOption) *pagination.CursorPageAutoPager[ExecutionEvent] {
	return pagination.NewCursorPageAutoPager(r.Events(ctx, query, opts...))
}

type ExecutionCreateParams struct {
	Command   param.Field[[]string]          `json:"command" api:"required"`
	Cwd       param.Field[string]            `json:"cwd"`
	Env       param.Field[map[string]string] `json:"env"`
	Stdin     param.Field[string]            `json:"stdin"`
	TimeoutMs param.Field[int64]             `json:"timeout_ms"`
}

func (r ExecutionCreateParams) MarshalJSON() (data []byte, err error) {
	return apijson.MarshalRoot(r)
}

type Execution struct {
	Command           []string            `json:"command" api:"required,nullable"`
	CreatedAt         time.Time           `json:"created_at" api:"required" format:"date-time"`
	ExecutionID       string              `json:"execution_id" api:"required"`
	LogCapture        ExecutionLogCapture `json:"log_capture" api:"required"`
	MachineID         string              `json:"machine_id" api:"required" format:"uuid"`
	Status            ExecutionStatus     `json:"status" api:"required"`
	Artifacts         []ArtifactRef       `json:"artifacts" api:"nullable"`
	CompletedAt       time.Time           `json:"completed_at" format:"date-time"`
	CreationRequestID string              `json:"creation_request_id"`
	CreationTraceID   string              `json:"creation_trace_id"`
	Cwd               string              `json:"cwd"`
	EnvKeys           []string            `json:"env_keys" api:"nullable"`
	ErrorCode         string              `json:"error_code"`
	ErrorMessage      string              `json:"error_message"`
	ExitCode          int64               `json:"exit_code"`
	ExpiresAt         time.Time           `json:"expires_at" format:"date-time"`
	RetryAfterMs      int64               `json:"retry_after_ms"`
	Signal            int64               `json:"signal"`
	StartedAt         time.Time           `json:"started_at" format:"date-time"`
	StderrBytes       int64               `json:"stderr_bytes"`
	StderrTruncated   bool                `json:"stderr_truncated"`
	StdoutBytes       int64               `json:"stdout_bytes"`
	StdoutTruncated   bool                `json:"stdout_truncated"`
	JSON              executionJSON       `json:"-"`
}

// executionJSON contains the JSON metadata for the struct [Execution]
type executionJSON struct {
	Command           apijson.Field
	CreatedAt         apijson.Field
	ExecutionID       apijson.Field
	LogCapture        apijson.Field
	MachineID         apijson.Field
	Status            apijson.Field
	Artifacts         apijson.Field
	CompletedAt       apijson.Field
	CreationRequestID apijson.Field
	CreationTraceID   apijson.Field
	Cwd               apijson.Field
	EnvKeys           apijson.Field
	ErrorCode         apijson.Field
	ErrorMessage      apijson.Field
	ExitCode          apijson.Field
	ExpiresAt         apijson.Field
	RetryAfterMs      apijson.Field
	Signal            apijson.Field
	StartedAt         apijson.Field
	StderrBytes       apijson.Field
	StderrTruncated   apijson.Field
	StdoutBytes       apijson.Field
	StdoutTruncated   apijson.Field
	raw               string
	ExtraFields       map[string]apijson.Field
}

func (r *Execution) UnmarshalJSON(data []byte) (err error) {
	return apijson.UnmarshalRoot(data, r)
}

func (r executionJSON) RawJSON() string {
	return r.raw
}

type ExecutionStatus string

const (
	ExecutionStatusWakeInProgress ExecutionStatus = "wake_in_progress"
	ExecutionStatusQueued         ExecutionStatus = "queued"
	ExecutionStatusRunning        ExecutionStatus = "running"
	ExecutionStatusSucceeded      ExecutionStatus = "succeeded"
	ExecutionStatusFailed         ExecutionStatus = "failed"
	ExecutionStatusCancelled      ExecutionStatus = "cancelled"
	ExecutionStatusExpired        ExecutionStatus = "expired"
)

func (r ExecutionStatus) IsKnown() bool {
	switch r {
	case ExecutionStatusWakeInProgress, ExecutionStatusQueued, ExecutionStatusRunning, ExecutionStatusSucceeded, ExecutionStatusFailed, ExecutionStatusCancelled, ExecutionStatusExpired:
		return true
	}
	return false
}

type ExecutionList struct {
	Items      []Execution       `json:"items" api:"required,nullable"`
	NextCursor string            `json:"next_cursor"`
	JSON       executionListJSON `json:"-"`
}

// executionListJSON contains the JSON metadata for the struct [ExecutionList]
type executionListJSON struct {
	Items       apijson.Field
	NextCursor  apijson.Field
	raw         string
	ExtraFields map[string]apijson.Field
}

func (r *ExecutionList) UnmarshalJSON(data []byte) (err error) {
	return apijson.UnmarshalRoot(data, r)
}

func (r executionListJSON) RawJSON() string {
	return r.raw
}

type ExecutionOutput struct {
	ExecutionID     string              `json:"execution_id" api:"required"`
	Stderr          string              `json:"stderr"`
	StderrBytes     int64               `json:"stderr_bytes"`
	StderrTruncated bool                `json:"stderr_truncated"`
	Stdout          string              `json:"stdout"`
	StdoutBytes     int64               `json:"stdout_bytes"`
	StdoutTruncated bool                `json:"stdout_truncated"`
	JSON            executionOutputJSON `json:"-"`
}

// executionOutputJSON contains the JSON metadata for the struct [ExecutionOutput]
type executionOutputJSON struct {
	ExecutionID     apijson.Field
	Stderr          apijson.Field
	StderrBytes     apijson.Field
	StderrTruncated apijson.Field
	Stdout          apijson.Field
	StdoutBytes     apijson.Field
	StdoutTruncated apijson.Field
	raw             string
	ExtraFields     map[string]apijson.Field
}

func (r *ExecutionOutput) UnmarshalJSON(data []byte) (err error) {
	return apijson.UnmarshalRoot(data, r)
}

func (r executionOutputJSON) RawJSON() string {
	return r.raw
}

type ExecutionEvent struct {
	At           time.Time            `json:"at" api:"required" format:"date-time"`
	Sequence     int64                `json:"sequence" api:"required"`
	Type         ExecutionEventType   `json:"type" api:"required"`
	Chunk        string               `json:"chunk"`
	ErrorCode    string               `json:"error_code"`
	ErrorMessage string               `json:"error_message"`
	ExitCode     int64                `json:"exit_code"`
	Signal       int64                `json:"signal"`
	Status       ExecutionEventStatus `json:"status"`
	JSON         executionEventJSON   `json:"-"`
}

// executionEventJSON contains the JSON metadata for the struct [ExecutionEvent]
type executionEventJSON struct {
	At           apijson.Field
	Sequence     apijson.Field
	Type         apijson.Field
	Chunk        apijson.Field
	ErrorCode    apijson.Field
	ErrorMessage apijson.Field
	ExitCode     apijson.Field
	Signal       apijson.Field
	Status       apijson.Field
	raw          string
	ExtraFields  map[string]apijson.Field
}

func (r *ExecutionEvent) UnmarshalJSON(data []byte) (err error) {
	return apijson.UnmarshalRoot(data, r)
}

func (r executionEventJSON) RawJSON() string {
	return r.raw
}

type ExecutionEventStatus string

const (
	ExecutionEventStatusWakeInProgress ExecutionEventStatus = "wake_in_progress"
	ExecutionEventStatusQueued         ExecutionEventStatus = "queued"
	ExecutionEventStatusRunning        ExecutionEventStatus = "running"
	ExecutionEventStatusSucceeded      ExecutionEventStatus = "succeeded"
	ExecutionEventStatusFailed         ExecutionEventStatus = "failed"
	ExecutionEventStatusCancelled      ExecutionEventStatus = "cancelled"
	ExecutionEventStatusExpired        ExecutionEventStatus = "expired"
)

func (r ExecutionEventStatus) IsKnown() bool {
	switch r {
	case ExecutionEventStatusWakeInProgress, ExecutionEventStatusQueued, ExecutionEventStatusRunning, ExecutionEventStatusSucceeded, ExecutionEventStatusFailed, ExecutionEventStatusCancelled, ExecutionEventStatusExpired:
		return true
	}
	return false
}

type ExecutionEventType string

const (
	ExecutionEventTypeLifecycle ExecutionEventType = "lifecycle"
	ExecutionEventTypeStdout    ExecutionEventType = "stdout"
	ExecutionEventTypeStderr    ExecutionEventType = "stderr"
)

func (r ExecutionEventType) IsKnown() bool {
	switch r {
	case ExecutionEventTypeLifecycle, ExecutionEventTypeStdout, ExecutionEventTypeStderr:
		return true
	}
	return false
}

type ExecutionEvents struct {
	Items      []ExecutionEvent    `json:"items" api:"required,nullable"`
	NextCursor string              `json:"next_cursor"`
	JSON       executionEventsJSON `json:"-"`
}

// executionEventsJSON contains the JSON metadata for the struct [ExecutionEvents]
type executionEventsJSON struct {
	Items       apijson.Field
	NextCursor  apijson.Field
	raw         string
	ExtraFields map[string]apijson.Field
}

func (r *ExecutionEvents) UnmarshalJSON(data []byte) (err error) {
	return apijson.UnmarshalRoot(data, r)
}

func (r executionEventsJSON) RawJSON() string {
	return r.raw
}

type ArtifactRef struct {
	ArtifactID string          `json:"artifact_id" api:"required"`
	Name       string          `json:"name" api:"required"`
	JSON       artifactRefJSON `json:"-"`
}

// artifactRefJSON contains the JSON metadata for the struct [ArtifactRef]
type artifactRefJSON struct {
	ArtifactID  apijson.Field
	Name        apijson.Field
	raw         string
	ExtraFields map[string]apijson.Field
}

func (r *ArtifactRef) UnmarshalJSON(data []byte) (err error) {
	return apijson.UnmarshalRoot(data, r)
}

func (r artifactRefJSON) RawJSON() string {
	return r.raw
}

type ExecutionCreateParamsParam struct {
	Command   param.Field[[]string]          `json:"command" api:"required"`
	Cwd       param.Field[string]            `json:"cwd"`
	Env       param.Field[map[string]string] `json:"env"`
	Stdin     param.Field[string]            `json:"stdin"`
	TimeoutMs param.Field[int64]             `json:"timeout_ms"`
}

func (r ExecutionCreateParamsParam) MarshalJSON() (data []byte, err error) {
	return apijson.MarshalRoot(r)
}

type MachineExecutionListParams struct {
	// Bare, lowercase, hyphenated Machine UUID. Pass the returned machine_id
	// unchanged.
	MachineID string              `path:"machine_id" api:"required" json:"-"`
	Cursor    param.Field[string] `query:"cursor"`
	Limit     param.Field[int64]  `query:"limit"`
}

// URLQuery serializes [MachineExecutionListParams]'s query parameters as `url.Values`.
func (r MachineExecutionListParams) URLQuery() (v url.Values) {
	return apiquery.MarshalWithSettings(r, apiquery.QuerySettings{
		ArrayFormat:  apiquery.ArrayQueryFormatComma,
		NestedFormat: apiquery.NestedQueryFormatBrackets,
	})
}

type MachineExecutionNewParams struct {
	// Bare, lowercase, hyphenated Machine UUID. Pass the returned machine_id
	// unchanged.
	MachineID             string                `path:"machine_id" api:"required" json:"-"`
	ExecutionCreateParams ExecutionCreateParams `json:"execution_create_params" api:"required"`
}

func (r MachineExecutionNewParams) MarshalJSON() (data []byte, err error) {
	return apijson.MarshalRoot(r.ExecutionCreateParams)
}

type MachineExecutionGetParams struct {
	ExecutionID string `path:"execution_id" api:"required" json:"-"`
	// Bare, lowercase, hyphenated Machine UUID. Pass the returned machine_id
	// unchanged.
	MachineID string `path:"machine_id" api:"required" json:"-"`
}

type MachineExecutionDeleteParams struct {
	ExecutionID string `path:"execution_id" api:"required" json:"-"`
	// Bare, lowercase, hyphenated Machine UUID. Pass the returned machine_id
	// unchanged.
	MachineID string `path:"machine_id" api:"required" json:"-"`
}

type MachineExecutionOutputParams struct {
	ExecutionID string `path:"execution_id" api:"required" json:"-"`
	// Bare, lowercase, hyphenated Machine UUID. Pass the returned machine_id
	// unchanged.
	MachineID string `path:"machine_id" api:"required" json:"-"`
}

type MachineExecutionEventsParams struct {
	ExecutionID string `path:"execution_id" api:"required" json:"-"`
	// Bare, lowercase, hyphenated Machine UUID. Pass the returned machine_id
	// unchanged.
	MachineID string              `path:"machine_id" api:"required" json:"-"`
	Cursor    param.Field[string] `query:"cursor"`
	Limit     param.Field[int64]  `query:"limit"`
}

// URLQuery serializes [MachineExecutionEventsParams]'s query parameters as `url.Values`.
func (r MachineExecutionEventsParams) URLQuery() (v url.Values) {
	return apiquery.MarshalWithSettings(r, apiquery.QuerySettings{
		ArrayFormat:  apiquery.ArrayQueryFormatComma,
		NestedFormat: apiquery.NestedQueryFormatBrackets,
	})
}

type ExecutionLogCapture struct {
	Code             string                   `json:"code"`
	LostBytes        string                   `json:"lost_bytes"`
	State            ExecutionLogCaptureState `json:"state"`
	UnconfirmedBytes string                   `json:"unconfirmed_bytes"`
	JSON             executionLogCaptureJSON  `json:"-"`
}

// executionLogCaptureJSON contains the JSON metadata for the struct [ExecutionLogCapture]
type executionLogCaptureJSON struct {
	Code             apijson.Field
	LostBytes        apijson.Field
	State            apijson.Field
	UnconfirmedBytes apijson.Field
	raw              string
	ExtraFields      map[string]apijson.Field
}

func (r *ExecutionLogCapture) UnmarshalJSON(data []byte) (err error) {
	return apijson.UnmarshalRoot(data, r)
}

func (r executionLogCaptureJSON) RawJSON() string {
	return r.raw
}

type ExecutionLogCaptureState string

const (
	ExecutionLogCaptureStatePending     ExecutionLogCaptureState = "pending"
	ExecutionLogCaptureStateIncomplete  ExecutionLogCaptureState = "incomplete"
	ExecutionLogCaptureStateUnavailable ExecutionLogCaptureState = "unavailable"
)

func (r ExecutionLogCaptureState) IsKnown() bool {
	switch r {
	case ExecutionLogCaptureStatePending, ExecutionLogCaptureStateIncomplete, ExecutionLogCaptureStateUnavailable:
		return true
	}
	return false
}
