// Code generated by Scalar SDK Generator. DO NOT EDIT.

package dedalus

import (
	"context"
	"errors"
	"fmt"
	"net/http"
	"net/url"
	"slices"

	"github.com/dedalus-labs/dedalus-go/internal/apijson"
	"github.com/dedalus-labs/dedalus-go/internal/param"
	"github.com/dedalus-labs/dedalus-go/internal/requestconfig"
	"github.com/dedalus-labs/dedalus-go/option"
)

// MachineNetworkService contains methods and other services that help with interacting
// with the API. You should not instantiate this service directly, and instead use
// the [NewMachineNetworkService] method instead.
type MachineNetworkService struct {
	Options []option.RequestOption
}

// NewMachineNetworkService generates a new service that applies the given options to each request.
// These options are applied after the parent client's options (if there is one), and
// before any request-specific options.
func NewMachineNetworkService(opts ...option.RequestOption) (r *MachineNetworkService) {
	r = &MachineNetworkService{}
	r.Options = opts
	return
}

// Get machine network identity
//
// Parameters:
//
//	ctx: Context for the request.
//	params: MachineNetworkGetParams request parameters.
//	opts: Options to apply to this request.
//
// Returns:
//
//	*MachineNetwork: OK
//
// Example:
//
//	network, err := client.Machines.Network.Get(context.Background(), sdk.MachineNetworkGetParams{
//		MachineID: "machineID",
//	})
//	if err != nil {
//		panic(err)
//	}
//
//	fmt.Println(network)
func (r *MachineNetworkService) Get(ctx context.Context, params MachineNetworkGetParams, opts ...option.RequestOption) (res *MachineNetwork, err error) {
	if params.XDedalusOrgID.Present {
		opts = append(opts, option.WithHeader("X-Dedalus-Org-Id", fmt.Sprintf("%v", params.XDedalusOrgID.Value)))
	}
	opts = slices.Concat(r.Options, opts)
	if params.MachineID == "" {
		err = errors.New("missing required machine_id parameter")
		return nil, err
	}
	path := fmt.Sprintf("v1/machines/%s/network", url.PathEscape(params.MachineID))
	err = requestconfig.ExecuteNewRequest(ctx, http.MethodGet, path, nil, &res, opts...)
	return res, err
}

type MachineNetwork struct {
	Hostname    string             `json:"hostname" api:"required"`
	MachineID   string             `json:"machine_id" api:"required"`
	NetworkID   string             `json:"network_id" api:"required"`
	NetworkName string             `json:"network_name" api:"required"`
	PrivateIpv4 string             `json:"private_ipv4" api:"required"`
	PrivateIpv6 string             `json:"private_ipv6" api:"required"`
	JSON        machineNetworkJSON `json:"-"`
}

// machineNetworkJSON contains the JSON metadata for the struct [MachineNetwork]
type machineNetworkJSON struct {
	Hostname    apijson.Field
	MachineID   apijson.Field
	NetworkID   apijson.Field
	NetworkName apijson.Field
	PrivateIpv4 apijson.Field
	PrivateIpv6 apijson.Field
	raw         string
	ExtraFields map[string]apijson.Field
}

func (r *MachineNetwork) UnmarshalJSON(data []byte) (err error) {
	return apijson.UnmarshalRoot(data, r)
}

func (r machineNetworkJSON) RawJSON() string {
	return r.raw
}

type MachineNetworkGetParams struct {
	MachineID     string              `path:"machine_id" api:"required" json:"-"`
	XDedalusOrgID param.Field[string] `header:"X-Dedalus-Org-Id"`
}
