// Code generated by Scalar SDK Generator. DO NOT EDIT.

package dedalus

import (
	"context"
	"errors"
	"fmt"
	"net/http"
	"net/url"
	"slices"
	"time"

	"github.com/dedalus-labs/dedalus-go/internal/apijson"
	"github.com/dedalus-labs/dedalus-go/internal/apiquery"
	"github.com/dedalus-labs/dedalus-go/internal/param"
	"github.com/dedalus-labs/dedalus-go/internal/requestconfig"
	"github.com/dedalus-labs/dedalus-go/option"
	"github.com/dedalus-labs/dedalus-go/packages/pagination"
)

// MachineArtifactService contains methods and other services that help with interacting
// with the API. You should not instantiate this service directly, and instead use
// the [NewMachineArtifactService] method instead.
type MachineArtifactService struct {
	Options []option.RequestOption
}

// NewMachineArtifactService generates a new service that applies the given options to each request.
// These options are applied after the parent client's options (if there is one), and
// before any request-specific options.
func NewMachineArtifactService(opts ...option.RequestOption) (r *MachineArtifactService) {
	r = &MachineArtifactService{}
	r.Options = opts
	return
}

// List artifacts
//
// Parameters:
//
//	ctx: Context for the request.
//	query: MachineArtifactListParams request parameters.
//	opts: Options to apply to this request.
//
// Returns:
//
//	*pagination.CursorPage[Artifact]: OK
//
// Example:
//
//	page, err := client.Machines.Artifacts.List(context.Background(), sdk.MachineArtifactListParams{
//		MachineID: "machineID",
//	})
//	if err != nil {
//		panic(err)
//	}
//
//	fmt.Println(page)
func (r *MachineArtifactService) List(ctx context.Context, query MachineArtifactListParams, opts ...option.RequestOption) (res *pagination.CursorPage[Artifact], err error) {
	var raw *http.Response
	if query.XDedalusOrgID.Present {
		opts = append(opts, option.WithHeader("X-Dedalus-Org-Id", fmt.Sprintf("%v", query.XDedalusOrgID.Value)))
	}
	opts = slices.Concat(r.Options, opts)
	opts = append([]option.RequestOption{option.WithResponseInto(&raw)}, opts...)
	if query.MachineID == "" {
		err = errors.New("missing required machine_id parameter")
		return nil, err
	}
	path := fmt.Sprintf("v1/machines/%s/artifacts", url.PathEscape(query.MachineID))
	cfg, err := requestconfig.NewRequestConfig(ctx, http.MethodGet, path, query, &res, opts...)
	if err != nil {
		return nil, err
	}
	err = cfg.Execute()
	if err != nil {
		return nil, err
	}
	res.SetPageConfig(cfg, raw)
	return res, nil
}

// ListAutoPaging returns an auto-pager for List.
//
// Returns:
//
//	*pagination.CursorPageAutoPager[Artifact]
func (r *MachineArtifactService) ListAutoPaging(ctx context.Context, query MachineArtifactListParams, opts ...option.RequestOption) *pagination.CursorPageAutoPager[Artifact] {
	return pagination.NewCursorPageAutoPager(r.List(ctx, query, opts...))
}

// Get artifact
//
// Parameters:
//
//	ctx: Context for the request.
//	params: MachineArtifactGetParams request parameters.
//	opts: Options to apply to this request.
//
// Returns:
//
//	*Artifact: OK
//
// Example:
//
//	artifact, err := client.Machines.Artifacts.Get(context.Background(), sdk.MachineArtifactGetParams{
//		ArtifactID: "artifactID",
//		MachineID:  "machineID",
//	})
//	if err != nil {
//		panic(err)
//	}
//
//	fmt.Println(artifact.ArtifactID)
func (r *MachineArtifactService) Get(ctx context.Context, params MachineArtifactGetParams, opts ...option.RequestOption) (res *Artifact, err error) {
	if params.XDedalusOrgID.Present {
		opts = append(opts, option.WithHeader("X-Dedalus-Org-Id", fmt.Sprintf("%v", params.XDedalusOrgID.Value)))
	}
	opts = slices.Concat(r.Options, opts)
	if params.ArtifactID == "" {
		err = errors.New("missing required artifact_id parameter")
		return nil, err
	}
	if params.MachineID == "" {
		err = errors.New("missing required machine_id parameter")
		return nil, err
	}
	path := fmt.Sprintf("v1/machines/%s/artifacts/%s", url.PathEscape(params.MachineID), url.PathEscape(params.ArtifactID))
	err = requestconfig.ExecuteNewRequest(ctx, http.MethodGet, path, nil, &res, opts...)
	return res, err
}

// Delete artifact
//
// Parameters:
//
//	ctx: Context for the request.
//	params: MachineArtifactDeleteParams request parameters.
//	opts: Options to apply to this request.
//
// Returns:
//
//	*Artifact: OK
//
// Example:
//
//	artifact, err := client.Machines.Artifacts.Delete(context.Background(), sdk.MachineArtifactDeleteParams{
//		ArtifactID: "artifactID",
//		MachineID:  "machineID",
//	})
//	if err != nil {
//		panic(err)
//	}
//
//	fmt.Println(artifact.ArtifactID)
func (r *MachineArtifactService) Delete(ctx context.Context, params MachineArtifactDeleteParams, opts ...option.RequestOption) (res *Artifact, err error) {
	if params.XDedalusOrgID.Present {
		opts = append(opts, option.WithHeader("X-Dedalus-Org-Id", fmt.Sprintf("%v", params.XDedalusOrgID.Value)))
	}
	opts = slices.Concat(r.Options, opts)
	if params.ArtifactID == "" {
		err = errors.New("missing required artifact_id parameter")
		return nil, err
	}
	if params.MachineID == "" {
		err = errors.New("missing required machine_id parameter")
		return nil, err
	}
	path := fmt.Sprintf("v1/machines/%s/artifacts/%s", url.PathEscape(params.MachineID), url.PathEscape(params.ArtifactID))
	err = requestconfig.ExecuteNewRequest(ctx, http.MethodDelete, path, nil, &res, opts...)
	return res, err
}

type Artifact struct {
	ArtifactID  string       `json:"artifact_id" api:"required"`
	CreatedAt   time.Time    `json:"created_at" api:"required" format:"date-time"`
	MachineID   string       `json:"machine_id" api:"required"`
	Name        string       `json:"name" api:"required"`
	SizeBytes   int64        `json:"size_bytes" api:"required"`
	DownloadURL string       `json:"download_url"`
	ExecutionID string       `json:"execution_id"`
	ExpiresAt   time.Time    `json:"expires_at" format:"date-time"`
	MimeType    string       `json:"mime_type"`
	Sha256      string       `json:"sha256"`
	JSON        artifactJSON `json:"-"`
}

// artifactJSON contains the JSON metadata for the struct [Artifact]
type artifactJSON struct {
	ArtifactID  apijson.Field
	CreatedAt   apijson.Field
	MachineID   apijson.Field
	Name        apijson.Field
	SizeBytes   apijson.Field
	DownloadURL apijson.Field
	ExecutionID apijson.Field
	ExpiresAt   apijson.Field
	MimeType    apijson.Field
	Sha256      apijson.Field
	raw         string
	ExtraFields map[string]apijson.Field
}

func (r *Artifact) UnmarshalJSON(data []byte) (err error) {
	return apijson.UnmarshalRoot(data, r)
}

func (r artifactJSON) RawJSON() string {
	return r.raw
}

type ArtifactList struct {
	Items      []Artifact       `json:"items" api:"required,nullable"`
	NextCursor string           `json:"next_cursor"`
	JSON       artifactListJSON `json:"-"`
}

// artifactListJSON contains the JSON metadata for the struct [ArtifactList]
type artifactListJSON struct {
	Items       apijson.Field
	NextCursor  apijson.Field
	raw         string
	ExtraFields map[string]apijson.Field
}

func (r *ArtifactList) UnmarshalJSON(data []byte) (err error) {
	return apijson.UnmarshalRoot(data, r)
}

func (r artifactListJSON) RawJSON() string {
	return r.raw
}

type MachineArtifactListParams struct {
	MachineID     string              `path:"machine_id" api:"required" json:"-"`
	Cursor        param.Field[string] `query:"cursor"`
	Limit         param.Field[int64]  `query:"limit"`
	XDedalusOrgID param.Field[string] `header:"X-Dedalus-Org-Id"`
}

// URLQuery serializes [MachineArtifactListParams]'s query parameters as `url.Values`.
func (r MachineArtifactListParams) URLQuery() (v url.Values) {
	return apiquery.MarshalWithSettings(r, apiquery.QuerySettings{
		ArrayFormat:  apiquery.ArrayQueryFormatComma,
		NestedFormat: apiquery.NestedQueryFormatBrackets,
	})
}

type MachineArtifactGetParams struct {
	ArtifactID    string              `path:"artifact_id" api:"required" json:"-"`
	MachineID     string              `path:"machine_id" api:"required" json:"-"`
	XDedalusOrgID param.Field[string] `header:"X-Dedalus-Org-Id"`
}

type MachineArtifactDeleteParams struct {
	ArtifactID    string              `path:"artifact_id" api:"required" json:"-"`
	MachineID     string              `path:"machine_id" api:"required" json:"-"`
	XDedalusOrgID param.Field[string] `header:"X-Dedalus-Org-Id"`
}
