// Code generated by Scalar SDK Generator. DO NOT EDIT.

package dedalus

import (
	"context"
	"errors"
	"fmt"
	"net/http"
	"net/url"
	"slices"
	"time"

	"github.com/dedalus-labs/dedalus-go/internal/apijson"
	"github.com/dedalus-labs/dedalus-go/internal/param"
	"github.com/dedalus-labs/dedalus-go/internal/requestconfig"
	"github.com/dedalus-labs/dedalus-go/option"
)

// MachineExecutionLogService contains methods and other services that help with interacting
// with the API. You should not instantiate this service directly, and instead use
// the [NewMachineExecutionLogService] method instead.
type MachineExecutionLogService struct {
	Options []option.RequestOption
}

// NewMachineExecutionLogService generates a new service that applies the given options to each request.
// These options are applied after the parent client's options (if there is one), and
// before any request-specific options.
func NewMachineExecutionLogService(opts ...option.RequestOption) (r *MachineExecutionLogService) {
	r = &MachineExecutionLogService{}
	r.Options = opts
	return
}

// Get execution log status
//
// Parameters:
//
//	ctx: Context for the request.
//	params: MachineExecutionLogGetParams request parameters.
//	opts: Options to apply to this request.
//
// Returns:
//
//	*Status: OK
//
// Example:
//
//	log, err := client.Machines.Executions.Logs.Get(context.Background(), sdk.MachineExecutionLogGetParams{
//		ExecutionID: "executionID",
//		MachineID:   "017f22e2-79b0-7cc3-98c4-dc0c0c07398f",
//	})
//	if err != nil {
//		panic(err)
//	}
//
//	fmt.Println(log)
func (r *MachineExecutionLogService) Get(ctx context.Context, params MachineExecutionLogGetParams, opts ...option.RequestOption) (res *Status, err error) {
	opts = slices.Concat(r.Options, opts)
	if params.ExecutionID == "" {
		err = errors.New("missing required execution_id parameter")
		return nil, err
	}
	if params.MachineID == "" {
		err = errors.New("missing required machine_id parameter")
		return nil, err
	}
	path := fmt.Sprintf("v1/machines/%s/executions/%s/logs", url.PathEscape(params.MachineID), url.PathEscape(params.ExecutionID))
	err = requestconfig.ExecuteNewRequest(ctx, http.MethodGet, path, nil, &res, opts...)
	return res, err
}

// Reauthorize execution log publication
//
// Parameters:
//
//	ctx: Context for the request.
//	params: MachineExecutionLogReauthorizeParams request parameters.
//	opts: Options to apply to this request.
//
// Returns:
//
//	*Status: OK
//
// Example:
//
//	log, err := client.Machines.Executions.Logs.Reauthorize(context.Background(), sdk.MachineExecutionLogReauthorizeParams{
//		ExecutionID: "executionID",
//		MachineID:   "017f22e2-79b0-7cc3-98c4-dc0c0c07398f",
//	})
//	if err != nil {
//		panic(err)
//	}
//
//	fmt.Println(log)
func (r *MachineExecutionLogService) Reauthorize(ctx context.Context, params MachineExecutionLogReauthorizeParams, opts ...option.RequestOption) (res *Status, err error) {
	opts = slices.Concat(r.Options, opts)
	if params.ExecutionID == "" {
		err = errors.New("missing required execution_id parameter")
		return nil, err
	}
	if params.MachineID == "" {
		err = errors.New("missing required machine_id parameter")
		return nil, err
	}
	path := fmt.Sprintf("v1/machines/%s/executions/%s/logs/reauthorize", url.PathEscape(params.MachineID), url.PathEscape(params.ExecutionID))
	err = requestconfig.ExecuteNewRequest(ctx, http.MethodPost, path, nil, &res, opts...)
	return res, err
}

// Create execution log read token
//
// Parameters:
//
//	ctx: Context for the request.
//	params: MachineExecutionLogNewTokenParams request parameters.
//	opts: Options to apply to this request.
//
// Returns:
//
//	*ReadToken: OK
//
// Example:
//
//	log, err := client.Machines.Executions.Logs.NewToken(context.Background(), sdk.MachineExecutionLogNewTokenParams{
//		ExecutionID: "executionID",
//		MachineID:   "017f22e2-79b0-7cc3-98c4-dc0c0c07398f",
//	})
//	if err != nil {
//		panic(err)
//	}
//
//	fmt.Println(log)
func (r *MachineExecutionLogService) NewToken(ctx context.Context, params MachineExecutionLogNewTokenParams, opts ...option.RequestOption) (res *ReadToken, err error) {
	opts = slices.Concat(r.Options, opts)
	if params.ExecutionID == "" {
		err = errors.New("missing required execution_id parameter")
		return nil, err
	}
	if params.MachineID == "" {
		err = errors.New("missing required machine_id parameter")
		return nil, err
	}
	path := fmt.Sprintf("v1/machines/%s/executions/%s/logs/token", url.PathEscape(params.MachineID), url.PathEscape(params.ExecutionID))
	err = requestconfig.ExecuteNewRequest(ctx, http.MethodPost, path, nil, &res, opts...)
	return res, err
}

type Status struct {
	Capture     StatusCapture     `json:"capture" api:"required"`
	ExecutionID string            `json:"execution_id" api:"required"`
	Code        string            `json:"code"`
	Publication StatusPublication `json:"publication"`
	StreamID    string            `json:"stream_id"`
	JSON        statusJSON        `json:"-"`
}

// statusJSON contains the JSON metadata for the struct [Status]
type statusJSON struct {
	Capture     apijson.Field
	ExecutionID apijson.Field
	Code        apijson.Field
	Publication apijson.Field
	StreamID    apijson.Field
	raw         string
	ExtraFields map[string]apijson.Field
}

func (r *Status) UnmarshalJSON(data []byte) (err error) {
	return apijson.UnmarshalRoot(data, r)
}

func (r statusJSON) RawJSON() string {
	return r.raw
}

type ReadToken struct {
	AccessToken string        `json:"access_token" api:"required"`
	BaseURL     string        `json:"base_url" api:"required"`
	ExecutionID string        `json:"execution_id" api:"required"`
	ExpiresAt   time.Time     `json:"expires_at" api:"required" format:"date-time"`
	StreamID    string        `json:"stream_id" api:"required"`
	TokenType   string        `json:"token_type" api:"required"`
	JSON        readTokenJSON `json:"-"`
}

// readTokenJSON contains the JSON metadata for the struct [ReadToken]
type readTokenJSON struct {
	AccessToken apijson.Field
	BaseURL     apijson.Field
	ExecutionID apijson.Field
	ExpiresAt   apijson.Field
	StreamID    apijson.Field
	TokenType   apijson.Field
	raw         string
	ExtraFields map[string]apijson.Field
}

func (r *ReadToken) UnmarshalJSON(data []byte) (err error) {
	return apijson.UnmarshalRoot(data, r)
}

func (r readTokenJSON) RawJSON() string {
	return r.raw
}

type StatusPublication struct {
	Complete       bool                   `json:"complete" api:"required"`
	QueuedMessages int64                  `json:"queued_messages" api:"required"`
	State          StatusPublicationState `json:"state" api:"required"`
	Code           string                 `json:"code"`
	JSON           statusPublicationJSON  `json:"-"`
}

// statusPublicationJSON contains the JSON metadata for the struct [StatusPublication]
type statusPublicationJSON struct {
	Complete       apijson.Field
	QueuedMessages apijson.Field
	State          apijson.Field
	Code           apijson.Field
	raw            string
	ExtraFields    map[string]apijson.Field
}

func (r *StatusPublication) UnmarshalJSON(data []byte) (err error) {
	return apijson.UnmarshalRoot(data, r)
}

func (r statusPublicationJSON) RawJSON() string {
	return r.raw
}

type StatusPublicationState string

const (
	StatusPublicationStateActive    StatusPublicationState = "active"
	StatusPublicationStateFinishing StatusPublicationState = "finishing"
	StatusPublicationStateFailed    StatusPublicationState = "failed"
	StatusPublicationStateClosed    StatusPublicationState = "closed"
)

func (r StatusPublicationState) IsKnown() bool {
	switch r {
	case StatusPublicationStateActive, StatusPublicationStateFinishing, StatusPublicationStateFailed, StatusPublicationStateClosed:
		return true
	}
	return false
}

type StatusPublicationParam struct {
	Complete       param.Field[bool]                   `json:"complete" api:"required"`
	QueuedMessages param.Field[int64]                  `json:"queued_messages" api:"required"`
	State          param.Field[StatusPublicationState] `json:"state" api:"required"`
	Code           param.Field[string]                 `json:"code"`
}

func (r StatusPublicationParam) MarshalJSON() (data []byte, err error) {
	return apijson.MarshalRoot(r)
}

type MachineExecutionLogGetParams struct {
	ExecutionID string `path:"execution_id" api:"required" json:"-"`
	// Bare, lowercase, hyphenated Machine UUID. Pass the returned machine_id
	// unchanged.
	MachineID string `path:"machine_id" api:"required" json:"-"`
}

type MachineExecutionLogReauthorizeParams struct {
	ExecutionID string `path:"execution_id" api:"required" json:"-"`
	// Bare, lowercase, hyphenated Machine UUID. Pass the returned machine_id
	// unchanged.
	MachineID string `path:"machine_id" api:"required" json:"-"`
}

type MachineExecutionLogNewTokenParams struct {
	ExecutionID string `path:"execution_id" api:"required" json:"-"`
	// Bare, lowercase, hyphenated Machine UUID. Pass the returned machine_id
	// unchanged.
	MachineID string `path:"machine_id" api:"required" json:"-"`
}

type StatusCapture struct {
	Code             string             `json:"code"`
	LostBytes        string             `json:"lost_bytes"`
	State            StatusCaptureState `json:"state"`
	UnconfirmedBytes string             `json:"unconfirmed_bytes"`
	JSON             statusCaptureJSON  `json:"-"`
}

// statusCaptureJSON contains the JSON metadata for the struct [StatusCapture]
type statusCaptureJSON struct {
	Code             apijson.Field
	LostBytes        apijson.Field
	State            apijson.Field
	UnconfirmedBytes apijson.Field
	raw              string
	ExtraFields      map[string]apijson.Field
}

func (r *StatusCapture) UnmarshalJSON(data []byte) (err error) {
	return apijson.UnmarshalRoot(data, r)
}

func (r statusCaptureJSON) RawJSON() string {
	return r.raw
}

type StatusCaptureState string

const (
	StatusCaptureStatePending     StatusCaptureState = "pending"
	StatusCaptureStateIncomplete  StatusCaptureState = "incomplete"
	StatusCaptureStateUnavailable StatusCaptureState = "unavailable"
)

func (r StatusCaptureState) IsKnown() bool {
	switch r {
	case StatusCaptureStatePending, StatusCaptureStateIncomplete, StatusCaptureStateUnavailable:
		return true
	}
	return false
}
