// Code generated by Scalar SDK Generator. DO NOT EDIT.

package dedalus

import (
	"context"
	"errors"
	"fmt"
	"net/http"
	"net/url"
	"slices"
	"time"

	"github.com/dedalus-labs/dedalus-go/internal/apijson"
	"github.com/dedalus-labs/dedalus-go/internal/apiquery"
	"github.com/dedalus-labs/dedalus-go/internal/param"
	"github.com/dedalus-labs/dedalus-go/internal/requestconfig"
	"github.com/dedalus-labs/dedalus-go/option"
	"github.com/dedalus-labs/dedalus-go/packages/pagination"
)

// MachineSSHService contains methods and other services that help with interacting
// with the API. You should not instantiate this service directly, and instead use
// the [NewMachineSSHService] method instead.
type MachineSSHService struct {
	Options []option.RequestOption
}

// NewMachineSSHService generates a new service that applies the given options to each request.
// These options are applied after the parent client's options (if there is one), and
// before any request-specific options.
func NewMachineSSHService(opts ...option.RequestOption) (r *MachineSSHService) {
	r = &MachineSSHService{}
	r.Options = opts
	return
}

// List SSH sessions
//
// Parameters:
//
//	ctx: Context for the request.
//	query: MachineSSHListParams request parameters.
//	opts: Options to apply to this request.
//
// Returns:
//
//	*pagination.CursorPage[SSHSession]: OK
//
// Example:
//
//	page, err := client.Machines.SSH.List(context.Background(), sdk.MachineSSHListParams{
//		MachineID: "machineID",
//	})
//	if err != nil {
//		panic(err)
//	}
//
//	fmt.Println(page)
func (r *MachineSSHService) List(ctx context.Context, query MachineSSHListParams, opts ...option.RequestOption) (res *pagination.CursorPage[SSHSession], err error) {
	var raw *http.Response
	if query.XDedalusOrgID.Present {
		opts = append(opts, option.WithHeader("X-Dedalus-Org-Id", fmt.Sprintf("%v", query.XDedalusOrgID.Value)))
	}
	opts = slices.Concat(r.Options, opts)
	opts = append([]option.RequestOption{option.WithResponseInto(&raw)}, opts...)
	if query.MachineID == "" {
		err = errors.New("missing required machine_id parameter")
		return nil, err
	}
	path := fmt.Sprintf("v1/machines/%s/ssh", url.PathEscape(query.MachineID))
	cfg, err := requestconfig.NewRequestConfig(ctx, http.MethodGet, path, query, &res, opts...)
	if err != nil {
		return nil, err
	}
	err = cfg.Execute()
	if err != nil {
		return nil, err
	}
	res.SetPageConfig(cfg, raw)
	return res, nil
}

// ListAutoPaging returns an auto-pager for List.
//
// Returns:
//
//	*pagination.CursorPageAutoPager[SSHSession]
func (r *MachineSSHService) ListAutoPaging(ctx context.Context, query MachineSSHListParams, opts ...option.RequestOption) *pagination.CursorPageAutoPager[SSHSession] {
	return pagination.NewCursorPageAutoPager(r.List(ctx, query, opts...))
}

// Create SSH session
//
// Parameters:
//
//	ctx: Context for the request.
//	body: MachineSSHNewParams request parameters.
//	opts: Options to apply to this request.
//
// Returns:
//
//	*SSHSession: OK
//
// Example:
//
//	ssh, err := client.Machines.SSH.New(context.Background(), sdk.MachineSSHNewParams{
//		MachineID: "machineID",
//		SSHSessionCreateParams: sdk.SSHSessionCreateParams{
//			PublicKey: sdk.F[string](""),
//		},
//	})
//	if err != nil {
//		panic(err)
//	}
//
//	fmt.Println(ssh.SessionID)
func (r *MachineSSHService) New(ctx context.Context, body MachineSSHNewParams, opts ...option.RequestOption) (res *SSHSession, err error) {
	if body.XDedalusOrgID.Present {
		opts = append(opts, option.WithHeader("X-Dedalus-Org-Id", fmt.Sprintf("%v", body.XDedalusOrgID.Value)))
	}
	opts = slices.Concat(r.Options, opts)
	if body.MachineID == "" {
		err = errors.New("missing required machine_id parameter")
		return nil, err
	}
	path := fmt.Sprintf("v1/machines/%s/ssh", url.PathEscape(body.MachineID))
	err = requestconfig.ExecuteNewRequest(ctx, http.MethodPost, path, body, &res, opts...)
	return res, err
}

// Get SSH session
//
// Parameters:
//
//	ctx: Context for the request.
//	params: MachineSSHGetParams request parameters.
//	opts: Options to apply to this request.
//
// Returns:
//
//	*SSHSession: OK
//
// Example:
//
//	ssh, err := client.Machines.SSH.Get(context.Background(), sdk.MachineSSHGetParams{
//		MachineID: "machineID",
//		SessionID: "sessionID",
//	})
//	if err != nil {
//		panic(err)
//	}
//
//	fmt.Println(ssh.SessionID)
func (r *MachineSSHService) Get(ctx context.Context, params MachineSSHGetParams, opts ...option.RequestOption) (res *SSHSession, err error) {
	if params.XDedalusOrgID.Present {
		opts = append(opts, option.WithHeader("X-Dedalus-Org-Id", fmt.Sprintf("%v", params.XDedalusOrgID.Value)))
	}
	opts = slices.Concat(r.Options, opts)
	if params.MachineID == "" {
		err = errors.New("missing required machine_id parameter")
		return nil, err
	}
	if params.SessionID == "" {
		err = errors.New("missing required session_id parameter")
		return nil, err
	}
	path := fmt.Sprintf("v1/machines/%s/ssh/%s", url.PathEscape(params.MachineID), url.PathEscape(params.SessionID))
	err = requestconfig.ExecuteNewRequest(ctx, http.MethodGet, path, nil, &res, opts...)
	return res, err
}

// Delete SSH session
//
// Parameters:
//
//	ctx: Context for the request.
//	params: MachineSSHDeleteParams request parameters.
//	opts: Options to apply to this request.
//
// Returns:
//
//	*SSHSession: OK
//
// Example:
//
//	ssh, err := client.Machines.SSH.Delete(context.Background(), sdk.MachineSSHDeleteParams{
//		MachineID: "machineID",
//		SessionID: "sessionID",
//	})
//	if err != nil {
//		panic(err)
//	}
//
//	fmt.Println(ssh.SessionID)
func (r *MachineSSHService) Delete(ctx context.Context, params MachineSSHDeleteParams, opts ...option.RequestOption) (res *SSHSession, err error) {
	if params.XDedalusOrgID.Present {
		opts = append(opts, option.WithHeader("X-Dedalus-Org-Id", fmt.Sprintf("%v", params.XDedalusOrgID.Value)))
	}
	opts = slices.Concat(r.Options, opts)
	if params.MachineID == "" {
		err = errors.New("missing required machine_id parameter")
		return nil, err
	}
	if params.SessionID == "" {
		err = errors.New("missing required session_id parameter")
		return nil, err
	}
	path := fmt.Sprintf("v1/machines/%s/ssh/%s", url.PathEscape(params.MachineID), url.PathEscape(params.SessionID))
	err = requestconfig.ExecuteNewRequest(ctx, http.MethodDelete, path, nil, &res, opts...)
	return res, err
}

type SSHSessionCreateParams struct {
	PublicKey param.Field[string] `json:"public_key" api:"required"`
}

func (r SSHSessionCreateParams) MarshalJSON() (data []byte, err error) {
	return apijson.MarshalRoot(r)
}

type SSHSession struct {
	CreatedAt    time.Time        `json:"created_at" api:"required" format:"date-time"`
	MachineID    string           `json:"machine_id" api:"required"`
	SessionID    string           `json:"session_id" api:"required"`
	Status       SSHSessionStatus `json:"status" api:"required"`
	Connection   SSHConnection    `json:"connection"`
	ErrorCode    string           `json:"error_code"`
	ErrorMessage string           `json:"error_message"`
	ExpiresAt    time.Time        `json:"expires_at" format:"date-time"`
	ReadyAt      time.Time        `json:"ready_at" format:"date-time"`
	RetryAfterMs int64            `json:"retry_after_ms"`
	JSON         sshSessionJSON   `json:"-"`
}

// sshSessionJSON contains the JSON metadata for the struct [SSHSession]
type sshSessionJSON struct {
	CreatedAt    apijson.Field
	MachineID    apijson.Field
	SessionID    apijson.Field
	Status       apijson.Field
	Connection   apijson.Field
	ErrorCode    apijson.Field
	ErrorMessage apijson.Field
	ExpiresAt    apijson.Field
	ReadyAt      apijson.Field
	RetryAfterMs apijson.Field
	raw          string
	ExtraFields  map[string]apijson.Field
}

func (r *SSHSession) UnmarshalJSON(data []byte) (err error) {
	return apijson.UnmarshalRoot(data, r)
}

func (r sshSessionJSON) RawJSON() string {
	return r.raw
}

type SSHSessionStatus string

const (
	SSHSessionStatusWakeInProgress SSHSessionStatus = "wake_in_progress"
	SSHSessionStatusReady          SSHSessionStatus = "ready"
	SSHSessionStatusClosed         SSHSessionStatus = "closed"
	SSHSessionStatusExpired        SSHSessionStatus = "expired"
	SSHSessionStatusFailed         SSHSessionStatus = "failed"
)

func (r SSHSessionStatus) IsKnown() bool {
	switch r {
	case SSHSessionStatusWakeInProgress, SSHSessionStatusReady, SSHSessionStatusClosed, SSHSessionStatusExpired, SSHSessionStatusFailed:
		return true
	}
	return false
}

type SSHSessionList struct {
	Items      []SSHSession       `json:"items" api:"required,nullable"`
	NextCursor string             `json:"next_cursor"`
	JSON       sshSessionListJSON `json:"-"`
}

// sshSessionListJSON contains the JSON metadata for the struct [SSHSessionList]
type sshSessionListJSON struct {
	Items       apijson.Field
	NextCursor  apijson.Field
	raw         string
	ExtraFields map[string]apijson.Field
}

func (r *SSHSessionList) UnmarshalJSON(data []byte) (err error) {
	return apijson.UnmarshalRoot(data, r)
}

func (r sshSessionListJSON) RawJSON() string {
	return r.raw
}

type SSHConnection struct {
	Endpoint        string            `json:"endpoint" api:"required"`
	Port            int64             `json:"port" api:"required"`
	SSHUsername     string            `json:"ssh_username" api:"required"`
	HostTrust       SSHHostTrust      `json:"host_trust"`
	UserCertificate string            `json:"user_certificate"`
	JSON            sshConnectionJSON `json:"-"`
}

// sshConnectionJSON contains the JSON metadata for the struct [SSHConnection]
type sshConnectionJSON struct {
	Endpoint        apijson.Field
	Port            apijson.Field
	SSHUsername     apijson.Field
	HostTrust       apijson.Field
	UserCertificate apijson.Field
	raw             string
	ExtraFields     map[string]apijson.Field
}

func (r *SSHConnection) UnmarshalJSON(data []byte) (err error) {
	return apijson.UnmarshalRoot(data, r)
}

func (r sshConnectionJSON) RawJSON() string {
	return r.raw
}

type SSHHostTrust struct {
	HostPattern string           `json:"host_pattern" api:"required"`
	Kind        SSHHostTrustKind `json:"kind" api:"required"`
	PublicKey   string           `json:"public_key" api:"required"`
	JSON        sshHostTrustJSON `json:"-"`
}

// sshHostTrustJSON contains the JSON metadata for the struct [SSHHostTrust]
type sshHostTrustJSON struct {
	HostPattern apijson.Field
	Kind        apijson.Field
	PublicKey   apijson.Field
	raw         string
	ExtraFields map[string]apijson.Field
}

func (r *SSHHostTrust) UnmarshalJSON(data []byte) (err error) {
	return apijson.UnmarshalRoot(data, r)
}

func (r sshHostTrustJSON) RawJSON() string {
	return r.raw
}

type SSHHostTrustKind string

const (
	SSHHostTrustKindCertAuthority SSHHostTrustKind = "cert_authority"
)

func (r SSHHostTrustKind) IsKnown() bool {
	switch r {
	case SSHHostTrustKindCertAuthority:
		return true
	}
	return false
}

type SSHSessionCreateParamsParam struct {
	PublicKey param.Field[string] `json:"public_key" api:"required"`
}

func (r SSHSessionCreateParamsParam) MarshalJSON() (data []byte, err error) {
	return apijson.MarshalRoot(r)
}

type MachineSSHListParams struct {
	MachineID     string              `path:"machine_id" api:"required" json:"-"`
	Cursor        param.Field[string] `query:"cursor"`
	Limit         param.Field[int64]  `query:"limit"`
	XDedalusOrgID param.Field[string] `header:"X-Dedalus-Org-Id"`
}

// URLQuery serializes [MachineSSHListParams]'s query parameters as `url.Values`.
func (r MachineSSHListParams) URLQuery() (v url.Values) {
	return apiquery.MarshalWithSettings(r, apiquery.QuerySettings{
		ArrayFormat:  apiquery.ArrayQueryFormatComma,
		NestedFormat: apiquery.NestedQueryFormatBrackets,
	})
}

type MachineSSHNewParams struct {
	MachineID              string                 `path:"machine_id" api:"required" json:"-"`
	SSHSessionCreateParams SSHSessionCreateParams `json:"ssh_session_create_params" api:"required"`
	XDedalusOrgID          param.Field[string]    `header:"X-Dedalus-Org-Id"`
}

func (r MachineSSHNewParams) MarshalJSON() (data []byte, err error) {
	return apijson.MarshalRoot(r.SSHSessionCreateParams)
}

type MachineSSHGetParams struct {
	MachineID     string              `path:"machine_id" api:"required" json:"-"`
	SessionID     string              `path:"session_id" api:"required" json:"-"`
	XDedalusOrgID param.Field[string] `header:"X-Dedalus-Org-Id"`
}

type MachineSSHDeleteParams struct {
	MachineID     string              `path:"machine_id" api:"required" json:"-"`
	SessionID     string              `path:"session_id" api:"required" json:"-"`
	XDedalusOrgID param.Field[string] `header:"X-Dedalus-Org-Id"`
}
