// Code generated by Scalar SDK Generator. DO NOT EDIT.

package dedalus

import (
	"context"
	"errors"
	"fmt"
	"net/http"
	"net/url"
	"reflect"
	"slices"
	"time"

	"github.com/tidwall/gjson"

	"github.com/dedalus-labs/dedalus-go/internal/apijson"
	"github.com/dedalus-labs/dedalus-go/internal/apiquery"
	"github.com/dedalus-labs/dedalus-go/internal/param"
	"github.com/dedalus-labs/dedalus-go/internal/requestconfig"
	"github.com/dedalus-labs/dedalus-go/option"
	"github.com/dedalus-labs/dedalus-go/packages/pagination"
)

// MachineTerminalService contains methods and other services that help with interacting
// with the API. You should not instantiate this service directly, and instead use
// the [NewMachineTerminalService] method instead.
type MachineTerminalService struct {
	Options []option.RequestOption
}

// NewMachineTerminalService generates a new service that applies the given options to each request.
// These options are applied after the parent client's options (if there is one), and
// before any request-specific options.
func NewMachineTerminalService(opts ...option.RequestOption) (r *MachineTerminalService) {
	r = &MachineTerminalService{}
	r.Options = opts
	return
}

// List terminals
//
// Parameters:
//
//	ctx: Context for the request.
//	query: MachineTerminalListParams request parameters.
//	opts: Options to apply to this request.
//
// Returns:
//
//	*pagination.CursorPage[Terminal]: OK
//
// Example:
//
//	page, err := client.Machines.Terminals.List(context.Background(), sdk.MachineTerminalListParams{
//		MachineID: "machineID",
//	})
//	if err != nil {
//		panic(err)
//	}
//
//	fmt.Println(page)
func (r *MachineTerminalService) List(ctx context.Context, query MachineTerminalListParams, opts ...option.RequestOption) (res *pagination.CursorPage[Terminal], err error) {
	var raw *http.Response
	if query.XDedalusOrgID.Present {
		opts = append(opts, option.WithHeader("X-Dedalus-Org-Id", fmt.Sprintf("%v", query.XDedalusOrgID.Value)))
	}
	opts = slices.Concat(r.Options, opts)
	opts = append([]option.RequestOption{option.WithResponseInto(&raw)}, opts...)
	if query.MachineID == "" {
		err = errors.New("missing required machine_id parameter")
		return nil, err
	}
	path := fmt.Sprintf("v1/machines/%s/terminals", url.PathEscape(query.MachineID))
	cfg, err := requestconfig.NewRequestConfig(ctx, http.MethodGet, path, query, &res, opts...)
	if err != nil {
		return nil, err
	}
	err = cfg.Execute()
	if err != nil {
		return nil, err
	}
	res.SetPageConfig(cfg, raw)
	return res, nil
}

// ListAutoPaging returns an auto-pager for List.
//
// Returns:
//
//	*pagination.CursorPageAutoPager[Terminal]
func (r *MachineTerminalService) ListAutoPaging(ctx context.Context, query MachineTerminalListParams, opts ...option.RequestOption) *pagination.CursorPageAutoPager[Terminal] {
	return pagination.NewCursorPageAutoPager(r.List(ctx, query, opts...))
}

// Create terminal
//
// Parameters:
//
//	ctx: Context for the request.
//	body: MachineTerminalNewParams request parameters.
//	opts: Options to apply to this request.
//
// Returns:
//
//	*Terminal: OK
//
// Example:
//
//	terminal, err := client.Machines.Terminals.New(context.Background(), sdk.MachineTerminalNewParams{
//		MachineID: "machineID",
//		TerminalCreateParams: sdk.TerminalCreateParams{
//			Height: sdk.F[int64](0),
//			Width:  sdk.F[int64](0),
//		},
//	})
//	if err != nil {
//		panic(err)
//	}
//
//	fmt.Println(terminal.TerminalID)
func (r *MachineTerminalService) New(ctx context.Context, body MachineTerminalNewParams, opts ...option.RequestOption) (res *Terminal, err error) {
	if body.XDedalusOrgID.Present {
		opts = append(opts, option.WithHeader("X-Dedalus-Org-Id", fmt.Sprintf("%v", body.XDedalusOrgID.Value)))
	}
	opts = slices.Concat(r.Options, opts)
	if body.MachineID == "" {
		err = errors.New("missing required machine_id parameter")
		return nil, err
	}
	path := fmt.Sprintf("v1/machines/%s/terminals", url.PathEscape(body.MachineID))
	err = requestconfig.ExecuteNewRequest(ctx, http.MethodPost, path, body, &res, opts...)
	return res, err
}

// Get terminal
//
// Parameters:
//
//	ctx: Context for the request.
//	params: MachineTerminalGetParams request parameters.
//	opts: Options to apply to this request.
//
// Returns:
//
//	*Terminal: OK
//
// Example:
//
//	terminal, err := client.Machines.Terminals.Get(context.Background(), sdk.MachineTerminalGetParams{
//		MachineID:  "machineID",
//		TerminalID: "terminalID",
//	})
//	if err != nil {
//		panic(err)
//	}
//
//	fmt.Println(terminal.TerminalID)
func (r *MachineTerminalService) Get(ctx context.Context, params MachineTerminalGetParams, opts ...option.RequestOption) (res *Terminal, err error) {
	if params.XDedalusOrgID.Present {
		opts = append(opts, option.WithHeader("X-Dedalus-Org-Id", fmt.Sprintf("%v", params.XDedalusOrgID.Value)))
	}
	opts = slices.Concat(r.Options, opts)
	if params.MachineID == "" {
		err = errors.New("missing required machine_id parameter")
		return nil, err
	}
	if params.TerminalID == "" {
		err = errors.New("missing required terminal_id parameter")
		return nil, err
	}
	path := fmt.Sprintf("v1/machines/%s/terminals/%s", url.PathEscape(params.MachineID), url.PathEscape(params.TerminalID))
	err = requestconfig.ExecuteNewRequest(ctx, http.MethodGet, path, nil, &res, opts...)
	return res, err
}

// Delete terminal
//
// Parameters:
//
//	ctx: Context for the request.
//	params: MachineTerminalDeleteParams request parameters.
//	opts: Options to apply to this request.
//
// Returns:
//
//	*Terminal: OK
//
// Example:
//
//	terminal, err := client.Machines.Terminals.Delete(context.Background(), sdk.MachineTerminalDeleteParams{
//		MachineID:  "machineID",
//		TerminalID: "terminalID",
//	})
//	if err != nil {
//		panic(err)
//	}
//
//	fmt.Println(terminal.TerminalID)
func (r *MachineTerminalService) Delete(ctx context.Context, params MachineTerminalDeleteParams, opts ...option.RequestOption) (res *Terminal, err error) {
	if params.XDedalusOrgID.Present {
		opts = append(opts, option.WithHeader("X-Dedalus-Org-Id", fmt.Sprintf("%v", params.XDedalusOrgID.Value)))
	}
	opts = slices.Concat(r.Options, opts)
	if params.MachineID == "" {
		err = errors.New("missing required machine_id parameter")
		return nil, err
	}
	if params.TerminalID == "" {
		err = errors.New("missing required terminal_id parameter")
		return nil, err
	}
	path := fmt.Sprintf("v1/machines/%s/terminals/%s", url.PathEscape(params.MachineID), url.PathEscape(params.TerminalID))
	err = requestconfig.ExecuteNewRequest(ctx, http.MethodDelete, path, nil, &res, opts...)
	return res, err
}

type TerminalCreateParams struct {
	Height param.Field[int64]             `json:"height" api:"required"`
	Width  param.Field[int64]             `json:"width" api:"required"`
	Cwd    param.Field[string]            `json:"cwd"`
	Env    param.Field[map[string]string] `json:"env"`
	Shell  param.Field[string]            `json:"shell"`
}

func (r TerminalCreateParams) MarshalJSON() (data []byte, err error) {
	return apijson.MarshalRoot(r)
}

type Terminal struct {
	CreatedAt    time.Time        `json:"created_at" api:"required" format:"date-time"`
	Height       int64            `json:"height" api:"required"`
	MachineID    string           `json:"machine_id" api:"required"`
	Status       TerminalStatus   `json:"status" api:"required"`
	TerminalID   string           `json:"terminal_id" api:"required"`
	Width        int64            `json:"width" api:"required"`
	ErrorCode    string           `json:"error_code"`
	ErrorMessage string           `json:"error_message"`
	ExpiresAt    time.Time        `json:"expires_at" format:"date-time"`
	Protocol     TerminalProtocol `json:"protocol"`
	ReadyAt      time.Time        `json:"ready_at" format:"date-time"`
	RetryAfterMs int64            `json:"retry_after_ms"`
	StreamURL    string           `json:"stream_url"`
	JSON         terminalJSON     `json:"-"`
}

// terminalJSON contains the JSON metadata for the struct [Terminal]
type terminalJSON struct {
	CreatedAt    apijson.Field
	Height       apijson.Field
	MachineID    apijson.Field
	Status       apijson.Field
	TerminalID   apijson.Field
	Width        apijson.Field
	ErrorCode    apijson.Field
	ErrorMessage apijson.Field
	ExpiresAt    apijson.Field
	Protocol     apijson.Field
	ReadyAt      apijson.Field
	RetryAfterMs apijson.Field
	StreamURL    apijson.Field
	raw          string
	ExtraFields  map[string]apijson.Field
}

func (r *Terminal) UnmarshalJSON(data []byte) (err error) {
	return apijson.UnmarshalRoot(data, r)
}

func (r terminalJSON) RawJSON() string {
	return r.raw
}

type TerminalProtocol string

const (
	TerminalProtocolWebsocket TerminalProtocol = "websocket"
)

func (r TerminalProtocol) IsKnown() bool {
	switch r {
	case TerminalProtocolWebsocket:
		return true
	}
	return false
}

type TerminalStatus string

const (
	TerminalStatusWakeInProgress TerminalStatus = "wake_in_progress"
	TerminalStatusReady          TerminalStatus = "ready"
	TerminalStatusClosed         TerminalStatus = "closed"
	TerminalStatusExpired        TerminalStatus = "expired"
	TerminalStatusFailed         TerminalStatus = "failed"
)

func (r TerminalStatus) IsKnown() bool {
	switch r {
	case TerminalStatusWakeInProgress, TerminalStatusReady, TerminalStatusClosed, TerminalStatusExpired, TerminalStatusFailed:
		return true
	}
	return false
}

type TerminalList struct {
	Items      []Terminal       `json:"items" api:"required,nullable"`
	NextCursor string           `json:"next_cursor"`
	JSON       terminalListJSON `json:"-"`
}

// terminalListJSON contains the JSON metadata for the struct [TerminalList]
type terminalListJSON struct {
	Items       apijson.Field
	NextCursor  apijson.Field
	raw         string
	ExtraFields map[string]apijson.Field
}

func (r *TerminalList) UnmarshalJSON(data []byte) (err error) {
	return apijson.UnmarshalRoot(data, r)
}

func (r terminalListJSON) RawJSON() string {
	return r.raw
}

type TerminalInputEvent struct {
	// Base64-encoded terminal input.
	Data string                 `json:"data" api:"required" format:"byte"`
	Type TerminalInputEventType `json:"type" api:"required"`
	JSON terminalInputEventJSON `json:"-"`
}

// terminalInputEventJSON contains the JSON metadata for the struct [TerminalInputEvent]
type terminalInputEventJSON struct {
	Data        apijson.Field
	Type        apijson.Field
	raw         string
	ExtraFields map[string]apijson.Field
}

func (r *TerminalInputEvent) UnmarshalJSON(data []byte) (err error) {
	return apijson.UnmarshalRoot(data, r)
}

func (r terminalInputEventJSON) RawJSON() string {
	return r.raw
}

type TerminalInputEventType string

const (
	TerminalInputEventTypeInput TerminalInputEventType = "input"
)

func (r TerminalInputEventType) IsKnown() bool {
	switch r {
	case TerminalInputEventTypeInput:
		return true
	}
	return false
}

type TerminalResizeEvent struct {
	Height int64                   `json:"height" api:"required"`
	Type   TerminalResizeEventType `json:"type" api:"required"`
	Width  int64                   `json:"width" api:"required"`
	JSON   terminalResizeEventJSON `json:"-"`
}

// terminalResizeEventJSON contains the JSON metadata for the struct [TerminalResizeEvent]
type terminalResizeEventJSON struct {
	Height      apijson.Field
	Type        apijson.Field
	Width       apijson.Field
	raw         string
	ExtraFields map[string]apijson.Field
}

func (r *TerminalResizeEvent) UnmarshalJSON(data []byte) (err error) {
	return apijson.UnmarshalRoot(data, r)
}

func (r terminalResizeEventJSON) RawJSON() string {
	return r.raw
}

type TerminalResizeEventType string

const (
	TerminalResizeEventTypeResize TerminalResizeEventType = "resize"
)

func (r TerminalResizeEventType) IsKnown() bool {
	switch r {
	case TerminalResizeEventTypeResize:
		return true
	}
	return false
}

type TerminalOutputEvent struct {
	// Base64-encoded terminal output.
	Data string                  `json:"data" api:"required" format:"byte"`
	Type TerminalOutputEventType `json:"type" api:"required"`
	JSON terminalOutputEventJSON `json:"-"`
}

// terminalOutputEventJSON contains the JSON metadata for the struct [TerminalOutputEvent]
type terminalOutputEventJSON struct {
	Data        apijson.Field
	Type        apijson.Field
	raw         string
	ExtraFields map[string]apijson.Field
}

func (r *TerminalOutputEvent) UnmarshalJSON(data []byte) (err error) {
	return apijson.UnmarshalRoot(data, r)
}

func (r terminalOutputEventJSON) RawJSON() string {
	return r.raw
}

type TerminalOutputEventType string

const (
	TerminalOutputEventTypeOutput TerminalOutputEventType = "output"
)

func (r TerminalOutputEventType) IsKnown() bool {
	switch r {
	case TerminalOutputEventTypeOutput:
		return true
	}
	return false
}

type TerminalErrorEvent struct {
	Type         TerminalErrorEventType `json:"type" api:"required"`
	ErrorCode    string                 `json:"error_code"`
	ErrorMessage string                 `json:"error_message"`
	JSON         terminalErrorEventJSON `json:"-"`
}

// terminalErrorEventJSON contains the JSON metadata for the struct [TerminalErrorEvent]
type terminalErrorEventJSON struct {
	Type         apijson.Field
	ErrorCode    apijson.Field
	ErrorMessage apijson.Field
	raw          string
	ExtraFields  map[string]apijson.Field
}

func (r *TerminalErrorEvent) UnmarshalJSON(data []byte) (err error) {
	return apijson.UnmarshalRoot(data, r)
}

func (r terminalErrorEventJSON) RawJSON() string {
	return r.raw
}

type TerminalErrorEventType string

const (
	TerminalErrorEventTypeError TerminalErrorEventType = "error"
)

func (r TerminalErrorEventType) IsKnown() bool {
	switch r {
	case TerminalErrorEventTypeError:
		return true
	}
	return false
}

type TerminalClosedEvent struct {
	Type TerminalClosedEventType `json:"type" api:"required"`
	JSON terminalClosedEventJSON `json:"-"`
}

// terminalClosedEventJSON contains the JSON metadata for the struct [TerminalClosedEvent]
type terminalClosedEventJSON struct {
	Type        apijson.Field
	raw         string
	ExtraFields map[string]apijson.Field
}

func (r *TerminalClosedEvent) UnmarshalJSON(data []byte) (err error) {
	return apijson.UnmarshalRoot(data, r)
}

func (r terminalClosedEventJSON) RawJSON() string {
	return r.raw
}

type TerminalClosedEventType string

const (
	TerminalClosedEventTypeClosed TerminalClosedEventType = "closed"
)

func (r TerminalClosedEventType) IsKnown() bool {
	switch r {
	case TerminalClosedEventTypeClosed:
		return true
	}
	return false
}

type ConnectClientEvent struct {
	Data   string                 `json:"data"`
	Type   ConnectClientEventType `json:"type" api:"required"`
	Height int64                  `json:"height"`
	Width  int64                  `json:"width"`
	JSON   connectClientEventJSON `json:"-"`
	union  ConnectClientEventUnion
}

// connectClientEventJSON contains the JSON metadata for the struct [ConnectClientEvent]
type connectClientEventJSON struct {
	Data        apijson.Field
	Type        apijson.Field
	Height      apijson.Field
	Width       apijson.Field
	raw         string
	ExtraFields map[string]apijson.Field
}

func (r connectClientEventJSON) RawJSON() string {
	return r.raw
}

func (r *ConnectClientEvent) UnmarshalJSON(data []byte) (err error) {
	*r = ConnectClientEvent{}
	err = apijson.UnmarshalRoot(data, &r.union)
	if err != nil {
		return err
	}
	return apijson.Port(r.union, &r)
}

// AsUnion returns a [ConnectClientEventUnion] interface which you can cast to the
// specific types for more type safety.
//
// Possible runtime types of the union are [ConnectClientEventTerminalInputEvent], [ConnectClientEventTerminalResizeEvent].
func (r ConnectClientEvent) AsUnion() ConnectClientEventUnion {
	return r.union
}

// Union satisfied by [ConnectClientEventTerminalInputEvent] or [ConnectClientEventTerminalResizeEvent].
type ConnectClientEventUnion interface {
	implementsConnectClientEvent()
}

func init() {
	apijson.RegisterUnion(
		reflect.TypeOf((*ConnectClientEventUnion)(nil)).Elem(),
		"type",
		apijson.UnionVariant{
			TypeFilter:         gjson.JSON,
			Type:               reflect.TypeOf(ConnectClientEventTerminalInputEvent{}),
			DiscriminatorValue: "input",
		},
		apijson.UnionVariant{
			TypeFilter:         gjson.JSON,
			Type:               reflect.TypeOf(ConnectClientEventTerminalResizeEvent{}),
			DiscriminatorValue: "resize",
		},
	)
}

type ConnectClientEventTerminalInputEvent struct {
	Data string                                   `json:"data" api:"required"`
	Type ConnectClientEventTerminalInputEventType `json:"type" api:"required"`
	JSON connectClientEventTerminalInputEventJSON `json:"-"`
}

// connectClientEventTerminalInputEventJSON contains the JSON metadata for the struct [ConnectClientEventTerminalInputEvent]
type connectClientEventTerminalInputEventJSON struct {
	Data        apijson.Field
	Type        apijson.Field
	raw         string
	ExtraFields map[string]apijson.Field
}

func (r *ConnectClientEventTerminalInputEvent) UnmarshalJSON(data []byte) (err error) {
	return apijson.UnmarshalRoot(data, r)
}

func (r connectClientEventTerminalInputEventJSON) RawJSON() string {
	return r.raw
}

func (r ConnectClientEventTerminalInputEvent) implementsConnectClientEvent() {}

type ConnectClientEventTerminalInputEventType string

const (
	ConnectClientEventTerminalInputEventTypeInput ConnectClientEventTerminalInputEventType = "input"
)

func (r ConnectClientEventTerminalInputEventType) IsKnown() bool {
	switch r {
	case ConnectClientEventTerminalInputEventTypeInput:
		return true
	}
	return false
}

type ConnectClientEventTerminalResizeEvent struct {
	Height int64                                     `json:"height" api:"required"`
	Type   ConnectClientEventTerminalResizeEventType `json:"type" api:"required"`
	Width  int64                                     `json:"width" api:"required"`
	JSON   connectClientEventTerminalResizeEventJSON `json:"-"`
}

// connectClientEventTerminalResizeEventJSON contains the JSON metadata for the struct [ConnectClientEventTerminalResizeEvent]
type connectClientEventTerminalResizeEventJSON struct {
	Height      apijson.Field
	Type        apijson.Field
	Width       apijson.Field
	raw         string
	ExtraFields map[string]apijson.Field
}

func (r *ConnectClientEventTerminalResizeEvent) UnmarshalJSON(data []byte) (err error) {
	return apijson.UnmarshalRoot(data, r)
}

func (r connectClientEventTerminalResizeEventJSON) RawJSON() string {
	return r.raw
}

func (r ConnectClientEventTerminalResizeEvent) implementsConnectClientEvent() {}

type ConnectClientEventTerminalResizeEventType string

const (
	ConnectClientEventTerminalResizeEventTypeResize ConnectClientEventTerminalResizeEventType = "resize"
)

func (r ConnectClientEventTerminalResizeEventType) IsKnown() bool {
	switch r {
	case ConnectClientEventTerminalResizeEventTypeResize:
		return true
	}
	return false
}

type ConnectClientEventType string

const (
	ConnectClientEventTypeInput  ConnectClientEventType = "input"
	ConnectClientEventTypeResize ConnectClientEventType = "resize"
)

func (r ConnectClientEventType) IsKnown() bool {
	switch r {
	case ConnectClientEventTypeInput, ConnectClientEventTypeResize:
		return true
	}
	return false
}

type ConnectClientEventParam struct {
	Data   param.Field[string]                 `json:"data"`
	Type   param.Field[ConnectClientEventType] `json:"type" api:"required"`
	Height param.Field[int64]                  `json:"height"`
	Width  param.Field[int64]                  `json:"width"`
}

func (r ConnectClientEventParam) MarshalJSON() (data []byte, err error) {
	return apijson.MarshalRoot(r)
}

func (r ConnectClientEventParam) implementsConnectClientEventUnionParam() {}

// Satisfied by [ConnectClientEventTerminalInputEventParam], [ConnectClientEventTerminalResizeEventParam], [ConnectClientEventParam].
type ConnectClientEventUnionParam interface {
	implementsConnectClientEventUnionParam()
}

type ConnectClientEventTerminalInputEventParam struct {
	Data param.Field[string]                                   `json:"data" api:"required"`
	Type param.Field[ConnectClientEventTerminalInputEventType] `json:"type" api:"required"`
}

func (r ConnectClientEventTerminalInputEventParam) MarshalJSON() (data []byte, err error) {
	return apijson.MarshalRoot(r)
}

func (r ConnectClientEventTerminalInputEventParam) implementsConnectClientEventUnionParam() {}

type ConnectClientEventTerminalResizeEventParam struct {
	Height param.Field[int64]                                     `json:"height" api:"required"`
	Type   param.Field[ConnectClientEventTerminalResizeEventType] `json:"type" api:"required"`
	Width  param.Field[int64]                                     `json:"width" api:"required"`
}

func (r ConnectClientEventTerminalResizeEventParam) MarshalJSON() (data []byte, err error) {
	return apijson.MarshalRoot(r)
}

func (r ConnectClientEventTerminalResizeEventParam) implementsConnectClientEventUnionParam() {}

type ConnectServerEvent struct {
	Data         string                 `json:"data"`
	Type         ConnectServerEventType `json:"type" api:"required"`
	ErrorCode    string                 `json:"error_code"`
	ErrorMessage string                 `json:"error_message"`
	JSON         connectServerEventJSON `json:"-"`
	union        ConnectServerEventUnion
}

// connectServerEventJSON contains the JSON metadata for the struct [ConnectServerEvent]
type connectServerEventJSON struct {
	Data         apijson.Field
	Type         apijson.Field
	ErrorCode    apijson.Field
	ErrorMessage apijson.Field
	raw          string
	ExtraFields  map[string]apijson.Field
}

func (r connectServerEventJSON) RawJSON() string {
	return r.raw
}

func (r *ConnectServerEvent) UnmarshalJSON(data []byte) (err error) {
	*r = ConnectServerEvent{}
	err = apijson.UnmarshalRoot(data, &r.union)
	if err != nil {
		return err
	}
	return apijson.Port(r.union, &r)
}

// AsUnion returns a [ConnectServerEventUnion] interface which you can cast to the
// specific types for more type safety.
//
// Possible runtime types of the union are [ConnectServerEventTerminalOutputEvent], [ConnectServerEventTerminalErrorEvent], [ConnectServerEventTerminalClosedEvent].
func (r ConnectServerEvent) AsUnion() ConnectServerEventUnion {
	return r.union
}

// Union satisfied by [ConnectServerEventTerminalOutputEvent] or [ConnectServerEventTerminalErrorEvent] or [ConnectServerEventTerminalClosedEvent].
type ConnectServerEventUnion interface {
	implementsConnectServerEvent()
}

func init() {
	apijson.RegisterUnion(
		reflect.TypeOf((*ConnectServerEventUnion)(nil)).Elem(),
		"type",
		apijson.UnionVariant{
			TypeFilter:         gjson.JSON,
			Type:               reflect.TypeOf(ConnectServerEventTerminalOutputEvent{}),
			DiscriminatorValue: "output",
		},
		apijson.UnionVariant{
			TypeFilter:         gjson.JSON,
			Type:               reflect.TypeOf(ConnectServerEventTerminalErrorEvent{}),
			DiscriminatorValue: "error",
		},
		apijson.UnionVariant{
			TypeFilter:         gjson.JSON,
			Type:               reflect.TypeOf(ConnectServerEventTerminalClosedEvent{}),
			DiscriminatorValue: "closed",
		},
	)
}

type ConnectServerEventTerminalOutputEvent struct {
	Data string                                    `json:"data" api:"required"`
	Type ConnectServerEventTerminalOutputEventType `json:"type" api:"required"`
	JSON connectServerEventTerminalOutputEventJSON `json:"-"`
}

// connectServerEventTerminalOutputEventJSON contains the JSON metadata for the struct [ConnectServerEventTerminalOutputEvent]
type connectServerEventTerminalOutputEventJSON struct {
	Data        apijson.Field
	Type        apijson.Field
	raw         string
	ExtraFields map[string]apijson.Field
}

func (r *ConnectServerEventTerminalOutputEvent) UnmarshalJSON(data []byte) (err error) {
	return apijson.UnmarshalRoot(data, r)
}

func (r connectServerEventTerminalOutputEventJSON) RawJSON() string {
	return r.raw
}

func (r ConnectServerEventTerminalOutputEvent) implementsConnectServerEvent() {}

type ConnectServerEventTerminalOutputEventType string

const (
	ConnectServerEventTerminalOutputEventTypeOutput ConnectServerEventTerminalOutputEventType = "output"
)

func (r ConnectServerEventTerminalOutputEventType) IsKnown() bool {
	switch r {
	case ConnectServerEventTerminalOutputEventTypeOutput:
		return true
	}
	return false
}

type ConnectServerEventTerminalErrorEvent struct {
	Type         ConnectServerEventTerminalErrorEventType `json:"type" api:"required"`
	ErrorCode    string                                   `json:"error_code"`
	ErrorMessage string                                   `json:"error_message"`
	JSON         connectServerEventTerminalErrorEventJSON `json:"-"`
}

// connectServerEventTerminalErrorEventJSON contains the JSON metadata for the struct [ConnectServerEventTerminalErrorEvent]
type connectServerEventTerminalErrorEventJSON struct {
	Type         apijson.Field
	ErrorCode    apijson.Field
	ErrorMessage apijson.Field
	raw          string
	ExtraFields  map[string]apijson.Field
}

func (r *ConnectServerEventTerminalErrorEvent) UnmarshalJSON(data []byte) (err error) {
	return apijson.UnmarshalRoot(data, r)
}

func (r connectServerEventTerminalErrorEventJSON) RawJSON() string {
	return r.raw
}

func (r ConnectServerEventTerminalErrorEvent) implementsConnectServerEvent() {}

type ConnectServerEventTerminalErrorEventType string

const (
	ConnectServerEventTerminalErrorEventTypeError ConnectServerEventTerminalErrorEventType = "error"
)

func (r ConnectServerEventTerminalErrorEventType) IsKnown() bool {
	switch r {
	case ConnectServerEventTerminalErrorEventTypeError:
		return true
	}
	return false
}

type ConnectServerEventTerminalClosedEvent struct {
	Type ConnectServerEventTerminalClosedEventType `json:"type" api:"required"`
	JSON connectServerEventTerminalClosedEventJSON `json:"-"`
}

// connectServerEventTerminalClosedEventJSON contains the JSON metadata for the struct [ConnectServerEventTerminalClosedEvent]
type connectServerEventTerminalClosedEventJSON struct {
	Type        apijson.Field
	raw         string
	ExtraFields map[string]apijson.Field
}

func (r *ConnectServerEventTerminalClosedEvent) UnmarshalJSON(data []byte) (err error) {
	return apijson.UnmarshalRoot(data, r)
}

func (r connectServerEventTerminalClosedEventJSON) RawJSON() string {
	return r.raw
}

func (r ConnectServerEventTerminalClosedEvent) implementsConnectServerEvent() {}

type ConnectServerEventTerminalClosedEventType string

const (
	ConnectServerEventTerminalClosedEventTypeClosed ConnectServerEventTerminalClosedEventType = "closed"
)

func (r ConnectServerEventTerminalClosedEventType) IsKnown() bool {
	switch r {
	case ConnectServerEventTerminalClosedEventTypeClosed:
		return true
	}
	return false
}

type ConnectServerEventType string

const (
	ConnectServerEventTypeOutput ConnectServerEventType = "output"
	ConnectServerEventTypeError  ConnectServerEventType = "error"
	ConnectServerEventTypeClosed ConnectServerEventType = "closed"
)

func (r ConnectServerEventType) IsKnown() bool {
	switch r {
	case ConnectServerEventTypeOutput, ConnectServerEventTypeError, ConnectServerEventTypeClosed:
		return true
	}
	return false
}

type TerminalCreateParamsParam struct {
	Height param.Field[int64]             `json:"height" api:"required"`
	Width  param.Field[int64]             `json:"width" api:"required"`
	Cwd    param.Field[string]            `json:"cwd"`
	Env    param.Field[map[string]string] `json:"env"`
	Shell  param.Field[string]            `json:"shell"`
}

func (r TerminalCreateParamsParam) MarshalJSON() (data []byte, err error) {
	return apijson.MarshalRoot(r)
}

type MachineTerminalListParams struct {
	MachineID     string              `path:"machine_id" api:"required" json:"-"`
	Cursor        param.Field[string] `query:"cursor"`
	Limit         param.Field[int64]  `query:"limit"`
	XDedalusOrgID param.Field[string] `header:"X-Dedalus-Org-Id"`
}

// URLQuery serializes [MachineTerminalListParams]'s query parameters as `url.Values`.
func (r MachineTerminalListParams) URLQuery() (v url.Values) {
	return apiquery.MarshalWithSettings(r, apiquery.QuerySettings{
		ArrayFormat:  apiquery.ArrayQueryFormatComma,
		NestedFormat: apiquery.NestedQueryFormatBrackets,
	})
}

type MachineTerminalNewParams struct {
	MachineID            string               `path:"machine_id" api:"required" json:"-"`
	TerminalCreateParams TerminalCreateParams `json:"terminal_create_params" api:"required"`
	XDedalusOrgID        param.Field[string]  `header:"X-Dedalus-Org-Id"`
}

func (r MachineTerminalNewParams) MarshalJSON() (data []byte, err error) {
	return apijson.MarshalRoot(r.TerminalCreateParams)
}

type MachineTerminalGetParams struct {
	MachineID     string              `path:"machine_id" api:"required" json:"-"`
	TerminalID    string              `path:"terminal_id" api:"required" json:"-"`
	XDedalusOrgID param.Field[string] `header:"X-Dedalus-Org-Id"`
}

type MachineTerminalDeleteParams struct {
	MachineID     string              `path:"machine_id" api:"required" json:"-"`
	TerminalID    string              `path:"terminal_id" api:"required" json:"-"`
	XDedalusOrgID param.Field[string] `header:"X-Dedalus-Org-Id"`
}

type MachineTerminalConnectParams struct {
	// Machine identifier.
	MachineID string `path:"machine_id" api:"required" json:"-"`
	// Terminal identifier.
	TerminalID string `path:"terminal_id" api:"required" json:"-"`
	// Organization ID header applied to all DCS requests.
	XDedalusOrgID param.Field[string] `header:"X-Dedalus-Org-Id" format:"uuid"`
}
