// Code generated by Scalar SDK Generator. DO NOT EDIT.

package dedalus

import (
	"context"
	"errors"
	"fmt"
	"net/http"
	"net/url"
	"slices"
	"time"

	"github.com/dedalus-labs/dedalus-go/internal/apijson"
	"github.com/dedalus-labs/dedalus-go/internal/apiquery"
	"github.com/dedalus-labs/dedalus-go/internal/param"
	"github.com/dedalus-labs/dedalus-go/internal/requestconfig"
	"github.com/dedalus-labs/dedalus-go/option"
	"github.com/dedalus-labs/dedalus-go/packages/pagination"
)

// MachinePortService contains methods and other services that help with interacting
// with the API. You should not instantiate this service directly, and instead use
// the [NewMachinePortService] method instead.
type MachinePortService struct {
	Options []option.RequestOption
}

// NewMachinePortService generates a new service that applies the given options to each request.
// These options are applied after the parent client's options (if there is one), and
// before any request-specific options.
func NewMachinePortService(opts ...option.RequestOption) (r *MachinePortService) {
	r = &MachinePortService{}
	r.Options = opts
	return
}

// List ports
//
// Parameters:
//
//	ctx: Context for the request.
//	query: MachinePortListParams request parameters.
//	opts: Options to apply to this request.
//
// Returns:
//
//	*pagination.CursorPage[Port]: OK
//
// Example:
//
//	page, err := client.Machines.Ports.List(context.Background(), sdk.MachinePortListParams{
//		MachineID: "machineID",
//	})
//	if err != nil {
//		panic(err)
//	}
//
//	fmt.Println(page)
func (r *MachinePortService) List(ctx context.Context, query MachinePortListParams, opts ...option.RequestOption) (res *pagination.CursorPage[Port], err error) {
	var raw *http.Response
	if query.XDedalusOrgID.Present {
		opts = append(opts, option.WithHeader("X-Dedalus-Org-Id", fmt.Sprintf("%v", query.XDedalusOrgID.Value)))
	}
	opts = slices.Concat(r.Options, opts)
	opts = append([]option.RequestOption{option.WithResponseInto(&raw)}, opts...)
	if query.MachineID == "" {
		err = errors.New("missing required machine_id parameter")
		return nil, err
	}
	path := fmt.Sprintf("v1/machines/%s/ports", url.PathEscape(query.MachineID))
	cfg, err := requestconfig.NewRequestConfig(ctx, http.MethodGet, path, query, &res, opts...)
	if err != nil {
		return nil, err
	}
	err = cfg.Execute()
	if err != nil {
		return nil, err
	}
	res.SetPageConfig(cfg, raw)
	return res, nil
}

// ListAutoPaging returns an auto-pager for List.
//
// Returns:
//
//	*pagination.CursorPageAutoPager[Port]
func (r *MachinePortService) ListAutoPaging(ctx context.Context, query MachinePortListParams, opts ...option.RequestOption) *pagination.CursorPageAutoPager[Port] {
	return pagination.NewCursorPageAutoPager(r.List(ctx, query, opts...))
}

// Create port
//
// Parameters:
//
//	ctx: Context for the request.
//	body: MachinePortNewParams request parameters.
//	opts: Options to apply to this request.
//
// Returns:
//
//	*Port: OK
//
// Example:
//
//	port, err := client.Machines.Ports.New(context.Background(), sdk.MachinePortNewParams{
//		MachineID: "machineID",
//		PortCreateParams: sdk.PortCreateParams{
//			Port: sdk.F[int64](0),
//		},
//	})
//	if err != nil {
//		panic(err)
//	}
//
//	fmt.Println(port.PortID)
func (r *MachinePortService) New(ctx context.Context, body MachinePortNewParams, opts ...option.RequestOption) (res *Port, err error) {
	if body.XDedalusOrgID.Present {
		opts = append(opts, option.WithHeader("X-Dedalus-Org-Id", fmt.Sprintf("%v", body.XDedalusOrgID.Value)))
	}
	opts = slices.Concat(r.Options, opts)
	if body.MachineID == "" {
		err = errors.New("missing required machine_id parameter")
		return nil, err
	}
	path := fmt.Sprintf("v1/machines/%s/ports", url.PathEscape(body.MachineID))
	err = requestconfig.ExecuteNewRequest(ctx, http.MethodPost, path, body, &res, opts...)
	return res, err
}

// Get port
//
// Parameters:
//
//	ctx: Context for the request.
//	params: MachinePortGetParams request parameters.
//	opts: Options to apply to this request.
//
// Returns:
//
//	*Port: OK
//
// Example:
//
//	port, err := client.Machines.Ports.Get(context.Background(), sdk.MachinePortGetParams{
//		MachineID: "machineID",
//		PortID:    "portID",
//	})
//	if err != nil {
//		panic(err)
//	}
//
//	fmt.Println(port.PortID)
func (r *MachinePortService) Get(ctx context.Context, params MachinePortGetParams, opts ...option.RequestOption) (res *Port, err error) {
	if params.XDedalusOrgID.Present {
		opts = append(opts, option.WithHeader("X-Dedalus-Org-Id", fmt.Sprintf("%v", params.XDedalusOrgID.Value)))
	}
	opts = slices.Concat(r.Options, opts)
	if params.MachineID == "" {
		err = errors.New("missing required machine_id parameter")
		return nil, err
	}
	if params.PortID == "" {
		err = errors.New("missing required port_id parameter")
		return nil, err
	}
	path := fmt.Sprintf("v1/machines/%s/ports/%s", url.PathEscape(params.MachineID), url.PathEscape(params.PortID))
	err = requestconfig.ExecuteNewRequest(ctx, http.MethodGet, path, nil, &res, opts...)
	return res, err
}

// Delete port
//
// Parameters:
//
//	ctx: Context for the request.
//	params: MachinePortDeleteParams request parameters.
//	opts: Options to apply to this request.
//
// Returns:
//
//	*Port: OK
//
// Example:
//
//	port, err := client.Machines.Ports.Delete(context.Background(), sdk.MachinePortDeleteParams{
//		MachineID: "machineID",
//		PortID:    "portID",
//	})
//	if err != nil {
//		panic(err)
//	}
//
//	fmt.Println(port.PortID)
func (r *MachinePortService) Delete(ctx context.Context, params MachinePortDeleteParams, opts ...option.RequestOption) (res *Port, err error) {
	if params.XDedalusOrgID.Present {
		opts = append(opts, option.WithHeader("X-Dedalus-Org-Id", fmt.Sprintf("%v", params.XDedalusOrgID.Value)))
	}
	opts = slices.Concat(r.Options, opts)
	if params.MachineID == "" {
		err = errors.New("missing required machine_id parameter")
		return nil, err
	}
	if params.PortID == "" {
		err = errors.New("missing required port_id parameter")
		return nil, err
	}
	path := fmt.Sprintf("v1/machines/%s/ports/%s", url.PathEscape(params.MachineID), url.PathEscape(params.PortID))
	err = requestconfig.ExecuteNewRequest(ctx, http.MethodDelete, path, nil, &res, opts...)
	return res, err
}

type PortCreateParams struct {
	Port     param.Field[int64]                    `json:"port" api:"required"`
	Protocol param.Field[PortCreateParamsProtocol] `json:"protocol"`
}

func (r PortCreateParams) MarshalJSON() (data []byte, err error) {
	return apijson.MarshalRoot(r)
}

type PortCreateParamsProtocol string

const (
	PortCreateParamsProtocolHTTP  PortCreateParamsProtocol = "http"
	PortCreateParamsProtocolHTTPS PortCreateParamsProtocol = "https"
)

func (r PortCreateParamsProtocol) IsKnown() bool {
	switch r {
	case PortCreateParamsProtocolHTTP, PortCreateParamsProtocolHTTPS:
		return true
	}
	return false
}

type Port struct {
	CreatedAt    time.Time    `json:"created_at" api:"required" format:"date-time"`
	MachineID    string       `json:"machine_id" api:"required"`
	Port         int64        `json:"port" api:"required"`
	PortID       string       `json:"port_id" api:"required"`
	Status       PortStatus   `json:"status" api:"required"`
	ErrorCode    string       `json:"error_code"`
	ErrorMessage string       `json:"error_message"`
	ExpiresAt    time.Time    `json:"expires_at" format:"date-time"`
	Protocol     PortProtocol `json:"protocol"`
	ReadyAt      time.Time    `json:"ready_at" format:"date-time"`
	RetryAfterMs int64        `json:"retry_after_ms"`
	URL          string       `json:"url"`
	JSON         portJSON     `json:"-"`
}

// portJSON contains the JSON metadata for the struct [Port]
type portJSON struct {
	CreatedAt    apijson.Field
	MachineID    apijson.Field
	Port         apijson.Field
	PortID       apijson.Field
	Status       apijson.Field
	ErrorCode    apijson.Field
	ErrorMessage apijson.Field
	ExpiresAt    apijson.Field
	Protocol     apijson.Field
	ReadyAt      apijson.Field
	RetryAfterMs apijson.Field
	URL          apijson.Field
	raw          string
	ExtraFields  map[string]apijson.Field
}

func (r *Port) UnmarshalJSON(data []byte) (err error) {
	return apijson.UnmarshalRoot(data, r)
}

func (r portJSON) RawJSON() string {
	return r.raw
}

type PortProtocol string

const (
	PortProtocolHTTP  PortProtocol = "http"
	PortProtocolHTTPS PortProtocol = "https"
)

func (r PortProtocol) IsKnown() bool {
	switch r {
	case PortProtocolHTTP, PortProtocolHTTPS:
		return true
	}
	return false
}

type PortStatus string

const (
	PortStatusWakeInProgress PortStatus = "wake_in_progress"
	PortStatusReady          PortStatus = "ready"
	PortStatusClosed         PortStatus = "closed"
	PortStatusExpired        PortStatus = "expired"
	PortStatusFailed         PortStatus = "failed"
)

func (r PortStatus) IsKnown() bool {
	switch r {
	case PortStatusWakeInProgress, PortStatusReady, PortStatusClosed, PortStatusExpired, PortStatusFailed:
		return true
	}
	return false
}

type PortList struct {
	Items      []Port       `json:"items" api:"required,nullable"`
	NextCursor string       `json:"next_cursor"`
	JSON       portListJSON `json:"-"`
}

// portListJSON contains the JSON metadata for the struct [PortList]
type portListJSON struct {
	Items       apijson.Field
	NextCursor  apijson.Field
	raw         string
	ExtraFields map[string]apijson.Field
}

func (r *PortList) UnmarshalJSON(data []byte) (err error) {
	return apijson.UnmarshalRoot(data, r)
}

func (r portListJSON) RawJSON() string {
	return r.raw
}

type PortCreateParamsParam struct {
	Port     param.Field[int64]                    `json:"port" api:"required"`
	Protocol param.Field[PortCreateParamsProtocol] `json:"protocol"`
}

func (r PortCreateParamsParam) MarshalJSON() (data []byte, err error) {
	return apijson.MarshalRoot(r)
}

type MachinePortListParams struct {
	MachineID     string              `path:"machine_id" api:"required" json:"-"`
	Cursor        param.Field[string] `query:"cursor"`
	Limit         param.Field[int64]  `query:"limit"`
	XDedalusOrgID param.Field[string] `header:"X-Dedalus-Org-Id"`
}

// URLQuery serializes [MachinePortListParams]'s query parameters as `url.Values`.
func (r MachinePortListParams) URLQuery() (v url.Values) {
	return apiquery.MarshalWithSettings(r, apiquery.QuerySettings{
		ArrayFormat:  apiquery.ArrayQueryFormatComma,
		NestedFormat: apiquery.NestedQueryFormatBrackets,
	})
}

type MachinePortNewParams struct {
	MachineID        string              `path:"machine_id" api:"required" json:"-"`
	PortCreateParams PortCreateParams    `json:"port_create_params" api:"required"`
	XDedalusOrgID    param.Field[string] `header:"X-Dedalus-Org-Id"`
}

func (r MachinePortNewParams) MarshalJSON() (data []byte, err error) {
	return apijson.MarshalRoot(r.PortCreateParams)
}

type MachinePortGetParams struct {
	MachineID     string              `path:"machine_id" api:"required" json:"-"`
	PortID        string              `path:"port_id" api:"required" json:"-"`
	XDedalusOrgID param.Field[string] `header:"X-Dedalus-Org-Id"`
}

type MachinePortDeleteParams struct {
	MachineID     string              `path:"machine_id" api:"required" json:"-"`
	PortID        string              `path:"port_id" api:"required" json:"-"`
	XDedalusOrgID param.Field[string] `header:"X-Dedalus-Org-Id"`
}
