// Code generated by Scalar SDK Generator. DO NOT EDIT.

package dedalus

import (
	"context"
	"errors"
	"fmt"
	"net/http"
	"net/url"
	"slices"

	"github.com/dedalus-labs/dedalus-go/internal/apijson"
	"github.com/dedalus-labs/dedalus-go/internal/param"
	"github.com/dedalus-labs/dedalus-go/internal/requestconfig"
	"github.com/dedalus-labs/dedalus-go/option"
)

// NetworkService contains methods and other services that help with interacting
// with the API. You should not instantiate this service directly, and instead use
// the [NewNetworkService] method instead.
type NetworkService struct {
	Options []option.RequestOption
}

// NewNetworkService generates a new service that applies the given options to each request.
// These options are applied after the parent client's options (if there is one), and
// before any request-specific options.
func NewNetworkService(opts ...option.RequestOption) (r *NetworkService) {
	r = &NetworkService{}
	r.Options = opts
	return
}

// Get network details
//
// Parameters:
//
//	ctx: Context for the request.
//	params: NetworkGetParams request parameters.
//	opts: Options to apply to this request.
//
// Returns:
//
//	*Network: OK
//
// Example:
//
//	network, err := client.Networks.Get(context.Background(), sdk.NetworkGetParams{
//		NetworkID: "networkID",
//	})
//	if err != nil {
//		panic(err)
//	}
//
//	fmt.Println(network)
func (r *NetworkService) Get(ctx context.Context, params NetworkGetParams, opts ...option.RequestOption) (res *Network, err error) {
	if params.XDedalusOrgID.Present {
		opts = append(opts, option.WithHeader("X-Dedalus-Org-Id", fmt.Sprintf("%v", params.XDedalusOrgID.Value)))
	}
	opts = slices.Concat(r.Options, opts)
	if params.NetworkID == "" {
		err = errors.New("missing required network_id parameter")
		return nil, err
	}
	path := fmt.Sprintf("v1/networks/%s", url.PathEscape(params.NetworkID))
	err = requestconfig.ExecuteNewRequest(ctx, http.MethodGet, path, nil, &res, opts...)
	return res, err
}

type Network struct {
	Gateways  []NetworkGateway `json:"gateways" api:"required,nullable"`
	Name      string           `json:"name" api:"required"`
	NetworkID string           `json:"network_id" api:"required"`
	JSON      networkJSON      `json:"-"`
}

// networkJSON contains the JSON metadata for the struct [Network]
type networkJSON struct {
	Gateways    apijson.Field
	Name        apijson.Field
	NetworkID   apijson.Field
	raw         string
	ExtraFields map[string]apijson.Field
}

func (r *Network) UnmarshalJSON(data []byte) (err error) {
	return apijson.UnmarshalRoot(data, r)
}

func (r networkJSON) RawJSON() string {
	return r.raw
}

type NetworkGateway struct {
	Hostname string                 `json:"hostname" api:"required"`
	Kind     NetworkGatewayKind     `json:"kind" api:"required"`
	Protocol NetworkGatewayProtocol `json:"protocol" api:"required"`
	Port     int64                  `json:"port"`
	JSON     networkGatewayJSON     `json:"-"`
}

// networkGatewayJSON contains the JSON metadata for the struct [NetworkGateway]
type networkGatewayJSON struct {
	Hostname    apijson.Field
	Kind        apijson.Field
	Protocol    apijson.Field
	Port        apijson.Field
	raw         string
	ExtraFields map[string]apijson.Field
}

func (r *NetworkGateway) UnmarshalJSON(data []byte) (err error) {
	return apijson.UnmarshalRoot(data, r)
}

func (r networkGatewayJSON) RawJSON() string {
	return r.raw
}

type NetworkGatewayKind string

const (
	NetworkGatewayKindSSH  NetworkGatewayKind = "ssh"
	NetworkGatewayKindPort NetworkGatewayKind = "port"
)

func (r NetworkGatewayKind) IsKnown() bool {
	switch r {
	case NetworkGatewayKindSSH, NetworkGatewayKindPort:
		return true
	}
	return false
}

type NetworkGatewayProtocol string

const (
	NetworkGatewayProtocolSSH   NetworkGatewayProtocol = "ssh"
	NetworkGatewayProtocolHTTPS NetworkGatewayProtocol = "https"
)

func (r NetworkGatewayProtocol) IsKnown() bool {
	switch r {
	case NetworkGatewayProtocolSSH, NetworkGatewayProtocolHTTPS:
		return true
	}
	return false
}

type NetworkGetParams struct {
	NetworkID     string              `path:"network_id" api:"required" json:"-"`
	XDedalusOrgID param.Field[string] `header:"X-Dedalus-Org-Id"`
}
