// Code generated by Scalar SDK Generator. DO NOT EDIT.

package dedalus

import (
	"github.com/dedalus-labs/dedalus-go/option"
)

// OrganizationService contains methods and other services that help with interacting
// with the API. You should not instantiate this service directly, and instead use
// the [NewOrganizationService] method instead.
type OrganizationService struct {
	Options      []option.RequestOption
	Autoresizing *OrganizationAutoresizingService
}

// NewOrganizationService generates a new service that applies the given options to each request.
// These options are applied after the parent client's options (if there is one), and
// before any request-specific options.
func NewOrganizationService(opts ...option.RequestOption) (r *OrganizationService) {
	r = &OrganizationService{}
	r.Options = opts
	r.Autoresizing = NewOrganizationAutoresizingService(opts...)
	return
}
