// Code generated by Scalar SDK Generator. DO NOT EDIT.

package dedalus

import (
	"context"
	"net/http"
	"slices"

	"github.com/dedalus-labs/dedalus-go/internal/apijson"
	"github.com/dedalus-labs/dedalus-go/internal/param"
	"github.com/dedalus-labs/dedalus-go/internal/requestconfig"
	"github.com/dedalus-labs/dedalus-go/option"
)

// OrganizationAutoresizingService contains methods and other services that help with interacting
// with the API. You should not instantiate this service directly, and instead use
// the [NewOrganizationAutoresizingService] method instead.
type OrganizationAutoresizingService struct {
	Options []option.RequestOption
}

// NewOrganizationAutoresizingService generates a new service that applies the given options to each request.
// These options are applied after the parent client's options (if there is one), and
// before any request-specific options.
func NewOrganizationAutoresizingService(opts ...option.RequestOption) (r *OrganizationAutoresizingService) {
	r = &OrganizationAutoresizingService{}
	r.Options = opts
	return
}

// Read organization RAM autoresizing policy
//
// Parameters:
//
//	ctx: Context for the request.
//	opts: Options to apply to this request.
//
// Returns:
//
//	*Policy: OK
//
// Example:
//
//	autoresizing, err := client.Organization.Autoresizing.Get(context.Background())
//	if err != nil {
//		panic(err)
//	}
//
//	fmt.Println(autoresizing)
func (r *OrganizationAutoresizingService) Get(ctx context.Context, opts ...option.RequestOption) (res *Policy, err error) {
	opts = slices.Concat(r.Options, opts)
	path := "v1/organization/autoresizing"
	err = requestconfig.ExecuteNewRequest(ctx, http.MethodGet, path, nil, &res, opts...)
	return res, err
}

// Set organization RAM autoresizing policy
//
// Parameters:
//
//	ctx: Context for the request.
//	body: OrganizationAutoresizingUpdateParams request parameters.
//	opts: Options to apply to this request.
//
// Returns:
//
//	*Policy: OK
//
// Example:
//
//	autoresizing, err := client.Organization.Autoresizing.Update(context.Background(), sdk.OrganizationAutoresizingUpdateParams{
//		Policy: sdk.PolicyParam{
//			Enabled: sdk.F[bool](false),
//		},
//	})
//	if err != nil {
//		panic(err)
//	}
//
//	fmt.Println(autoresizing)
func (r *OrganizationAutoresizingService) Update(ctx context.Context, body OrganizationAutoresizingUpdateParams, opts ...option.RequestOption) (res *Policy, err error) {
	opts = slices.Concat(r.Options, opts)
	path := "v1/organization/autoresizing"
	err = requestconfig.ExecuteNewRequest(ctx, http.MethodPut, path, body, &res, opts...)
	return res, err
}

type Policy struct {
	// Allow automatic RAM increases for all organization machines. Disabling preserves
	// applied RAM and already admitted resizes.
	Enabled bool       `json:"enabled" api:"required"`
	JSON    policyJSON `json:"-"`
}

// policyJSON contains the JSON metadata for the struct [Policy]
type policyJSON struct {
	Enabled     apijson.Field
	raw         string
	ExtraFields map[string]apijson.Field
}

func (r *Policy) UnmarshalJSON(data []byte) (err error) {
	return apijson.UnmarshalRoot(data, r)
}

func (r policyJSON) RawJSON() string {
	return r.raw
}

type PolicyParam struct {
	// Allow automatic RAM increases for all organization machines. Disabling preserves
	// applied RAM and already admitted resizes.
	Enabled param.Field[bool] `json:"enabled" api:"required"`
}

func (r PolicyParam) MarshalJSON() (data []byte, err error) {
	return apijson.MarshalRoot(r)
}

type OrganizationAutoresizingUpdateParams struct {
	Policy PolicyParam `json:"policy" api:"required"`
}

func (r OrganizationAutoresizingUpdateParams) MarshalJSON() (data []byte, err error) {
	return apijson.MarshalRoot(r.Policy)
}
