// Code generated by Scalar SDK Generator. DO NOT EDIT.

package dedalus

import (
	"context"
	"net/http"
	"net/url"
	"slices"
	"time"

	"github.com/dedalus-labs/dedalus-go/internal/apijson"
	"github.com/dedalus-labs/dedalus-go/internal/apiquery"
	"github.com/dedalus-labs/dedalus-go/internal/param"
	"github.com/dedalus-labs/dedalus-go/internal/requestconfig"
	"github.com/dedalus-labs/dedalus-go/option"
)

// UsageService contains methods and other services that help with interacting
// with the API. You should not instantiate this service directly, and instead use
// the [NewUsageService] method instead.
type UsageService struct {
	Options []option.RequestOption
}

// NewUsageService generates a new service that applies the given options to each request.
// These options are applied after the parent client's options (if there is one), and
// before any request-specific options.
func NewUsageService(opts ...option.RequestOption) (r *UsageService) {
	r = &UsageService{}
	r.Options = opts
	return
}

// Get usage summary
//
// Parameters:
//
//	ctx: Context for the request.
//	query: UsageGetParams request parameters.
//	opts: Options to apply to this request.
//
// Returns:
//
//	*OrgUsage: OK
//
// Example:
//
//	usage, err := client.Usage.Get(context.Background(), sdk.UsageGetParams{})
//	if err != nil {
//		panic(err)
//	}
//
//	fmt.Println(usage)
func (r *UsageService) Get(ctx context.Context, query UsageGetParams, opts ...option.RequestOption) (res *OrgUsage, err error) {
	opts = slices.Concat(r.Options, opts)
	path := "v1/usage"
	err = requestconfig.ExecuteNewRequest(ctx, http.MethodGet, path, query, &res, opts...)
	return res, err
}

// List machine compute usage breakdown
//
// Parameters:
//
//	ctx: Context for the request.
//	query: UsageMachineComputeParams request parameters.
//	opts: Options to apply to this request.
//
// Returns:
//
//	*MachineComputeUsage: OK
//
// Example:
//
//	usage, err := client.Usage.MachineCompute(context.Background(), sdk.UsageMachineComputeParams{})
//	if err != nil {
//		panic(err)
//	}
//
//	fmt.Println(usage)
func (r *UsageService) MachineCompute(ctx context.Context, query UsageMachineComputeParams, opts ...option.RequestOption) (res *MachineComputeUsage, err error) {
	opts = slices.Concat(r.Options, opts)
	path := "v1/usage/machines/compute"
	err = requestconfig.ExecuteNewRequest(ctx, http.MethodGet, path, query, &res, opts...)
	return res, err
}

// List machine storage usage breakdown
//
// Parameters:
//
//	ctx: Context for the request.
//	query: UsageMachineStorageParams request parameters.
//	opts: Options to apply to this request.
//
// Returns:
//
//	*MachineStorageUsage: OK
//
// Example:
//
//	usage, err := client.Usage.MachineStorage(context.Background(), sdk.UsageMachineStorageParams{})
//	if err != nil {
//		panic(err)
//	}
//
//	fmt.Println(usage)
func (r *UsageService) MachineStorage(ctx context.Context, query UsageMachineStorageParams, opts ...option.RequestOption) (res *MachineStorageUsage, err error) {
	opts = slices.Concat(r.Options, opts)
	path := "v1/usage/machines/storage"
	err = requestconfig.ExecuteNewRequest(ctx, http.MethodGet, path, query, &res, opts...)
	return res, err
}

type OrgUsage struct {
	// Closed awake seconds in billed org buckets for the period.
	BilledAwakeSeconds int64 `json:"billed_awake_seconds" api:"required"`
	// Closed requested vCPU millicores multiplied by guest-owned active CPU seconds
	// for the period.
	BilledCPUMillicoreSeconds int64 `json:"billed_cpu_millicore_seconds" api:"required"`
	// Closed billable logical MiB-seconds for the period.
	BilledLogicalStorageMibSeconds int64 `json:"billed_logical_storage_mib_seconds" api:"required"`
	// Closed requested memory MiB multiplied by running allocation seconds for the
	// period.
	BilledMemoryMibSeconds int64 `json:"billed_memory_mib_seconds" api:"required"`
	// Plan-included storage in GiB, used as a local guardrail only.
	IncludedStorageGib int64 `json:"included_storage_gib" api:"required"`
	// Billing plan in effect for the organization.
	PlanSlug string `json:"plan_slug" api:"required"`
	// Current provisioned storage summed across machines in GiB.
	ProvisionedStorageGib int64        `json:"provisioned_storage_gib" api:"required"`
	JSON                  orgUsageJSON `json:"-"`
}

// orgUsageJSON contains the JSON metadata for the struct [OrgUsage]
type orgUsageJSON struct {
	BilledAwakeSeconds             apijson.Field
	BilledCPUMillicoreSeconds      apijson.Field
	BilledLogicalStorageMibSeconds apijson.Field
	BilledMemoryMibSeconds         apijson.Field
	IncludedStorageGib             apijson.Field
	PlanSlug                       apijson.Field
	ProvisionedStorageGib          apijson.Field
	raw                            string
	ExtraFields                    map[string]apijson.Field
}

func (r *OrgUsage) UnmarshalJSON(data []byte) (err error) {
	return apijson.UnmarshalRoot(data, r)
}

func (r orgUsageJSON) RawJSON() string {
	return r.raw
}

type MachineComputeUsage struct {
	// Usage breakdown granularity used for rows: hour or day.
	Granularity string `json:"granularity" api:"required"`
	// Exclusive usage period end.
	PeriodEnd time.Time `json:"period_end" api:"required" format:"date-time"`
	// Inclusive usage period start.
	PeriodStart time.Time `json:"period_start" api:"required" format:"date-time"`
	// Machine-level compute usage breakdown rows.
	Rows []MachineComputeUsageRow `json:"rows" api:"required,nullable"`
	JSON machineComputeUsageJSON  `json:"-"`
}

// machineComputeUsageJSON contains the JSON metadata for the struct [MachineComputeUsage]
type machineComputeUsageJSON struct {
	Granularity apijson.Field
	PeriodEnd   apijson.Field
	PeriodStart apijson.Field
	Rows        apijson.Field
	raw         string
	ExtraFields map[string]apijson.Field
}

func (r *MachineComputeUsage) UnmarshalJSON(data []byte) (err error) {
	return apijson.UnmarshalRoot(data, r)
}

func (r machineComputeUsageJSON) RawJSON() string {
	return r.raw
}

type MachineComputeUsageRow struct {
	// Machine-awake seconds in this bucket.
	AwakeSeconds int64 `json:"awake_seconds" api:"required"`
	// Exclusive usage bucket end.
	BucketEnd time.Time `json:"bucket_end" api:"required" format:"date-time"`
	// Inclusive usage bucket start.
	BucketStart time.Time `json:"bucket_start" api:"required" format:"date-time"`
	// Requested vCPU millicores multiplied by guest-owned active CPU seconds.
	CPUMillicoreSeconds int64 `json:"cpu_millicore_seconds" api:"required"`
	// Latest raw window_end represented by this row.
	LastWindowEnd time.Time `json:"last_window_end" api:"required" format:"date-time"`
	// Machine identifier.
	MachineID string `json:"machine_id" api:"required"`
	// Requested memory MiB multiplied by running allocation seconds.
	MemoryMibSeconds int64 `json:"memory_mib_seconds" api:"required"`
	// Org compute bucket IDs this row contributes to.
	OrgMeteringBucketIDs []string `json:"org_metering_bucket_ids" api:"required,nullable"`
	// Requested memory for this shape, in MiB.
	RequestedMemoryMib int64 `json:"requested_memory_mib" api:"required"`
	// Requested storage for this shape, in GiB.
	RequestedStorageGib int64 `json:"requested_storage_gib" api:"required"`
	// Requested vCPU for this shape.
	RequestedVcpu float64 `json:"requested_vcpu" api:"required"`
	// Stable fingerprint for the requested machine shape.
	SpecFingerprint string `json:"spec_fingerprint" api:"required"`
	// Raw metering events compacted into this row.
	WindowCount int64 `json:"window_count" api:"required"`
	// Latest meter emission timestamp for linked org buckets, when emitted.
	LatestMeterEmittedAt time.Time                  `json:"latest_meter_emitted_at" format:"date-time"`
	JSON                 machineComputeUsageRowJSON `json:"-"`
}

// machineComputeUsageRowJSON contains the JSON metadata for the struct [MachineComputeUsageRow]
type machineComputeUsageRowJSON struct {
	AwakeSeconds         apijson.Field
	BucketEnd            apijson.Field
	BucketStart          apijson.Field
	CPUMillicoreSeconds  apijson.Field
	LastWindowEnd        apijson.Field
	MachineID            apijson.Field
	MemoryMibSeconds     apijson.Field
	OrgMeteringBucketIDs apijson.Field
	RequestedMemoryMib   apijson.Field
	RequestedStorageGib  apijson.Field
	RequestedVcpu        apijson.Field
	SpecFingerprint      apijson.Field
	WindowCount          apijson.Field
	LatestMeterEmittedAt apijson.Field
	raw                  string
	ExtraFields          map[string]apijson.Field
}

func (r *MachineComputeUsageRow) UnmarshalJSON(data []byte) (err error) {
	return apijson.UnmarshalRoot(data, r)
}

func (r machineComputeUsageRowJSON) RawJSON() string {
	return r.raw
}

type MachineStorageUsage struct {
	// Exclusive usage period end.
	PeriodEnd time.Time `json:"period_end" api:"required" format:"date-time"`
	// Inclusive usage period start.
	PeriodStart time.Time `json:"period_start" api:"required" format:"date-time"`
	// Machine-level storage usage breakdown rows.
	Rows []MachineStorageUsageRow `json:"rows" api:"required,nullable"`
	JSON machineStorageUsageJSON  `json:"-"`
}

// machineStorageUsageJSON contains the JSON metadata for the struct [MachineStorageUsage]
type machineStorageUsageJSON struct {
	PeriodEnd   apijson.Field
	PeriodStart apijson.Field
	Rows        apijson.Field
	raw         string
	ExtraFields map[string]apijson.Field
}

func (r *MachineStorageUsage) UnmarshalJSON(data []byte) (err error) {
	return apijson.UnmarshalRoot(data, r)
}

func (r machineStorageUsageJSON) RawJSON() string {
	return r.raw
}

type MachineStorageUsageRow struct {
	// Exclusive usage bucket end.
	BucketEnd time.Time `json:"bucket_end" api:"required" format:"date-time"`
	// Inclusive usage bucket start.
	BucketStart time.Time `json:"bucket_start" api:"required" format:"date-time"`
	// Machine logical bytes observed for storage allocation.
	LogicalStorageBytes int64 `json:"logical_storage_bytes" api:"required"`
	// Machine identifier.
	MachineID string `json:"machine_id" api:"required"`
	// Org storage bucket ID this row contributes to.
	OrgMeteringBucketID string `json:"org_metering_bucket_id" api:"required"`
	// Allocated logical MiB-seconds for this machine.
	StorageMibSeconds int64 `json:"storage_mib_seconds" api:"required"`
	// Latest meter emission timestamp for the linked org bucket, when emitted.
	LatestMeterEmittedAt time.Time                  `json:"latest_meter_emitted_at" format:"date-time"`
	JSON                 machineStorageUsageRowJSON `json:"-"`
}

// machineStorageUsageRowJSON contains the JSON metadata for the struct [MachineStorageUsageRow]
type machineStorageUsageRowJSON struct {
	BucketEnd            apijson.Field
	BucketStart          apijson.Field
	LogicalStorageBytes  apijson.Field
	MachineID            apijson.Field
	OrgMeteringBucketID  apijson.Field
	StorageMibSeconds    apijson.Field
	LatestMeterEmittedAt apijson.Field
	raw                  string
	ExtraFields          map[string]apijson.Field
}

func (r *MachineStorageUsageRow) UnmarshalJSON(data []byte) (err error) {
	return apijson.UnmarshalRoot(data, r)
}

func (r machineStorageUsageRowJSON) RawJSON() string {
	return r.raw
}

type UsageGetParams struct {
	// Billing period start (YYYY-MM-DD). Defaults to first of current month.
	PeriodStart param.Field[string] `query:"period_start"`
}

// URLQuery serializes [UsageGetParams]'s query parameters as `url.Values`.
func (r UsageGetParams) URLQuery() (v url.Values) {
	return apiquery.MarshalWithSettings(r, apiquery.QuerySettings{
		ArrayFormat:  apiquery.ArrayQueryFormatComma,
		NestedFormat: apiquery.NestedQueryFormatBrackets,
	})
}

type UsageMachineComputeParams struct {
	// Usage breakdown granularity: hour or day. Defaults to hour.
	Granularity param.Field[string] `query:"granularity"`
	// Optional machine ID filter.
	MachineID param.Field[string] `query:"machine_id"`
	// Last UTC usage date to include (YYYY-MM-DD). Defaults to current time.
	PeriodEnd param.Field[string] `query:"period_end"`
	// Usage period start (YYYY-MM-DD). Defaults to first of current month.
	PeriodStart param.Field[string] `query:"period_start"`
}

// URLQuery serializes [UsageMachineComputeParams]'s query parameters as `url.Values`.
func (r UsageMachineComputeParams) URLQuery() (v url.Values) {
	return apiquery.MarshalWithSettings(r, apiquery.QuerySettings{
		ArrayFormat:  apiquery.ArrayQueryFormatComma,
		NestedFormat: apiquery.NestedQueryFormatBrackets,
	})
}

type UsageMachineStorageParams struct {
	// Optional machine ID filter.
	MachineID param.Field[string] `query:"machine_id"`
	// Last UTC usage date to include (YYYY-MM-DD). Defaults to current time.
	PeriodEnd param.Field[string] `query:"period_end"`
	// Usage period start (YYYY-MM-DD). Defaults to first of current month.
	PeriodStart param.Field[string] `query:"period_start"`
}

// URLQuery serializes [UsageMachineStorageParams]'s query parameters as `url.Values`.
func (r UsageMachineStorageParams) URLQuery() (v url.Values) {
	return apiquery.MarshalWithSettings(r, apiquery.QuerySettings{
		ArrayFormat:  apiquery.ArrayQueryFormatComma,
		NestedFormat: apiquery.NestedQueryFormatBrackets,
	})
}
