// Code generated by Scalar SDK Generator. DO NOT EDIT.

package main

import (
	"context"
	"encoding/json"
	"fmt"
	"os"
	"strconv"
	"strings"
	"sync"
	"time"

	sdk "github.com/dedalus-labs/dedalus-go"
	"github.com/dedalus-labs/dedalus-go/option"
)

// Smoke test: calls every generated operation once to confirm the SDK can reach each endpoint.
// Run it from this repo with `go run tests/smoke-test.go`. The generator also runs this file
// against a mock server and reads the JSON report produced via SCALAR_SMOKE_REPORT.
var client = sdk.NewClient(option.WithAPIKey("test"), option.WithXAPIKey("test"), option.WithAsBaseURL("test"), option.WithDedalusOrgID("test"), option.WithProvider("test"), option.WithProviderKey("test"), option.WithProviderModel("test"), option.WithHeader("x-api-key", "test"), option.WithHeader("Authorization", "Bearer test"), option.WithHeader("Authorization", "Bearer test"), option.WithMaxRetries(2), option.WithRequestTimeout(10*time.Second))

type smokeResult struct {
	Operation  string `json:"operation"`
	Method     string `json:"method"`
	Path       string `json:"path"`
	Label      string `json:"label,omitempty"`
	Status     string `json:"status"`
	DurationMs int64  `json:"durationMs"`
	Error      string `json:"error,omitempty"`
}

// Label says which of an operation's two calls this is — "required params" or "all params".
// It is empty when the operation contributed a single case.
type smokeCase struct {
	Operation string
	Method    string
	Path      string
	Label     string
	Run       func()
}

func _smokeCase0() {
	page, err := client.Machines.List(context.Background(), sdk.MachineListParams{})
	if err != nil {
		panic(err)
	}

	fmt.Println(page)
}

func _smokeCase1() {
	machine, err := client.Machines.New(context.Background(), sdk.MachineNewParams{
		CreateParams: sdk.CreateParams{
			Autosleep:  sdk.F[string]("300s"),
			MemoryMib:  sdk.F[int64](4096),
			StorageGib: sdk.F[int64](10),
			Vcpu:       sdk.F[float64](1),
		},
	})
	if err != nil {
		panic(err)
	}

	fmt.Println(machine.MachineID)
}

func _smokeCase2() {
	machine, err := client.Machines.Get(context.Background(), sdk.MachineGetParams{
		MachineID: "017f22e2-79b0-7cc3-98c4-dc0c0c07398f",
	})
	if err != nil {
		panic(err)
	}

	fmt.Println(machine.MachineID)
}

func _smokeCase3() {
	machine, err := client.Machines.Update(context.Background(), sdk.MachineUpdateParams{
		MachineID:    "017f22e2-79b0-7cc3-98c4-dc0c0c07398f",
		UpdateParams: sdk.UpdateParams{},
	})
	if err != nil {
		panic(err)
	}

	fmt.Println(machine.MachineID)
}

func _smokeCase4() {
	machine, err := client.Machines.Update(context.Background(), sdk.MachineUpdateParams{
		MachineID: "017f22e2-79b0-7cc3-98c4-dc0c0c07398f",
		UpdateParams: sdk.UpdateParams{
			Autosleep:  sdk.F[string](""),
			MemoryMib:  sdk.F[int64](0),
			StorageGib: sdk.F[int64](0),
			Vcpu:       sdk.F[float64](0),
		},
	})
	if err != nil {
		panic(err)
	}

	fmt.Println(machine.MachineID)
}

func _smokeCase5() {
	machine, err := client.Machines.Delete(context.Background(), sdk.MachineDeleteParams{
		MachineID: "017f22e2-79b0-7cc3-98c4-dc0c0c07398f",
	})
	if err != nil {
		panic(err)
	}

	fmt.Println(machine.MachineID)
}

func _smokeCase6() {
	machine, err := client.Machines.Sleep(context.Background(), sdk.MachineSleepParams{
		MachineID: "017f22e2-79b0-7cc3-98c4-dc0c0c07398f",
	})
	if err != nil {
		panic(err)
	}

	fmt.Println(machine.MachineID)
}

func _smokeCase7() {
	machine, err := client.Machines.Wake(context.Background(), sdk.MachineWakeParams{
		MachineID: "017f22e2-79b0-7cc3-98c4-dc0c0c07398f",
	})
	if err != nil {
		panic(err)
	}

	fmt.Println(machine.MachineID)
}

func _smokeCase8() {
	page, err := client.Machines.SSH.List(context.Background(), sdk.MachineSSHListParams{
		MachineID: "017f22e2-79b0-7cc3-98c4-dc0c0c07398f",
	})
	if err != nil {
		panic(err)
	}

	fmt.Println(page)
}

func _smokeCase9() {
	ssh, err := client.Machines.SSH.New(context.Background(), sdk.MachineSSHNewParams{
		MachineID: "017f22e2-79b0-7cc3-98c4-dc0c0c07398f",
		SSHSessionCreateParams: sdk.SSHSessionCreateParams{
			PublicKey: sdk.F[string](""),
		},
	})
	if err != nil {
		panic(err)
	}

	fmt.Println(ssh.SessionID)
}

func _smokeCase10() {
	ssh, err := client.Machines.SSH.Get(context.Background(), sdk.MachineSSHGetParams{
		MachineID: "017f22e2-79b0-7cc3-98c4-dc0c0c07398f",
		SessionID: "sessionID",
	})
	if err != nil {
		panic(err)
	}

	fmt.Println(ssh.SessionID)
}

func _smokeCase11() {
	ssh, err := client.Machines.SSH.Delete(context.Background(), sdk.MachineSSHDeleteParams{
		MachineID: "017f22e2-79b0-7cc3-98c4-dc0c0c07398f",
		SessionID: "sessionID",
	})
	if err != nil {
		panic(err)
	}

	fmt.Println(ssh.SessionID)
}

func _smokeCase12() {
	page, err := client.Machines.Executions.List(context.Background(), sdk.MachineExecutionListParams{
		MachineID: "017f22e2-79b0-7cc3-98c4-dc0c0c07398f",
	})
	if err != nil {
		panic(err)
	}

	fmt.Println(page)
}

func _smokeCase13() {
	execution, err := client.Machines.Executions.New(context.Background(), sdk.MachineExecutionNewParams{
		MachineID: "017f22e2-79b0-7cc3-98c4-dc0c0c07398f",
		ExecutionCreateParams: sdk.ExecutionCreateParams{
			Command: sdk.F[[]string]([]string{""}),
		},
	})
	if err != nil {
		panic(err)
	}

	fmt.Println(execution.ExecutionID)
}

func _smokeCase14() {
	execution, err := client.Machines.Executions.New(context.Background(), sdk.MachineExecutionNewParams{
		MachineID: "017f22e2-79b0-7cc3-98c4-dc0c0c07398f",
		ExecutionCreateParams: sdk.ExecutionCreateParams{
			Command:   sdk.F[[]string]([]string{""}),
			Cwd:       sdk.F[string](""),
			Env:       sdk.F[map[string]string](map[string]string{}),
			Stdin:     sdk.F[string](""),
			TimeoutMs: sdk.F[int64](0),
		},
	})
	if err != nil {
		panic(err)
	}

	fmt.Println(execution.ExecutionID)
}

func _smokeCase15() {
	execution, err := client.Machines.Executions.Get(context.Background(), sdk.MachineExecutionGetParams{
		ExecutionID: "executionID",
		MachineID:   "017f22e2-79b0-7cc3-98c4-dc0c0c07398f",
	})
	if err != nil {
		panic(err)
	}

	fmt.Println(execution.ExecutionID)
}

func _smokeCase16() {
	execution, err := client.Machines.Executions.Delete(context.Background(), sdk.MachineExecutionDeleteParams{
		ExecutionID: "executionID",
		MachineID:   "017f22e2-79b0-7cc3-98c4-dc0c0c07398f",
	})
	if err != nil {
		panic(err)
	}

	fmt.Println(execution.ExecutionID)
}

func _smokeCase17() {
	execution, err := client.Machines.Executions.Output(context.Background(), sdk.MachineExecutionOutputParams{
		ExecutionID: "executionID",
		MachineID:   "017f22e2-79b0-7cc3-98c4-dc0c0c07398f",
	})
	if err != nil {
		panic(err)
	}

	fmt.Println(execution.ExecutionID)
}

func _smokeCase18() {
	page, err := client.Machines.Executions.Events(context.Background(), sdk.MachineExecutionEventsParams{
		ExecutionID: "executionID",
		MachineID:   "017f22e2-79b0-7cc3-98c4-dc0c0c07398f",
	})
	if err != nil {
		panic(err)
	}

	fmt.Println(page)
}

var cases = []smokeCase{
	{
		Operation: "list",
		Method:    "GET",
		Path:      "/v1/machines",
		Run:       _smokeCase0,
	},

	{
		Operation: "create",
		Method:    "POST",
		Path:      "/v1/machines",
		Run:       _smokeCase1,
	},

	{
		Operation: "retrieve",
		Method:    "GET",
		Path:      "/v1/machines/{machine_id}",
		Run:       _smokeCase2,
	},

	{
		Operation: "update",
		Method:    "PATCH",
		Path:      "/v1/machines/{machine_id}",
		Label:     "required params",
		Run:       _smokeCase3,
	},

	{
		Operation: "update",
		Method:    "PATCH",
		Path:      "/v1/machines/{machine_id}",
		Label:     "all params",
		Run:       _smokeCase4,
	},

	{
		Operation: "delete",
		Method:    "DELETE",
		Path:      "/v1/machines/{machine_id}",
		Run:       _smokeCase5,
	},

	{
		Operation: "sleep",
		Method:    "POST",
		Path:      "/v1/machines/{machine_id}/sleep",
		Run:       _smokeCase6,
	},

	{
		Operation: "wake",
		Method:    "POST",
		Path:      "/v1/machines/{machine_id}/wake",
		Run:       _smokeCase7,
	},

	{
		Operation: "list",
		Method:    "GET",
		Path:      "/v1/machines/{machine_id}/ssh",
		Run:       _smokeCase8,
	},

	{
		Operation: "create",
		Method:    "POST",
		Path:      "/v1/machines/{machine_id}/ssh",
		Run:       _smokeCase9,
	},

	{
		Operation: "retrieve",
		Method:    "GET",
		Path:      "/v1/machines/{machine_id}/ssh/{session_id}",
		Run:       _smokeCase10,
	},

	{
		Operation: "delete",
		Method:    "DELETE",
		Path:      "/v1/machines/{machine_id}/ssh/{session_id}",
		Run:       _smokeCase11,
	},

	{
		Operation: "list",
		Method:    "GET",
		Path:      "/v1/machines/{machine_id}/executions",
		Run:       _smokeCase12,
	},

	{
		Operation: "create",
		Method:    "POST",
		Path:      "/v1/machines/{machine_id}/executions",
		Label:     "required params",
		Run:       _smokeCase13,
	},

	{
		Operation: "create",
		Method:    "POST",
		Path:      "/v1/machines/{machine_id}/executions",
		Label:     "all params",
		Run:       _smokeCase14,
	},

	{
		Operation: "retrieve",
		Method:    "GET",
		Path:      "/v1/machines/{machine_id}/executions/{execution_id}",
		Run:       _smokeCase15,
	},

	{
		Operation: "delete",
		Method:    "DELETE",
		Path:      "/v1/machines/{machine_id}/executions/{execution_id}",
		Run:       _smokeCase16,
	},

	{
		Operation: "output",
		Method:    "GET",
		Path:      "/v1/machines/{machine_id}/executions/{execution_id}/output",
		Run:       _smokeCase17,
	},

	{
		Operation: "events",
		Method:    "GET",
		Path:      "/v1/machines/{machine_id}/executions/{execution_id}/events",
		Run:       _smokeCase18,
	},
}

func selectedCases() []smokeCase {
	filter := os.Getenv("SCALAR_SMOKE_FILTER")
	if filter == "" {
		return cases
	}
	needles := strings.Split(filter, ",")
	selected := make([]smokeCase, 0, len(cases))
	for _, testCase := range cases {
		for _, needle := range needles {
			needle = strings.TrimSpace(needle)
			if needle == "" {
				continue
			}
			if strings.Contains(testCase.Operation, needle) || strings.Contains(testCase.Path, needle) {
				selected = append(selected, testCase)
				break
			}
		}
	}
	return selected
}

// How many cases run at once. A large SDK has hundreds of operations, and one goroutine per case
// puts more requests in flight than the client's transport pools connections for. SCALAR_SMOKE_CONCURRENCY
// overrides the cap; anything unparseable falls back to the default.
func smokeConcurrency(caseCount int) int {
	limit := 32
	if override, err := strconv.Atoi(os.Getenv("SCALAR_SMOKE_CONCURRENCY")); err == nil && override > 0 {
		limit = override
	}
	if caseCount < limit {
		return caseCount
	}
	return limit
}

func runCase(testCase smokeCase) (result smokeResult) {
	startedAt := time.Now()
	result = smokeResult{
		Operation: testCase.Operation,
		Method:    testCase.Method,
		Path:      testCase.Path,
		Label:     testCase.Label,
		Status:    "passed",
	}
	defer func() {
		result.DurationMs = time.Since(startedAt).Milliseconds()
		if recovered := recover(); recovered != nil {
			result.Status = "failed"
			result.Error = fmt.Sprint(recovered)
		}
	}()
	testCase.Run()
	return result
}

func main() {
	selected := selectedCases()
	results := make([]smokeResult, len(selected))
	var wg sync.WaitGroup
	// Buffered channel as a counting semaphore: every goroutine still starts, but only
	// smokeConcurrency of them hold a slot — and so have a request in flight — at a time.
	semaphore := make(chan struct{}, smokeConcurrency(len(selected)))
	for index, testCase := range selected {
		wg.Add(1)
		go func(index int, testCase smokeCase) {
			defer wg.Done()
			semaphore <- struct{}{}
			defer func() { <-semaphore }()
			results[index] = runCase(testCase)
		}(index, testCase)
	}
	wg.Wait()

	failed := 0
	for _, result := range results {
		if result.Status == "failed" {
			failed++
		}
	}

	report := map[string]interface{}{"total": len(results), "failed": failed, "results": results}
	if reportPath := os.Getenv("SCALAR_SMOKE_REPORT"); reportPath != "" {
		bytes, err := json.Marshal(report)
		if err != nil {
			panic(err)
		}
		if err := os.WriteFile(reportPath, bytes, 0o644); err != nil {
			panic(err)
		}
	} else {
		for _, result := range results {
			suffix := ""
			if result.Label != "" {
				suffix = " [" + result.Label + "]"
			}
			if result.Status == "passed" {
				fmt.Printf("PASS %s%s (%s %s) %dms\n", result.Operation, suffix, result.Method, result.Path, result.DurationMs)
			} else {
				fmt.Fprintf(os.Stderr, "FAIL %s%s (%s %s)\n%s\n", result.Operation, suffix, result.Method, result.Path, result.Error)
			}
		}
		if len(results) == 0 {
			fmt.Fprintln(os.Stderr, "No code samples ran (empty SDK or a SCALAR_SMOKE_FILTER that matched nothing).")
		} else {
			fmt.Printf("\n%d/%d samples passed\n", len(results)-failed, len(results))
		}
	}

	if failed > 0 || len(results) == 0 {
		os.Exit(1)
	}
}
